### ISSUE TITLE
Browser resize doesn't resize the rdp window.

### ISSUE THREAD

**Issue by tmakaro** [cedrozor/myrtille#10]
I've only tried this on Windows 10 using chrome but the rdp window doesn't resize if you resize the browser window.

**Comment by cedrozor** [comment]
Yes, it's because the window size of the rdp session is defined at start, when the session opens. Then, it becomes a session context, no longer bound to the client (browser).
That said, I think the latest version of freerdp is "responsive"; I will check that soon as I almost finished reporting the myrtille code into it.

**Comment by cedrozor** [comment]
I recenty added this feature to myrtille (will be available in 1.5.0 release); it will be disabled by default, but dynamically activatable using a button during the rdp session
