### ISSUE TITLE
Myrtille Screen Frozen 

### ISSUE THREAD

**Issue by welsonplay** [cedrozor/myrtille#105]
When I hibernate the notebook and go back to the Myrtille page the screen is frozen. Is there any way to recode the websocket or simply redirect to login screen without getting on the frozen screen?

**Comment by cedrozor** [comment]
The websocket is forcibly closed server side (myrtille gateway) when your notebook goes into hibernation. That means you have to refresh (F5) the page when you have your notebook out of hibernation, for the browser to re-establish a websocket connection with the gateway.

Did you also removed (or extended) the session idle timeout on your rdp server? otherwise, the session will be disconnected while your notebook hibernates.

[RDS 2016 session limits](https://serverfault.com/questions/873399/rds-2016-session-limits)

**Comment by cedrozor** [comment]
In order not being redirected to the login screen when you refresh (F5) the page, you'll also have to remove (or extend) the [http session timeout](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/Web.Base.config#L53) into the myrtille web.config.

**Comment by cedrozor** [comment]
does that answer your question?

**Comment by welsonplay** [comment]
I will close the issue, because I have not been able to test it yet. As soon as I do this implementation I give the feedback.

Thank you for your help.
