### ISSUE TITLE
Not able to open program using 'url'

### ISSUE THREAD

**Issue by rajan-github** [cedrozor/myrtille#106]
Hi,
I have installed myrtille 1.8 using the setup.exe on window 2016 server. Before installing the mytille i enable IIS server. Now i am able to connect to the remote desktop. But when i try to open a program using following url-
**Edited: caution not giving away your remote desktop access credentials to the world!**

It always shows me desktop and  notepad is never opened. I am wondering what could possibly go wrong since in documentation for installation you haven't mentioned anything to setup. I am not getting error. Is there any file where logs are being written and i could look to figure out the cause.
I have visited [issue#27](https://github.com/cedrozor/myrtille/issues/27), [issue#104](https://github.com/cedrozor/myrtille/issues/104) but i couldn't succeed.
Also is there anything else apart from [Installation](https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#installation) we need to do for enabling the myrtille to open program using URL?
Thanking you in anticipation!

**Comment by cedrozor** [comment]
Hi Rajan,

I edited your post because you gave away to everyone your server address and credentials within the url. I was able to connect your server an indeed notepad didn't run. I saw RDPSetup.reg was selected, so I guess you imported it.

Is the server part of a RDS farm? if so, you have to configure the session collection on your connection broker to allow to run unlisted programs, or add notepad to the allowed programs.

If you want to distribute the url to third parties, you may want to [hash the password](https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#password-hash). People will be able to connect the server but only through myrtille, so you can configure access restrictions into IIS; they won't know the real password and won't be able to connect the server directly.

**Comment by rajan-github** [comment]
Hi,
Thank you for editing my post. Indeed i wanted to give you credentials for you to try because i already spend few hours figuring out and couldn't and whatever examples are given they are clear to me.
"Is the server part of a RDS farm?" Sorry i did not get it..i am new to this stuff. 
I am also getting following error in browser console-
"VM18597:164 WebSocket connection to 'ws://SERVER_ADDRESS/Myrtille/(S(1zomv2l43ih321zrq44t45so))/SocketHandler.ashx?type=binary' failed: Error during WebSocket handshake: Unexpected response code: 200"
Does this error indicate something wrong on my server?
Can you please elaborate on this and tell me what can i do to resolve it?

Thank you for quick response. I admire your passion for software!

**Comment by rajan-github** [comment]
01000000D08C9DDF0115D1118C7A00C04FC297EB0100000018B795C7FB81B045A3BBB131109D41FC040000000200000000001066000000010000200000006893757BA8218CA03DD1741BCBD8FBFF0C2255E22C185B4CAB6149A036C12E2B000000000E800000000200002000000058C4985099A3A2073E4492E120E447F48C45C7099EAC6F0D0FB9F1F9B8A1B8032000000048DD9AE125BB54BF7BAB846D2C508237DA6EB62A0FF5C5051A996B6781DC794040000000436646D5E4A7D1183A172EDDBB2FC3CBEF93CEC9C2A6B12890951F113D608BFC27BE8719EFEABB17B109E4F4CD98227D3524DA730F8656061FB82C1542152544

**Comment by cedrozor** [comment]
The websocket error is probably due to the fact you didn't enabled the websocket protocol into IIS; follow this: https://docs.microsoft.com/en-us/iis/configuration/system.webServer/webSocket to enable it.

To allow notepad to run as alternate shell (normally not needed but that depends on your config), try this: https://www.server-world.info/en/note?os=Windows_Server_2016&p=remotedesktop&f=5 (just replace the server manager by notepad)

The generation of hashed passwords is done indeed on the myrtille gateway; it's an additional protection to ensure you are allowed to do it. But sure, there are many ways to automate powershell scripts, and you can also do it programmatically (https://github.com/cedrozor/myrtille/blob/master/Myrtille.Common/Helpers/RDPCryptoHelper.cs)

To copy&paste the hashed password to your local system, it's normally transparent if you use mstsc and allowed the use of clipboard; if you use myrtille to do it, you can retrieve the remote clipboard by clicking the clipboard button into the toolbar

**Comment by bigpjo** [comment]
It appears the /shell parameter has been removed from remotesessionprocess of myrtille.service project. I believe this is required to start a program when rdp session is created

**Comment by rajan-github** [comment]
@bigpjo Can i add /shell  parameter somehow to myrtille.service to enable myrtille to open a program? Or is there any alternative way to achieve the same?
Thanks,

**Comment by bigpjo** [comment]
Hi all, sorry for the misinformation, it did think it was a little odd it
may have been taken out.

**Comment by rajan-github** [comment]
Hi All,
Could this problem be because of IIS server config? What minimum config is required to enable the myrtille to open the program?

**Comment by cedrozor** [comment]
Hi, no it's not a IIS config and there is no minimum config. Did you tried with mstsc?

**Comment by rajan-github** [comment]
Hi,
I tried and i couldn't run it as you instructed(options > programs (tab) > start a program). I am not getting these options and here i am attaching the screenshots for more information-
![shot1](https://user-images.githubusercontent.com/15207869/40293059-a9914ba0-5cec-11e8-9e77-b32f17da2c0a.PNG)
![shot2](https://user-images.githubusercontent.com/15207869/40293066-ae447532-5cec-11e8-8648-d67a34868500.PNG)

**Comment by rajan-github** [comment]
Now i am trying with window server 2012 and still facing the same issue-
I enter following URL-

`
https://10.134.114.136/Myrtille/(S(eejeugotmrismwjmfabgj1xb))/Default.aspx?__EVENTTARGET=&__EVENTARGUMENT=&server=localhost&user=USER&password=PASSWORD&program=C%3A%5CWindows%5CWinSxS%5Cwow64_microsoft-windows-notepad_31bf3856ad364e35_6.2.9200.21545_none_d2eea7154721138a%5Cnotepad.exe&connect=Connect!
`

But still it shows desktop and URL gets converted to following:
`https://10.134.114.136/Myrtille/(S(jtum3unsn1cxbpe4tv4xjysk))/?`

And no error message is shown. Where can i see what is going wrong here?

**Comment by rajan-github** [comment]
I run the Myrtille.services.exe i am getting following error: 
![myrtille_error](https://user-images.githubusercontent.com/15207869/40305758-87638a98-5d19-11e8-8aa0-7292d9ed2448.PNG)

Does it indicate some error on my side?

**Comment by cedrozor** [comment]
mstsc on a 2016 server, like windows 10, doesn't have the option to run a program (as alternate shell) on connect; but (and that's a little weird, I agree), the 2016 server does support that feature.

But if you try mstsc from a windows 7, you have the option:

![image](https://user-images.githubusercontent.com/17749498/40308934-19ed769c-5d08-11e8-9c94-8ebe2ce03e97.png)

wfreerdp, unlike mstsc, has that feature built-in whatever the machine it's running on, given the target (connected) machine is a windows server edition (not 7, 8 or 10).

On my last tests, the alternate shell (used by myrtille "start program from url") works on servers 2012 and 2016. **I'm currenty doing a full windows update on my 2016 test VM to see whether if MS has removed the feature (possible).**

Regarding the url correct syntax, you have to encode (using https://www.url-encode-decode.com/) the params, so the connect param is not "`Connect!`" but "`Connect%21`". By the way, are you sure of the notepad path?! `c:\windows\system32\notepad.exe` is the standard location.

So you url should be `https://10.134.114.136/Myrtille/(S(eejeugotmrismwjmfabgj1xb))/Default.aspx?__EVENTTARGET=&__EVENTARGUMENT=&server=localhost&user=USER&password=PASSWORD&program=c%3A%5Cwindows%5Csystem32%5Cnotepad.exe&connect=Connect%21`

Also, the http session ID (`(S(eejeugotmrismwjmfabgj1xb))`) is changed upon login, it's normal to see another one afterward.

You can enable logs [here](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/app.config#L142) (set the value to "true", save file and restart Myrtille.Services windows service) and check logs into the myrtille "log" folder.

About **RDPSetup.reg**, it's a set of registry entries to configure your rdp server(s) automatically. Just copy it over your rdp server(s) (in your case it's localhost so the myrtille gateway is also the rdp server) and double-click it to import the keys inside. Among other things, it will allow unlisted programs (such as notepad.exe) to be run as alternate shell. Depending on your domain or server policies, it may be required. So yes, **you should import it**.

**Myrtille.Services.exe** is not meant to be run from console (unless you are under Visual Studio?). The error message is because it's already running (as windows service) and the WCF endpoints are already registered.

**Comment by rajan-github** [comment]
Hi,
I enabled logs and saw that its able to read program parameter from URL properly but when i type that program address in powershell/cmd nothing happens: **No program is opening** .  It should open that program or give some error but nothing is happening on both powershell & cmd. What could be the issue? 
Also when i am changing path of the program and making it incorrect by appending some character then it raises error as follows:

>  is not recognized as the name of a cmdlet

What could be the issue. I also noticed when i enter myrtille URL in browser it logs in fresh everytime that means its working correctly?

**Comment by cedrozor** [comment]
I fully updated my 2016 server VM and the alternate shell is working as expected: the start program from url does work, for **c:\windows\system32\notepad.exe** (`&program=c%3A%5Cwindows%5Csystem32%5Cnotepad.exe`)

Why looking for notepad.exe into `&program=C%3A%5CWindows%5CWinSxS%5Cwow64_microsoft-windows-notepad_31bf3856ad364e35_6.2.9200.21545_none_d2eea7154721138a%5Cnotepad.exe`  and what is this powershell/cmd script you are speaking about?

If running notepad.exe was just a test, I have to say I didn't tested running a powershell cmdlet as alternate shell, so maybe it's not possible. But I know it's possible to run a .bat or .cmd as alternate shell, so you could just run that cmdlet from there.

Indeed, with logs enabled, you will have a **wfreerdp_[pid].log** everytime you connect a server. If that is, myrtille is working correctly and you should have a "**PRG[program to run]**" trace inside the log file.

**Comment by cedrozor** [comment]
I think I have misread your post. You don't try to run a cmdlet, you try to run notepad?

If so, you have to do it from a cmd console; and it's not with the url encoded address used by myrtille... it's **c:\windows\system32\notepad.exe**, right?

If that works (running notepad manually on the server, like that), it should work with the myrtille url...

**Comment by rajan-github** [comment]
It works on server manually: **c:\windows\system32\notepad.exe** is opening notepad through the power shell or cmd but it doesn't open with myrtille?

I am using now following URL:
**`https://10.134.114.136/Myrtille/(S(eejeugotmrismwjmfabgj1xb))/Default.aspx?__EVENTTARGET=&__EVENTARGUMENT=&server=localhost&user=USER&password=PASSWORD&program=c%3A%5Cwindows%5Csystem32%5Cnotepad.exe&connect=Connect%21`**

As you said with log enabled,  **wfreerdp_[pid].log** is being generated but its empty(0 KB) and nothing is being written to this file.

Is it something about mytille config which i have missed? I just installed myrtille using the setup.exe and after that i imported the RDPSetup.reg by double clicking it. Apart from this is there something else i am suppose to do?

I don't see any error in logs and following screenshot is taken from the log file-
![myrtille_log1](https://user-images.githubusercontent.com/15207869/40342916-e9eb7bbc-5daa-11e8-8c25-db1ae40490eb.PNG)

Every thing looks normal but just program is not opening.

**Comment by cedrozor** [comment]
Can you retry with `http://10.134.114.136/Myrtille/?__EVENTTARGET=&__EVENTARGUMENT=&server=localhost&user=USER&password=PASSWORD&program=c%3A%5Cwindows%5Csystem32%5Cnotepad.exe&connect=Connect%21` ? are your USER and PASSWORD correctly url encoded? (should be, the connection would not occur otherwise).

So, the session opens but displays the desktop (instead of opening notepad)? could you try to do some actions (move the mouse, open some applications, etc.) before clicking the toolbar disconnect button. You should have an **exit code 0** into the Myrtille.Services.log and a log file with information. Exit code 65541 indicates an unexpected exit of wfreerdp and that could explain the empty log file (buffered data not written on disk).

Is the machine on a domain and could you have a GPO preventing to start a program on logon or connection? if not, you also have several ways to achieve it, not even using the myrtille url:
- Standard GPO: http://tekbloq.com/2016/08/12/how-to-run-programs-automatically-when-a-user-logs-on-with-gpo/
- RDS GPO: http://www.kuhnline.com/windows-server-2012-r2-remote-desktop-services-start-a-program-on-connection-via-gpo/
- Remote Desktop Services Profile tab in Active Directory Users and Computers: https://serverfault.com/questions/846092/windows-server-2016-remote-desktop-services-starting-program

**Comment by rajan-github** [comment]
Hi,

I tried this new URL and same thing is happening.

I am able to connect to remote desktop and able to use it normally using myrtille URL. But i want program to be opened on session start instead of showing desktop and wants to log off as soon as program closes. 

So program is not opening. I followed [second link](http://www.kuhnline.com/windows-server-2012-r2-remote-desktop-services-start-a-program-on-connection-via-gpo/) and enabled the program on connection as shown in following screenshot but still program is not opening and only desktop is shown without any error?

![mytille_error_23_05_2018](https://user-images.githubusercontent.com/15207869/40422742-dee52fde-5ead-11e8-94be-a328c666a144.PNG)

Now i will try different version of myrtille.

**Comment by cedrozor** [comment]
Do you have something useful into the windows event logs (system or application) on the target server? it looks like a server configuration issue at some level.

**Comment by rajan-github** [comment]
I have followed this [this](https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-8/installing-iis-8-on-windows-server-2012) to configure my IIS server? Is it different from how you configure server on your machine? Please can you list the steps here to configure the server?

**Comment by cedrozor** [comment]
It doesn't have something to do with IIS but, rather, on the AWS instance.

**Comment by cedrozor** [comment]
closing, reopen if needed
