### ISSUE TITLE
unable to generate a password Hash

### ISSUE THREAD

**Issue by medlamin** [cedrozor/myrtille#109]
Hi ,
Please could someone explain me in details how to generate a PasswordHash
Thank you

**Comment by welsonplay** [comment]
Hello @medlamin,

There are two ways to open a session with Myrtille, one using the login screen, and the second through the url URL.

When working with the URL you must pass the user's password through the URL, but this can be a security problem, so Myrtille allows you to generate an encrypted password, and this new encrypted password is the one that goes to the URL.

To generate the encrypted password you can use the [script in powershell](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/Password51.ps1) for this.Lembrando the password will only work if it is generated on the same server that Myrtille is installed.

**Comment by medlamin** [comment]
thank you @welsonplay 
I did try the second way ,the one with the URL but I still have to retype my password again in the login screen (it fills the server,Domain,User fields for me) is it a normal thing ?I expected that I get my program running after lunching the URL.
Thank you again

**Comment by welsonplay** [comment]
When you log in to the url, you do not have to enter a password. a session
is automatically automatic. Are you passing the encrypted password or not?
a password is registered, keep having a password on the myrtille server.
Em qua, 23 de mai de 2018 às 17:19, medlamin <notifications@github.com>
escreveu:

**Comment by medlamin** [comment]
@welsonplay 
Thank you sir,I was doing it the wrong way! It works like a charm !.
is there any way I can skip the display of windows session loading and jump forward to the program ??I

**Comment by welsonplay** [comment]
Unfortunately I do not know of any way to do this. I put the following message: Loading application and put the setTimeout of 7000 milliseconds. This time is more than enough to load the user profile.

**Comment by cedrozor** [comment]
Among other options, you can remove the [session disconnection timeout](https://serverfault.com/questions/873399/rds-2016-session-limits) ("end a disconnected session":  Never) so that a previously disconnected session will load very fast; only the first connect will take some time and display the windows session loading (that also depends on the machine speed, a good cpu and an ssd will make it faster). 

You can also prefer a VM based desktop deployment (Hyper-V VDI) to a session based deployment (RDSH); there will be more resources allocated per desktop, even have it pre-loaded for a direct access. 
- [Installing Remote Desktop Services 2016](http://www.lemonbits.com/2017/02/26/installing-rds-2016/)
- [Difference between virtual machine based desktop deployment versus session-based desktop deployment](https://social.technet.microsoft.com/Forums/en-US/f7e7ed38-97e0-499a-ab4a-719aa161fb8f/what-is-difference-between-virtual-machine-based-desktop-deployment-versus-sessionbased-desktop?forum=winserverTS)

**Comment by cedrozor** [comment]
Closing, as you seem to have it working now. Thanks for your help @welsonplay :)

**Comment by welsonplay** [comment]
Whenever I can I will help the Myrtille community.
