### ISSUE TITLE
CredSSP error

### ISSUE THREAD

**Issue by stijnsta** [cedrozor/myrtille#110]
I downloaded the latest version of myrtille (installer). Could it be that the freerdp version you're using still faces the CredSSP error on connecting to a remote desktop? Are there plans on updating your version? I tried using the standard wfreerdp.exe, but that one doesn't work with myrtille.

**Comment by cedrozor** [comment]
FreeRDP is a bit unstable since recent MS updates (https://github.com/neutrinolabs/xrdp/issues/1083) and Kerberos support (https://github.com/FreeRDP/FreeRDP/issues/4525).

I'm following that closely; I had implemented some code into myrtille pre 1.9.0 to resolve the target IP, instead of using the hostname/FQDN, for both direct and connection broker redirect connections.

For Myrtille 1.9.0, I tested with openssl 1.1.0, connecting with IPs, hostnames and FQDNs, using a domain controller and connection broker; maybe I had luck, or my VMs weren't fully updated, but I didn't had any issue. So, I removed my custom code to resync with the FreeRDP base code. I could re-implement it, if needed.

Could you please enable the FreeRDP logs ([here](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/app.config#L163), set value "true") and paste me the error(s) you have?

For now, you may circumvent the problem by connecting with IP, instead of hostname/FQDN, or by enforcing NLA or TLS authentication; ensure your target have NLA enabled and use the myrtille enterprise mode ([here to enable an configure](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/app.config#L174)) to change the security mode of the connection; default is AUTO, set it NLA or TLS.

The standard freerdp.exe won't work; myrtille uses a [customized fork](https://github.com/cedrozor/FreeRDP/blob/master/client/Windows/wf_myrtille.cpp) to accommodate with its needs.

**Comment by stijnsta** [comment]
The error I'm getting is always: The above X.509 certificate could not be verified, possibly because you do not have the CA certificate in your certificate store, or the certificate has expired. Please look at the OpenSSL documentation on how to add a private CA to the store.
I tested a bit with the standard version of freerdp. I kept getting the error on my server 2012 r2 machine. After upgrading to server 2016 I could again connect, but only with the standard version of freerdp.

I will look into changing the authentication to NLA or TLS. Hopefully that will work. But it would be nice if it worked out of the box with the openssl code.

**Comment by cedrozor** [comment]
This isn't the error I expected; which is:
```
2018-03-22 12:42:56,418 [9] DEBUG com.freerdp.core.nla - nla_client_recv status 1
2018-03-22 12:42:56,418 [9] ERROR com.freerdp.core - freerdp_set_last_error ERRCONNECT_PASSWORD_CERTAINLY_EXPIRED [0x0002000F]
2018-03-22 12:42:56,418 [9] ERROR com.freerdp.core.transport - BIO_read returned an error: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
2018-03-22 12:42:56,418 [9] DEBUG com.freerdp.core.transport - transport_check_fds: transport_read_pdu() - -1
2018-03-22 12:42:56,418 [9] DEBUG com.freerdp.core.rdp - transport_check_fds() - -1
```
Do you have such traces into the log\wfreerdp.xxxx.log?

Did you disabled the [ignore certificate param](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/app.config#L197) into bin\Myrtille.Services.exe.config?

For your tests, do you use the myrtille website or do you run wfreerdp.exe directly from the myrtille bin folder? the latter is better for troubleshooting; for example, you could run the following command:
`wfreerdp.exe /v:server /d:domain /u:user /p:password`
and if it doesn't work:
`wfreerdp.exe /v:server /d:domain /u:user /p:password /cert-ignore`

**Comment by stijnsta** [comment]
I was trying it with the wfreerdp from command line directly. There I get these errors. I tried with /cert-ignore, but that doesn't help. With the standard wfreerdp I don't have to add the /cert-ignore parameter for it to work. 
The error came from the command line interface.
I used the command 

> wfreerdp.exe /v:server /d:domain /u:user /p:password > c:\logfile.txt
and 

> wfreerdp.exe /v:server /d:domain /u:user /p:password /cert-ignore > c:\logfile.txt
both give the same error to the logfile

> The above X.509 certificate could not be verified, possibly because you do not have the CA certificate in your certificate store, or the certificate has expired. Please look at the OpenSSL documentation on how to add a private CA to the store.

I checked the certificate. It is not expired. But it is a self-signed certificate.

**Comment by cedrozor** [comment]
By "standard wfreerdp", do you mean the latest nightly build or a version you built yourself? which version of openssl does it use? (`wfreerdp.exe /version`) statically or dynamically linked?

Did you created the self-signed ssl certificate yourself? It's weird the `/cert-ignore` option doesn't work. Myrtille needs it because there is no way to display the interactive dialog for the user to accept the certificate or not.

**Comment by cedrozor** [comment]
I released an update that could be related/fix your issue: https://github.com/cedrozor/myrtille/releases

**Comment by stijnsta** [comment]
With command line it seems to work now. We're still using an outdated version of myrtille because we changed some code to connect to our db for some extra's, with that version the new wfreerdp exe doesn't work, but I will try to fix that, probably something with the transmitting of data or something like that.

Thanks for the help.

**Comment by cedrozor** [comment]
wfreerdp.exe works now with the latest version (1.9.1) when it didn't previously (1.9.0)? if yes, that's interesting and the issue I was thinking about.

Which version did you modified for your needs? some commands, data structures and connection handshaking did indeed changed from time to time, so the web gateway and the rdp client (wfreerdp.exe) must be the same version.

Normally, you just have to resync your fork, or re-apply your changes, to the latest gateway version for myrtille to work.

**Comment by stijnsta** [comment]
Yes, version 1.9.1 works, 1.9.0 didn't. 
We modified myrtille (the default.aspx and some of the code behind) to make it connect to our sql server. I can't remember the version, but it's been a few years I'm afraid. 
If I'm understanding the Enterprise mode correct, then that is a bit like what we implemented. So I will be looking into that to use the newest version of myrtille. 
I positive it'll work.

Thanks for the help.

**Comment by stijnsta** [comment]
Just a small question:
I keep getting the following error: Disconnected remote session 1, exit code 131078
any idea?

**Comment by cedrozor** [comment]
Nice to hear it works with 1.9.1 :)

About the (wfreerdp.exe) exit code 131078, I have no idea what it is (should be 0 normally). It's not referenced into the win32 error codes (https://msdn.microsoft.com/en-us/library/cc231199.aspx), there is no 0x00020006 (hex) = 131078 (decimal)

Could you enable the FreeRDP logs (bin\Myrtille.Services.exeConfig, set "RemoteSessionLog" value "true") and have a look for more details? Do you succeed connecting your rdp server with wfreerdp.exe from command line but not with myrtille?

**Comment by cedrozor** [comment]
Ok just found something interesting: https://github.com/FreeRDP/FreeRDP/issues/4575, which states a 0x00020006 connection issue.

The person had specifically disabled NLA because it didn't connect from a domain joined system; by the way, if the machine on which myrtille is installed isn't part of the target domain, and you don't specify the domain (into the login screen) explicitly, there may be some connections troubles as well.

You should activate the enterprise mode (you wanted to test it anyway); there you can change the connection security mode (RDP, TLS, NLA, AUTO), for your target server, and check what works or not.

**Comment by cedrozor** [comment]
Please keep me updated

**Comment by stijnsta** [comment]
Forgot to reply, but it works. The issue was indeed that my testmachine was not in the same domain. Thanks for the help.

**Comment by cedrozor** [comment]
You are welcome.
