### ISSUE TITLE
Migrate from SQL CE to SQL Express

### ISSUE THREAD

**Issue by 11harveyj** [cedrozor/myrtille#117]
As SQL CE is now deprecated, Microsoft recommends using SQL Express or SQL LocalDB. 

As I prefer to use SQL Server (backups etc.) while, it's possible, its not overly simple to change from SQL CE to SQL Server. I might not have looked into this enough, however maybe create a SQL script admins can use to easily migrate rather than searching around the internet (like I had to do) to find the correct runtime environments and files to convert the sdf into a sql script. 

And also as far as I'm aware, SQL CE support isn't shipped with Windows by default (explains the whole runtime thing).

**Comment by 11harveyj** [comment]
Understood!

Unfortunately you can no longer open SQL CE databases in SSMS (SSMS 2012+). So without using 3rd party tools (not developed by Microsoft say), we have no way of converting the SQL CE database over to a SQL file and then importing back to a SQL Server installation. 

SQL LocalDB is only 33~mb in size. While agreed SQL CE is still supported and very lightweight, I just want to hear your ideas on migrating away from SQL CE as eventually it will be unsupported. 

http://download.microsoft.com/download/8/D/D/8DD7BDBA-CEF7-4D8E-8C16-D9F69527F909/ENU/x64/SqlLocalDB.MSI

**Comment by cedrozor** [comment]
I understand your concerns and I will look further on replacing SQL CE, even if it's low on my todo list. @bigpjo made the enterprise mode of myrtille, I would be curious to have his opinion on this topic.

I made some quick researches about SQL LocalDB and found a blog from @ErikEJ, the author of the 3rd party toolset I linked in my previous post: http://erikej.blogspot.com/2011/01/comparison-of-sql-server-compact-4-and.html. SQL LocalDB have more requirements (requires admin for installation, can't be privately installed, embedded, with the application, etc.), is more sized (30+MB), but also have more features (role-based security, unlimited concurrent connection, etc.)

If it becomes a myrtille prerequisite (like IIS and ASP.NET, outside of the packaging), I think it's better to go for SQL Express because it's better suited for production use (https://stackoverflow.com/questions/42028186/sql-server-express-vs-express-localdb). SQLite could also be an option.

That would add complexity to the myrtille installation, for something not everyone will use.... but you are right; if someone decides to use the enterprise mode, better have it future proof.

MS is accustomed to dropping some of its products when there are strategic or commercial conflicts with others of their products. I hope SQL LocalDB won't follow the same fate :/

Thanks

**Comment by bigpjo** [comment]
The only reason for the use of SQL CE was to ensure that it keeps the myrtille product completely standalone.

SQL Server is support as well, if you prefer to use a SQL Server database, create an empty SQL server database, update myrtille.services.exe.config 

 <connectionStrings>
    
    <add name="enterpriseDBConnection" providerName="System.Data.SqlServerCe.4.0" connectionString="Data Source=|DataDirectory|MyrtilleEnterprise.sdf"/>
    
  </connectionStrings>

Include the credentials of a SQL Server user which has DBO rights to the database, restart myrtille service (this will cause EF to update the new sql tables).

Other provides can be implmented MySQL even SQLite.
