### ISSUE TITLE
Install problem since version 1.9.0...

### ISSUE THREAD

**Issue by morths** [cedrozor/myrtille#123]
Hello! First of all i really love the myrtille project and you should keep up the good work!!!

Now to the problem...
To be honest, i was getting the classic binding 1001 error during installation, since the very first releases... But i have managed to bypass it somehow by copying four specific files in the empty bin directory, before installing each new release (trick worked until release 1.7.0). The 4 files (i can't remember anymore from which version i had taken them), were "Myrtille.Services.Contracts.dll", "Myrtille.Services.exe", "Myrtille.Services.InstallState", "Myrtille.Web.dll". The only thing i can tell for sure is that when i right-click those files (except the "Myrtille.Services.InstallState" one) and select properties the version states 1.0.0.0.

Now, beginning from 1.9.0 release (i skipped pre-releases 1.8.0 & 1.8.1), the above trick doesn't seem to work anymore (probably something major is changed...).

I really want to properly resolve the 1001 binding error, rather than using tricks, but i am not very good at tampering my server's default settings... Btw i am using windows server 2012 R2 .

Whole error goes like that: cannot add duplicate collection entry of type 'binding' with combined key attributes 'protocol,bindinginformation' respectively set to 'https,*:443:'.

Any help appreciated!!! (actually detailed instructions would be more than highly appreciated!!!)

**Comment by morths** [comment]
Nevermind, i was too hasty to open an issue! I finally managed to properly resolve the error myself.

For anyone who also have the same issue, it was pretty simple... I opened IIS from administrative tools, went to default website, opened bindings and removed an https entry from there.

Woila!! After that installation completed succefully! It seems that myrtille installation automatically adds an https entry in bindings and if there is already such entry there the installation never completes.

P.S.: After myrtille successfully installed, i removed its https entry from bindings and restored my own. Everything works like a charm now! thnx!!

**Comment by cedrozor** [comment]
Hi, thanks for the information and I'm sorry for the hassle.

About the 1001 issue, it was reported since early releases when I added the installation of a self-signed certificate into the installer, in order for myrtille to support https from scratch. But that code requires the management console to be enabled into IIS (and it's not by default into some Windows versions). I had it referenced into the troubleshoot section: https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#troubleshoot

The 1001 error could also happen if you have IIS express installed along with the standard IIS (which could be the case on a development machine), but this was normally fixed since version 1.5.0.

In the next myrtille release, I will make the installation of a self-signed certificate optional and check for an existing occurrence before installing it.

**Comment by morths** [comment]
Thank you for your answer!! 
Although i consider this resolved, if you really can make this step optional, it would save me the trouble of removing and re-inserting my https certificate, before and after next releases installations respectively.

thnx anyway!!

**Comment by cedrozor** [comment]
Myrtille version 2..0.0 is released with that feature (being able to skip the SSL certificate) on the installer. Please tell me if you still have any issue!
