### ISSUE TITLE
connection to Hyper-V virtual machines?

### ISSUE THREAD

**Issue by jol64** [cedrozor/myrtille#124]
Any plan to support connections to vm like FreeRDP does with /vmconnect:<vmid> ? Or is that possible and just not exposed on the login form?
Thanks, Joachim

**Comment by cedrozor** [comment]
I wanted to do it but never suceeded to have wfreerdp working with it. I tried many things, but wfreerdp struggles with NLA. I tried to uncheck the NLA requirement on the VM  and use RDP security protocol instead, but wfreerdp just freeze up without displaying any window (and it's not due to the myrtille code because I disabled it for my tests).

This is curious anyway because the wfreerdp documentation specially states to disable negotiation (and ignoring certificate) but adding the "-nego" and "/cert-ignore" params doesn't help either.

Anyway, you could just enable remote access on your VM and connect it normally through RDP. By the way, Hyper-V itself uses an RDP extension to connect the VM (that's why it was implemented into FreeRDP in fact).

**Comment by jol64** [comment]
I don´t want to use RDP directly for a) is not necessarily enabled in all VMs (consider linux vms), b) networking issues (may not have a network connection or be in a different network for security reasons and may use DHCP), c) cannot be used during system startup.

Actually I succeeded with both FreeRDP (wfreerdp 2.0.0dev3) and Guacamole to connect to Hyper-V virtual machines. Essentially I miss the /vmconnect parameter, which afai understand sets the preconnection-blob and changes the port to 2179.

You may wonder why I ask here if Guacamole works - the reason is that I want to have a Windows only solution (and docker on Windows is also not a reliable option).

**Comment by cedrozor** [comment]
Yes, I understand the reasons but I just can't have wfreerdp to work with it (just passed the last 3 hours on it).

I tried as follow:
`wfreerdp /u:vmuser /p:vmpassword /v:vmhost:2179 /vmconnect:vmguid`
`wfreerdp /u:vmuser /p:vmpassword /cert-ignore /v:vmhost:2179 /vmconnect:vmguid`
`wfreerdp /u:vmuser /p:vmpassword /cert-ignore -nego /v:vmhost:2179 /vmconnect:vmguid`
`wfreerdp /u:vmuser /p:vmpassword /cert-ignore -nego -sec-nla /v:vmhost:2179 /vmconnect:vmguid`
`wfreerdp /u:vmuser /p:vmpassword /cert-ignore -nego +sec-rdp /v:vmhost:2179 /vmconnect:vmguid`

Nothing works.

Could you post me the command line you are using (masking credentials)?

Guacamole uses FreeRDP 1.x and I found wfreerdp 2.0.0dev3 quite unstable (even myself pull requested some fixes, regarding NLA, FQDN resolving and IPv6 to the FreeRDP master repo).

**Comment by cedrozor** [comment]
I just retested and still no luck :/ I tried the [latest nightly build](https://ci.freerdp.com/job/freerdp-nightly-windows/lastBuild/) ("This is FreeRDP version 2.0.0-dev4 (92c2d83a4)"), 32 and 64 bits version, and got that error with the same command line as yours:
```
[18:24:58:364] [13760:00002434] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_LOGON_FAILURE [0x00020014]
[18:24:58:364] [13760:00002434] [ERROR][com.freerdp.core.rdp] - rdp_recv_callback: CONNECTION_STATE_NLA - nla_recv_pdu() fail
[18:24:58:365] [13760:00002434] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
[18:24:58:365] [13760:00002434] [DEBUG][com.freerdp.core.rdp] - transport_check_fds() - -1
[18:24:58:365] [13760:00002434] [DEBUG][com.freerdp.client.windows] - Main thread exited with 131092
[18:24:58:366] [13760:000031bc] [DEBUG][com.freerdp.client.windows] - Keyboard thread exited.
```
I have Hyper-V on a Windows 10 Pro x64 and the guest VM is a 2016 server x64. I can connect it without any issue with the Hyper-V vmconnect tool.

What is you environment spec (Hyper-V and VM)?

I may open an issue on the FreeRDP tracker.

**Comment by jol64** [comment]
what exactly matters... on the server I am running Windows 10 Pro 1803 64bit, Hyper-V is installed. I usually test with VMs that are also Windows 10 Pro 1803, some others are Windows 10 Enterprise don´t know the exact version, and I also have some Linux VMs but not sure I tested anything else than Guacanole. With windows clients I can usually connect with VMConnect, FreeRDP, FreeRDP-WebConnect, or Guacamole.
I know the server is a domain member. I am not sure about the current CredSSP or other authentication setting - and not sure I really know what matters, only that I experimented with CredSSP in the context of VMConnect.

I suspect the difference between our environments is the server and not the specific command line setting. I just double checked and Guacamole is using NLA, and based on the errors you get it looks like NLA was tried. Googling I found https://social.technet.microsoft.com/Forums/azure/en-US/9f7881d5-1960-41c7-9528-c1a671ee88b7/rdp-issues-remote-computers-requires-network-level-authentication?forum=winserverTS which indicates a broken cert, but I guess there can be many other causes. 
Maybe really ask on FreeRDP for help (or more useful error messages).

**Comment by cedrozor** [comment]
There were some windows updates lately related to credSSP, I'm think my
windows 10 is up to date, but I'm not sure about the 2016 vm... I will
check and update both of them tomorrow.

**Comment by cedrozor** [comment]
I updated both the Hyper-V host machine (Windows 10 pro) and the guest VM (2016 Server). Still no luck, same NLA error message. I will ivestigate (debug FreeRDP code) and test with a Windows 10 pro VM.

**Comment by cedrozor** [comment]
Ok I found the problem! the user I passed to wfreerdp, on the Hyper-V host, wasn't member of the "Hyper-V Administrators" group (https://github.com/FreeRDP/FreeRDP/issues/2421#issuecomment-274452213). I added it and it worked! :) I'll see to add the feature.

**Comment by cedrozor** [comment]
Done into version 2.1.0

**Comment by jol64** [comment]
Thanks for implementing that - and that fast. Tested ok.
However Hyper-V-Admin membership should not be required, VMConnectAccess should be sufficient and is in my tests.

**Comment by jol64** [comment]
https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#notes-and-limitations
>  and a valid user/password on that host (no domain user). The user must be member of the "Hyper-V Administrators" group on the host.

which host are you referring to? The guest VM? then afaik not correct. Authentication is done locally on the host, and the VM will request authentication on its own. I also used domain users successfully (had to)

**Comment by jol64** [comment]
you may also want to add to your notes that adding ";EnhancedMode=1;" after the VM guid triggers Enhanced Session Mode, which yields better performance and more features like audio redirection.

**Comment by cedrozor** [comment]
Hi, thanks for the information. Indeed, I just watched for usergroup membership, but there are also some Hyper-V cmdlets, `Grant-VMConnectAccess` being one of them: https://docs.microsoft.com/en-us/powershell/module/hyper-v/grant-vmconnectaccess?view=win10-ps

> and a valid user/password on that host (no domain user). The user must be member of the "Hyper-V Administrators" group on the host.

I was speaking about the VM host, not the guest VM. Yes, the authentication is done locally on the host, that's why I wrote no domain user. But it's true that it's possible to use a domain user when the VM request authentication later on. That was not clear, I agree. I will update the documentation.

I didn't knew about "**;EnhancedMode=1;**", it's undocumented by FreeRDP. It's nice, because it should give access to the remote clipboard and the myrtille pdf printer, among other things. Thanks again! :)

I made some researches and found that it may work only for Windows 10 (and probably 2016 server): https://www.tenforums.com/tutorials/57136-turn-off-hyper-v-enhanced-session-mode-windows-10-a.html

For other Windows versions, it can be enabled directly into the Hyper-V settings: http://www.systemcentercentral.com/what-is-enhanced-session-mode-in-windows-server-2012-r2-hyper-v-and-when-should-i-use-it/

**Comment by cedrozor** [comment]
I ram some tests and "**;EnhancedMode=1;**" works great :) not only it's faster but clipboard, printer, etc. are available.

I will see to add it automatically in the next version. In between, as @jol64 said, you can just add it after the VM guid (example: `13FE501B-C517-437D-AAC6-ABE48CE5B780;EnhancedMode=1;`)

**Comment by jol64** [comment]
Automatic? Unfortunately Enhanced Session Mode is not always available. Depends on OS and state of OS. E.g. for Linux guests it is not available. For Windows guests it is unavailable during system startup and shutdown. Thus automatic only makes probably only sense if you can
1)	identify availability up front, and afaik that requires Win-RM and thus Hyper-V-Administrator membership (as VMConnect does), or
2)	if it can be negotiated at FreeRDP connection time (no idea whether that is possible)

Otherwise I´d prefer a plain checkbox for now.

**Comment by cedrozor** [comment]
I expect it to be simpler than that :) if FreeRDP and Hyper-V are well designed, they should fallback to normal (not enhanced) mode if the feature isn't supported by the guest VM, or not yet available.

Otherwise, yes a checkbox would be the simplest option; but I'd prefer the fallback because I think the login screen already has enough things already.

About Linux VMs, does the Hyper-V connection works good? did you install an xrdp server to check with a standard RDP connection?

**Comment by jol64** [comment]
unfortunately I experienced connectivity issues when always adding request for enhanced session mode, but I’d be happy to learn it was my fault...

With linux vms I usually use RDP only until I get a static ip configured and ssh installed. None of them provides a graphical desktop.

**Comment by cedrozor** [comment]
I'll make some tests to check that.

Perhaps I should add another host type selection into the myrtille login screen; there are actually RDP and SSH, I could add a "RDP over VM Bus" so that the VM guid and the enhanced mode checkbox would be hidden by default for a standard RDP connection.

Beside the VM guid and `;EnhancedMode=1`, do you know if there are more options to pass to the FreeRDP "/vmconnect:" param?

If anyone is interested, there are more info on that RDP over VM Bus feature:

- http://culmor.blogspot.com/2013/10/vmconnect-enhanced-mode-rdp-over-vmbus.html
- https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/learn-more/Use-local-resources-on-Hyper-V-virtual-machine-with-VMConnect.md

**Comment by jol64** [comment]
>  I could add a "RDP over VM Bus" so...

I like that idea because it also makes obvious that different default ports are used.
> do you know if there are more options to...

sorry, but no.

**Comment by cedrozor** [comment]
done into version 2.1.1

**Comment by jol64** [comment]
thanks once more for the new version. I am kind of surprised that the internal code for "RDP" and "RDP over VM bus (Hyper-V)" are the same, both option 0. If you ever want to support prefilling some but not all information via URL, or after an unsuccessfull connection present the information in the form for change, then it is probably a good idea to have a different option code now.

**Comment by cedrozor** [comment]
updated the documentation :)
