### ISSUE TITLE
Feature Request: expose PasswordHash via http

### ISSUE THREAD

**Issue by jol64** [cedrozor/myrtille#129]
I am integrating Myrtille with my own application and implementing navigation from my service to Myrtille, filling in all required arguments in the URL. Now when Myrtille and my application are installed on different systems, I cannot use PasswordHash as I can on a local machine. 

Can you please expose PasswordHash as a kind of REST-Service via http? Then I can call that service from my backend, passing in the password I want to be hashed (encrypted) and pass that instead of the real password on the URL.

Thanks, Joachim

**Comment by jol64** [comment]
my suggestion is to have a URL @ myrtille that accepts a password and returns the passwordhash. The URL would be called by my application, then passing passwordhash (instead of password) to the frontend. Anyone obviously could call the URL but without knowing the correct password the gain is nothing. And of course all connections are encrypted via https.
(Actually the password is known to the frontend user anyway, but while  opening the browser with the url it is shown and thus potentially visible temporarily to someone looking at the screen).

Replacing LocalMachine is unfortunately no solution I like. In fact I was running my application under an alternative user but that prevented Windows updates to function properly - don´t want to experiment with that again. Also it would require a domain infrastructure and significant configuration.

I am also considering remote powershell execution, but again it requires (trust) configuration. Exposing the hash directly is imho the easiest approach.

**Comment by cedrozor** [comment]
You want to get the hash from a service... ok, but the machine that generates it will also have to decrypt it and send the plain text password to the frontend; How do you secure this?

**Comment by jol64** [comment]
tried to sketch this using draw.io  (with limitations). frontend and backend are part of my application, frontend can also be a browser (and then request in an invisible iframe).
![image](https://user-images.githubusercontent.com/24666601/45634275-3adf9680-baa2-11e8-838b-80fef0673fb5.png)
as you can see encryption and decryption will be both Myrtille. And all communication is https-encrypted.
Actually it only addresses the issue of showing the password in the URL. It does not change the fact that anybody seeing the URL with the hash / encrypted password can authenticate against that Myrtille instance. For virtual machines I consider this non-critical as the virtual machine requires an additional authentication, for RDP hosts this can be critical however.

**Comment by cedrozor** [comment]
Thanks for the flow diagram. In fact, you just need a service (SOAP, REST or whatever) to return the hash of a given password.

I can see to do that (should be quite easy) but I don't have much time these days :/ if you know how to expose a service through WCF, you could do it faster than I can find some free time.

Indeed, the hashed password doesn't prevent a third party to authenticate against myrtille. It simply avoids the plain text password to be known (and thus connect the server directly, without using myrtille). If you want a one time password, you can try the enterprise mode which generates a unique url for a given server and user.

**Comment by jol64** [comment]
what about https://github.com/cedrozor/myrtille/compare/master...jol64:master ?

**Comment by cedrozor** [comment]
Hey, sorry was busy for some time.

Yes, looks good, but you could had use the existing helper method (https://github.com/cedrozor/myrtille/blob/master/Myrtille.Common/Helpers/RDPCryptoHelper.cs#L53). Also, it could be a REST service, or an http handler, instead of a page but the goal is reached.

Could you make a pull request please? thanks :)

**Comment by cedrozor** [comment]
The difference between a REST service and a page is that it's more lighter for the rersources server side because there is no need to instanciate all the pipeline required by a page life cycle. But that said, REST services relies on the WCF layer, which is not super light either.

It's mostly cleaner because it makes use of the native HTTP methods (post, put, get, etc.) for CRUD operations. 

But I agree, a simple page is good enough just to get something.

There are also the http handlers, which are like pages but without UI rendering and thus lighter too for the server resources (SendInputs.aspx, called from an xmlhttp request, could had been a http handler). For example, I use an http handler for websockets, because the initial handshaking is done through an http request.
