### ISSUE TITLE
Any eta for support for the newest version of freerdp?

### ISSUE THREAD

**Issue by tmakaro** [cedrozor/myrtille#13]
Hi Cedric, you mentioned that you were working on implementing the newest version of freerdp. I was curious how that was going?

**Comment by cedrozor** [comment]
Hi Troy, yes I'm working on it the main problem being the low free time I have (like 1h/day).

I also had some technical challenges, with cmake, mixing up C/C++ code (myrtille uses C++ while freerdp is pure C), refactoring the myrtille code, playing with newest freerdp params and implementing the clipboard support.

The good news is it works, and well. The latest version fixes then NLA and mouse pointer issues. There is now clipboard and Hyper-V connection support. Performance may also be a bit improved as well, as freerdp now uses hardware gdi.

I'm currently testing and trying to fix some clipboard issues when multiple sessions are actives. Also, myrtille will support only unicode text clipboard format because OLE objects aren't supported by the browser.

ETA is 4 september, at best (I won't be at home this week-end so won't be able to progress).

I plan to do 2 more things in september: home page relooking (currently very basic) and IIS 7.5+ native websocket support (replacing Fleck).

**Comment by cedrozor** [comment]
There will be also an architectural change. I will make a freerdp fork as soon as I'm done with tests. This fork (another repository) will contain and tag the myrtille code (like it's done actually) and will be periodically synchronized with the freerdp main repository (stable branch).

The objective is to have myrtille always use the latest version of freerdp and thus benefit bug fixes and improvements.

But the main idea is to have myrtille loose coupled with freerdp, and the rdp protocol alltogether, in order to be able to be branched with other(s) project(s)/protocol(s) (ie: vnc). That is, myrtille will be a generic remote desktop gateway.

It will be transparent for the end user, I will have the installer manages that.

**Comment by cedrozor** [comment]
I committed the discussed changes. First, the rdp client (freerdp) is now decoupled from myrtille and is accessible there: [https://github.com/cedrozor/FreeRDP](https://github.com/cedrozor/FreeRDP). Second, I reworked the homepage to make it more sexy.

Just remains to update the installer, documentation and wiki.

I will release a new version this week (but the code is already functionnal is someone want to check it).

**Comment by tmakaro** [comment]
Cool. I can hardly wait to play with it :)

**Comment by tmakaro** [comment]
So I am a bit confused :) What is the relationship between cedrozer/myrtille/Myrtille.RDP... and cedrozer/FreeRDP?

The only thing I can see that you changed in Myrtille.RDP is wf_win.cpp which doesn't exist in FreeRDP?
Is any of the Myrtille.RDP still used?

I haven't built cedrozer/FreeRDP yet. I need to learn cmake I guess. I am really weak on c and c++

**Comment by cedrozor** [comment]
cedrozor/Myrtille (this repo) is the (http to rdp) gateway while cedrozor/FreeRDP is the rdp client (used by the gateway). It loose couples the 2, allowing tomorrow to have myrtille using telnet, SSH, VNC or whatever remote access protocol.

Before I have time to update the installer (and release a new version), I indeed left the old freerdp version (embedded with myrtille); it will be removed soon, when the decoupling is effective.

To build cedrozor/FreeRDP, you have to call cmake following this procedure: [https://github.com/FreeRDP/FreeRDP/wiki/Build-on-Windows-Visual-C---2012-%2832-and-64-bit%29](https://github.com/FreeRDP/FreeRDP/wiki/Build-on-Windows-Visual-C---2012-%2832-and-64-bit%29).

Once built, you have to copy the new freerdp executable and dlls into the myrtille bin folder, then comment and replace the old freerdp call by the new one (into Myrtille.Services/RemoteSessionProcess.cs.) But if you can wait a few days, I suggest you to wait the next release ;)

I will update the myrtille documentation and wiki according to it.

**Comment by cedrozor** [comment]
Myrtille 1.1.0 is now available. This is a pre-release (beta).
