### ISSUE TITLE
Can Myrtille issue a status on whether the remote desktop is successfully connected yet?

### ISSUE THREAD

**Issue by Sydrik** [cedrozor/myrtille#131]
Can Myrtille issue a status on whether the remote desktop is successfully connected yet? In my case, I use a dashboard built with PHP, in which I hope to receive from Myrtille a signal/instruction when the desktop is connected and ready. Thanks.

**Comment by cedrozor** [comment]
Yes, it's a state change from RemoteSessionState.Connecting to RemoteSessionState.Connected as soon as Myrtille receives a display update from the remote server.

You could trigger a notification at that point (https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/src/RemoteSessionManager.cs#L154) or poll the remote session state otherwise.

**Comment by cedrozor** [comment]
Does it fulfills your needs?

**Comment by cedrozor** [comment]
Ok, tell me if you need something else.
