### ISSUE TITLE
 connect WINDOWS SERVER 2003 Chinese version 

### ISSUE THREAD

**Issue by mmOTAN** [cedrozor/myrtille#140]
Use Myrtille to connect WINDOWS SERVER 2003 Chinese version (old enough, but still to use:( ) when there are refresh exceptions and some Chinese characters are not displayed, as shown in the figure:
![image](https://user-images.githubusercontent.com/23157770/50673580-c9f4c800-1019-11e9-87ab-8a64f753e6f7.png)

**Comment by mmOTAN** [comment]
I tried using "wfreerdp /u:user /p:password /v:server" two days ago and the display is normal. The problem should indeed be here. There are no test conditions now, I will try rebuild later.
Thank you for your reply.

**Comment by mmOTAN** [comment]
After I modified it to -glyph-cache and rebuild it, the display is normal. This phenomenon actually only appears in the Chinese version of windows server 2003, other versions of windows have not been found.
I am doing some tests on the operation of myrtille in the Chinese environment. I have found some problems, I will send it up, I hope to get your guidance.
Thank you again for developing such a good project and helping me!

**Comment by cedrozor** [comment]
Thanks for reporting this issue.

I will try to check what happen into FreeRDP and eventually report the issue or make a pull request to the FreeDPP team.

I will keep `glyph-cache` enabled by default because it's a performance flag, but I will make it (and more FreeRDP options) configurable into myrtille, then update the documentation (troubleshoot section).
