### ISSUE TITLE
max sessions limited under Myrtille ? or IIS ?

### ISSUE THREAD

**Issue by SeRom7640** [cedrozor/myrtille#141]
Dear,
First of all thanks for this wonderfull product.

I make an event booking portal with registration and online payment for an association.
For this, my software works only on Windows and is placed in DB/C (dbcsoftware.com).
To allow most people to book in, I decided to do a "kiosk" using a Windows 10 Pro PC, CONFIGURED with RDP Wrapper (also on GitHub) and blueberry. This will allow all the OS and all the hardware to connect via HTML5.
The kiosk starts working well and I get what I want, except that the maximum number of sessions I am able to open under Myrtille is 10.  You cannot open a new session under Myrtille, but you can open new sessions using the classic Microsoft RDP client.  So the limitation does not come from RDP wrapper.
Where can I change this limit (Myrtille? IIS? WebSocket?)
Thank you for your help

**Comment by cedrozor** [comment]
There is no such a limitation into Myrtille.

Maybe it doesn't come from RDP Wrapper, but from the host itself. RDP Wrapper states that it supports 

> Up to 15 concurrent sessions (the actual limitation depends on your hardware and OS version)

https://github.com/stascorp/rdpwrap#key-features

What happen when you try to open a 11th session? when you have 10 concurrent sessions with Myrtille, can you connect using mstsc?

It will be better to host your application on a Windows Server 2016, with the RDS role enabled (and a connection broker with multiple hosts in a load balancing scenario, if you have many connections). The number of concurrent connections will only be limited by the number of CALs provided by your license server (https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-client-access-license).

**Comment by cedrozor** [comment]
By the way, how do you proceed to have 10 concurrent sessions with myrtille? did you enabled cookieless sessions (for multiple tabs/sessions), as explained into the [readme](https://github.com/cedrozor/myrtille#resources)? or do you test from 10 different clients?

**Comment by SeRom7640** [comment]
Thanks for yours answers.

I can have more than 15 sessions, up to 20 (because my software has a licence limitation to 20 but I can continue to open more and more RDP session using mstsc.exe until lack of memory.
I use Myrtille with this URL (in my local LAN, not yet through the internet) : 
http://10.0.0.126/Myrtille/?__EVENTTARGET=&__EVENTARGUMENT=&server=10.0.0.126&user=brocante&passwordHash=01000000D08C9DDF0115D1118C7A00C04FC297EB010000003258DDC0A180B448882F92421CA95D0204000000020000000000106600000001000020000000EC01A9A9DD094184CB8406D3F16C80339B6D9482CD9F1B83AFA7D3F605D50EFE000000000E8000000002000020000000B47EFABC24D9B93608103002D9F6C7AA34F0217D772B8B3A9ACB39D739F58EC2200000003D041AED537E6985B430E69670DC6E87B685CBFA0680EF40F1BA1E750BD337CC4000000094994F382C90FBD7D4A50B3D84398C43587CF686203F91672B45EA3769A4FE8BC6A3CD4A46E2AB45854038C47535E3DF9BAF0CD4FE2BF8540E368E2F098E846C&width=900&height=900&connect=Connect%21
I also have enabled auto-scaling in Myrtille.
with that autologin, the session open and runs my program because I put it in the LOCALUSER Shell parameter instead of the default Windows explorer.  In fact, this shell program launch a cmd file which launch : sumatra PDF with a help file, My EventBooking software and a freeVK (an alternate free Virtuel Keyboard).

With Myrtille, when I open my 11th session, the browser is waiting till a time-out and go back to the Myrtille logon screen.  At this time I can continue to open RDP session with the same user "brocante" using mstsc.exe until the max 20 allowed session of my EventBookin software. At the 21rst session (opend with mstsc.exe), it continue to open session with the sumatra PDF reader and the virtual keybord, but not my software which displays a licence lack error.

Our association has no budget to buy Windows serveur 2016 and RDP CAL.

I just try to uses Cookieless option without change (max 10 sessions in Myrtille).

Thanks for the time you spend reading me

**Comment by cedrozor** [comment]
Thanks for the details.

When the 11th session is opened with myrtille, do you see something or have any dialog message before the redirect to the logon screen?

Could you enable the wfreerdp logs (bin\Myrtille.Services.exe.config, https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/app.config#L190), the restart Myrtille.Services (Windows Service), then check the `wfreerdp.xxx.log` into the log folder for any useful information.

Also check the wfreerdp exit code into `Myrtille.Services.log`.

**Comment by SeRom7640** [comment]
nothing on the screen before the logon screen, nor the menu button at the upper left corner.

I just activate the logs.
For the freerdp.*.log, only 10 file are created, nothing for the 11th session
with the log activated, it seems there is no timeout to return to the logon screen.  It is about ten minutes I wait for the logon screen but nothing the browser tab wait for something... or not...

If I close one of the 10 first session, the 11th begins. If I want to start a 12th, it wait for the end of a previous one.  I don't know if you can see that in the log.
at 2019-01-06 16:47, the 10th session started
at 16:58 I killed the 10th, so the 11th may start
Reporting of the end of the 10th session is marked at 16:59
here are the log

[wfreerdp.9152.log](https://github.com/cedrozor/myrtille/files/2730619/wfreerdp.9152.log)
[wfreerdp.15752.log](https://github.com/cedrozor/myrtille/files/2730620/wfreerdp.15752.log)
[wfreerdp.6932.log](https://github.com/cedrozor/myrtille/files/2730621/wfreerdp.6932.log)
[wfreerdp.11564.log](https://github.com/cedrozor/myrtille/files/2730622/wfreerdp.11564.log)
[wfreerdp.14884.log](https://github.com/cedrozor/myrtille/files/2730623/wfreerdp.14884.log)
[wfreerdp.3600.log](https://github.com/cedrozor/myrtille/files/2730624/wfreerdp.3600.log)
[wfreerdp.10164.log](https://github.com/cedrozor/myrtille/files/2730625/wfreerdp.10164.log)
[wfreerdp.6576.log](https://github.com/cedrozor/myrtille/files/2730626/wfreerdp.6576.log)
[wfreerdp.12260.log](https://github.com/cedrozor/myrtille/files/2730627/wfreerdp.12260.log)
[wfreerdp.7220.log](https://github.com/cedrozor/myrtille/files/2730628/wfreerdp.7220.log)
[wfreerdp.11732.log](https://github.com/cedrozor/myrtille/files/2730629/wfreerdp.11732.log)
[Myrtille.Services.log](https://github.com/cedrozor/myrtille/files/2730615/Myrtille.Services.log)

**Comment by cedrozor** [comment]
When you connect with mstsc, are you doing it from the machine where myrtille is installed?

**Comment by SeRom7640** [comment]
No I connect from another desktop and a laptop, both in windows 10 and for the moment, in the same LAN, not yet from internet

**Comment by cedrozor** [comment]
To reproduce the same conditions as for Myrtille, could you try to connect with mstsc from the Win 10 Pro machine itself (with "localhost" as target)?

I suspect some changes, made by RDP Wrapper, on the Win 10 Pro machine that have effects on wfreerdp (as rdp client) and _might_ (should?) have on mstsc.

That is, MS have 2 RDS licences type (and checks):
- per user (default)
- per device

If you connect from the Win 10 Pro machine and the licence type is "per device", it _might_ behave differently than another devices (desktop and laptop) because of that local changes.

Also, it's possible to have:
- only one connection per user (default)
- multiple connections per user

As you are connecting always with the same user, it's obviously the 2nd option which is configured.

**Comment by cedrozor** [comment]
There is another test you could do, perhaps easier. 

Copy the wfreerdp binaries (into the myrtille bin folder), or the whole bin folder if you want, on your laptop or desktop. Then run from a console command:
`wfreerdp /u:user [/d:domain] /p:password /v:server` (domain is optional, if you don't have one)

See if you can open more than 10 sessions. Try it also on the Win 10 pro machine.

**Comment by SeRom7640** [comment]
thanks for your suggestions.
Licences per user or per device are for servers versions of Windows.  There is no such distinction under Windows 10.
For RDP Wrapper, it just take de RDS part of Windows 10 Pro and It makes Windows believe that only one RDP session is running.

look below at the RdpWrapper config Screen, You can see I have unchecked the Single session per user, so I may open many session with the same user.
![image](https://user-images.githubusercontent.com/39957946/50833310-0c3b4380-1351-11e9-9eba-4b9b573242d3.png)
Ihave tried your first suggestion : trying mstsc on the console screen of my "RDP WRapper/Myrtille/Win10Pro" machine.  If I use localhost or 127.0.0.1 as hostname, it fails to start with message that another session is already running.  But I found on RDP Wrapper documentation that when testing the good-working of rdp-wrapper we must use an alternate localhost like 127.0.0.2, 127.0.0.3...
At this moment I can open more and more session.

I triad also your other post on my destop using **wfreerdp /u:brocante /p:password /v:10.0.0.126** where I replace password by my brocante password and... it works with at least 10 or more sessions
So at this moment my myrtille machine has more than 25 open sessions (10 with myrtille from my desktop, 10 with Wfreerdp on my destop and other one opened with mstsc on the myrtille machine with host 127.0.0.2 or 127.0.0.3
![image](https://user-images.githubusercontent.com/39957946/50834552-98029f00-1354-11e9-93b1-e878bc8c51d5.png)


With alla theses session opend, I tried also the commandline on de Myrtille machine even with 10.0.0.126, 127.0.0.1, 127.0.0.2 and 127.0.0.3 and all the sessions are working.
![image](https://user-images.githubusercontent.com/39957946/50834534-89b48300-1354-11e9-960d-741923b67e57.png)


I suppose the problem comes from the alternate host imposed by RDPWrapper

**Comment by cedrozor** [comment]
Myrtille does call wfreerdp with the same parameters as you entered into the command line (with some more, to disable wallpaper, set 16 bits per pixel, etc.), so the problem doesn't come from the alternate host imposed by RDP Wrapper. If you enter "10.0.0.126" as server address into the myrtille URL or logon screen, it's equivalent to the `/v:10.0.0.126` param.

I wonder where this 10 sessions limitation comes from (not from myrtille anyway). You are not using the enterprise mode of myrtille, isn't it? (you don't define a domain into the myrtille url).

Could you check if you have something useful into the win 10 pro machine application or system event logs? and, more specifically, into the Terminal Services event logs. See:

- https://answers.microsoft.com/en-us/windows/forum/windows_7-security/terminal-services-logs-in-event-viewer/b380c16a-10e0-4df7-bb22-ddb77d9b4a70
- http://purerds.org/remote-desktop-security/auditing-remote-desktop-services-logon-failures-1/

Could you also disable, just for test purpose, the configuration you made to run a custom program on session start ("LOCALUSER Shell parameter instead of the default Windows explorer") and see if that changes something.

For information, Myrtille has an equivalent feature with the `&program=` param into url, to provide an alternate shell on session start, but you were right to have that into registry (or whatever config tool you used) because that feature doesn't work actually on non server versions of Windows (7, 8, 10). The only thing that may work is to use the remoteapp feature with wfreerdp, but it's a little bugged right now and that's subject to another issue (https://github.com/cedrozor/myrtille/issues/137).

**Comment by SeRom7640** [comment]
In fact, I don't use domain in my LAN.
I have delete the shell parameter in the LOCALUSER for the user Brocante, so now, opening a session results in opening a full feature RDP session with start button and explorer loaded.  I also tried, for testing only, to give administrators rights to the "brocante" user.  But max number af session using the myrtille URL is 10.
When consulting event logs under my Win10ProRDPWrapMyrtille machine I don't find any trace of the 11th session.  I find only session which succeed to logon.

Don't you think the problem can come from IIS for Windows 10.  I'am not expert in IIS but it seems to be the last possibility. 

![image](https://user-images.githubusercontent.com/39957946/50898544-c85b4380-140f-11e9-8a7d-b369f88ceccf.png)

About the &program= I saw that in the documentation, but in fact, I was not able to use it under Win10.

**Comment by cedrozor** [comment]
Bonjour! (saw on the screenshot you are french, as I am :p)

I made some research about IIS on Windows 10 Pro and, you were right, that's the issue: https://forums.asp.net/t/2100558.aspx?concurrent+connections+on+windows+pro+10+IIS

> MS has put a limitation on the IIS application pool to max out at 10 concurrent connections when running on a windows 10 pro box. This limitation does not exist on windows server IIS proper.  I know this limitation to be true because before I was using IIS on windows home edition and saw that I was only able to open three tabs (3 concurrent connections) at a time with the application.
> 
> My issue is the windows 10 pro end user license agreement clearly states that 20 connections can be available to IIS. Yet, it is being crippled at 10 and not 20.

I didn't knew that because I always use Windows Server editions for my load tests. I will update the Myrtille documentation.

More info about the different versions of Windows/IIS and their limitations: http://www.jpelectron.com/sample/WWW%20and%20HTML/IIS-%20OS%20Version%20Limits.htm

There are some workarounds (but be warned, they may not be legal): https://stackoverflow.com/questions/38056200/unlimit-the-maximum-concurrent-connection-on-windows-10

Another option is to run Myrtille in IIS Express (it seems that it doesn't limit the number of connections): https://stackoverflow.com/questions/38802347/self-host-signalr-in-windows-10 (Myrtille doesn't use SignalR, but the same logic applies). You will have to use a custom port (other than 80) and have a port redirect (from the external port 80 to that internal port of your win 10 pro machine) on your NAT if you plan later to have it accessible from internet.

**Comment by Terricide** [comment]
Maybe something like the Cassini web server could be used?

https://github.com/zippy1981/Cassini

**Comment by SeRom7640** [comment]
Belgian and French speaking in fact, at the French border close to "Les Haut De France" :)

Do you think I have to uninstall IIS before installing IIS Express ?

Cassini seems to be an old product, no ?

**Comment by Terricide** [comment]
Yeah it is old but I've used it in the past to host an asp.net app

**Comment by cedrozor** [comment]
I don't know either for Cassini. Myrtille uses .NET 4.5 (websockets requirement), and Cassini seems for .NET 3.5, so it remains to be tested.

IIS Express can run along with IIS, on a different port. It's already installed if you have Visual Studio on the machine. Otherwise, you can download it there: https://www.microsoft.com/en-us/download/details.aspx?id=48264. I tested it previously with websockets and all, no problem.

**Comment by SeRom7640** [comment]
I must be stupid or tired.
I have just installed IIS Express but I don't find it on the machine... No new icon anywhere, Any idea ?

**Comment by cedrozor** [comment]
IIS Express is a lightweight version of IIS and doesn't come with a GUI (https://stackoverflow.com/questions/4690358/iisexpress-user-interface).

However, there seems to be a good one there: https://docs.jexusmanager.com/

**Comment by SeRom7640** [comment]
OK, now I installed IIS and Myrtille on my Win2012 server (the one which hosts my DB/C Dispatcher and my booking database.  The RDPWrapper stays on my Win10Pro Machine.  So IIS and Myrtille will give HTML RDP Session to my Remote Desktop Server which has a restricted access to my booking database only trough a few TCP port and the "DB/C Smart Client".
Can I now simply copy-paste the Myrtille folder from my Win10Pro machine to my Win2012Server ?

**Comment by cedrozor** [comment]
Did you tried the Jexus manager for IIS Express? it looks nice and comparable to the IIS manager. You just had to create a web application under the root website and make it point to the myrtille install folder.

Sure, by installing myrtille on a Windows Server 2012, you don't have the IIS limitation. But you should use the myrtille installer or otherwise create a dedicated application pool, a self hosted SSL certificate (for intranet usage), a web application, a windows service (myrtille self hosted WCF services, into Myrtille.Services) and tweak the config files to your needs.

**Comment by cedrozor** [comment]
> IIS Expresse didn't want to lauch on my Win10Pro and no more time to spend about that. So It seems there are more performance under Win2012 even with a less powerfull machine. My Win10Pro is a Core i5 2th generation, My Win2012 is a Intel E2160 with 5 GB RAM.
> So I decide to let Myrtille on the server 2012.

 Windows Server editions are more optimized than the home editions (even a "pro" version).

> when using URL with the &password= parameter, I can log in to my RDPWrap Machine but
> when using &passwordHash=, it fails with "invalid credentials" message.
> I tried to create a new Hash without success. I tried to do that even from my desktop, my Win10pro or my win2012 machine, always using the win2012 installation of Myrtille. An Idea ?

The hashes generated on the win pro 10 machine won't work on the server 2012. You have to re-generate them from the powershell console on the server 2012 machine (or from url http://10.0.0.125/myrtille/GetHash.aspx?password=your_password).

> the second problem is that I use the autoscale feature using informations from issue #72. It worked fine under my first Win10Pro/Myrtille installation, but under Win2012 my initial size "&width=900&height=900" is the only zone of the browser that is visible, the rest of the windows is grey but the displayed result of the running apps is correctly scaled like this

If you want the display to be autoscaled to the browser size, simply don't add `&width=900&height=900` into the url. The trick spoken into https://github.com/cedrozor/myrtille/issues/72 is about forcing a resolution (1024x768) then stretch the display to that resolution, whatever the browser size.

**Comment by SeRom7640** [comment]
for the password i found the error : I use the user name instead of the password itself.  It is time to go to week-end, I think.

Under my Win10PRo, I forced 900x900 in th url to fit with my application and force autoscaling with the browser size and it worked fine.  It was a way I found to allow using my App on a android tablet in portrait mode and to take all the screen.  How can I do that now ?

**Comment by cedrozor** [comment]
On the win10pro, did you modified network.js, as explained into https://github.com/cedrozor/myrtille/issues/72, to have autoscale enabled by default? did you modfied it on the winserver2012? if you didn't, there is no reason it behaves differently.

**Comment by SeRom7640** [comment]
Yes I modified network.js as discribed in #72, and I copy-paste network.js from the win10 to win2012 machine. her is my code : 
![image](https://user-images.githubusercontent.com/39957946/51038408-6e937e80-15b3-11e9-9d83-bc086b97ad29.png)

**Comment by cedrozor** [comment]
Ok it's probably a browser cache issue then, if both machines have the same .js code. Can you clear it and refresh the page?

Also, think to remove myrtille from the win10 machine, to avoid further confusion :p

**Comment by SeRom7640** [comment]
After clearing the cache : 
it works on my Android v9 phone under Firefox but not under chrome
idem for my Android v7 Tablet
but no success with my laptop nor my desktop under firefox, chrome and IE
what's wrong ?

**Comment by SeRom7640** [comment]
I also tried to start the single explorer instead of my personnal shell program : no success !

**Comment by SeRom7640** [comment]
I just power on my Ubuntu laptop which was never used with Myrtille and same result under Firefox with this URL : 
http://10.0.0.125/Myrtille/?__EVENTTARGET=&__EVENTARGUMENT=&server=10.0.0.126&user=brocante&passwordHash=01000000D08C9DDF0115D1118C7A00C04FC297EB01000000C3305894455BF144BB2DAD97DF56A1630400000002000000000003660000C000000010000000A6FB221151B3E34BC755E84EBC3135AF0000000004800000A0000000100000001D296653D6B668B7BD64C0C49C799ABE200000004C1CBB08880084EECF3A114C568007DDC9165DE60DEEEE6C9605E6576895BFE1140000003082652EA9F9C389657B4DB9AC15BF46779DDD68&width=900&height=900&connect=Connect%21

the browser display a 900x900 square where my apps are viewable but the rest of the browser windows has the same grey as the "manual" logon screen.  And the apps are scaled (but not always, in some case, they keep their real size in the 900x900 square)

**Comment by cedrozor** [comment]
When you say it doesn't work, do you mean the autoscale? what happens if you click on the autoscale button into the toolbar?

Did you enabled the websocket protocol on IIS ? it may be enabled by default on IIS 10 (win10) but not on IIS 8 (win2012). Follow https://docs.microsoft.com/en-us/iis/configuration/system.webServer/webSocket

Multiple commands can be an issue in Ajax mode due to the limitation of concurrent xhrs.

> I also tried to start the single explorer instead of my personnal shell program : no success !

You are still connecting the win10 machine, with your application on it, from myrtille? if so, you have to set the LOCALUSER shell parameter instead of the default Windows explorer (as you did before) because the "&program=" param won't work (your application is not hosted on the win2012 machine)

**Comment by cedrozor** [comment]
Hmm forget my last comment, you don't use the "&program" param anyway (our replies just crossed).

I think you meant you tried to start the default explorer, instead of your application, and the autoscale also failed, right? so have a look to enable the websocket protocol on the win 2012 machine, that's the main difference with IIS 10 in my opinion

**Comment by SeRom7640** [comment]
Yes just autoscale doesn't work nice.
the scale button was hidden by me in the CSS, I restored it just now.  When  clicking it work.  Disfunction seems to be just at the beginning of the session.
I verify for Websocket because, in fact I didn't activate it

**Comment by SeRom7640** [comment]
yes, just the Shell parameter for LOCALUSER.

**Comment by SeRom7640** [comment]
Yes, After installing Websocket and rebooting the server, Autoscale feature works fine again.
I tried, Androïd, Ubuntu and Windows with Firefox, Chrome and IE, but after a cache clear for Chrome.
Big Big Thanks to you !!

I have some other questions but perhaps is it better to open other issues, tell me... : 
questions are : 
1) is it possible to AutoSwipe at startup like the Autoscale ? because, under Android, the menu button is not easy to activate.
2) I know it is possible to add an autorenew "Let's Encrypt" certificate under IIS, but is there no risk to perturb Myrtille ?

**Comment by cedrozor** [comment]
> Big Big Thanks to you !!

You are welcome :)

> I have some other questions but perhaps is it better to open other issues, tell me...

Yes, better to track issues afterward.

> is it possible to AutoSwipe at startup like the Autoscale ? because, under Android, the menu button is not easy to activate.

Indeed, I tried to have a small button for the toolbar but on small devices I agree it's not easy to trigger.
Swipe is enabled by default (https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/js/user.js#L48). But it's quite experimental right now; I have improved it, I just have to find some time to release a new version.

> I know it is possible to add an autorenew "Let's Encrypt" certificate under IIS, but is there no risk to perturb Myrtille ?

Not at all, it's related to IIS. The SSL handshaking is established on page load and websocket connection; even if it's renewed while a remote session is active, you will have to refresh (F5) the page for the changes to take effect and that will be seamless. That said, I didn't tested such a scenario :p
