### ISSUE TITLE
Autoscaling problem (annex to #72)

### ISSUE THREAD

**Issue by SeRom7640** [cedrozor/myrtille#142]
Hi Cedrozor,
I come back to you about autoscaling at begining of the session because I meet some strange behaviours I can't explain.  As said in #141, Websocket are now correctly installed but it happens that sessions do not start autoscaling when starting.  My quesion is : have I correctly put the autoscaling code in the network.js ?
![image](https://user-images.githubusercontent.com/39957946/51087273-7e48c980-1751-11e9-83c3-1a0174e2db57.png)
In fact my URL command line has size parameters defined to **&width=900&height=900**
900x900 is the place taken by the software running under the rdp session, so autoscaling will allow the visitor to view the rdp session in full screen mode on a tablet or smartphone.
But quite often, the session start with no scaling enabled whatever the device or the browser used.  I have to clic once on the scale button in the menu bar to activate scaling.
Easy to do on a PC, Mc or Ubuntu machine with mouse, but not on touch device.
Is it possible to defined the user size (**&width=900&height=900**) at the early beginning of the connection because I think there is sometimes a problem with the IF statement on line 339 (**_if (!config.getScaleDisplay())_**), perhaps at the wrong place ?/51087273-7e48c980-1751-11e9-83c3-1a0174e2db57.png)
In fact my URL command line has size parameters defined to **&width=900&height=900**
900x900 is the place taken by the software running under the rdp session, so autoscaling will allow the visitor to view the rdp session in full screen mode on a tablet or smartphone.
But quite often, the session start with no scaling enabled whatever the device or the browser used.  I have to clic once on the scale button in the menu bar to activate scaling.
Easy to do on a PC, Mc or Ubuntu machine with mouse, but not on touch device.
Is it possible to defined the user size (**&width=900&height=900**) at the early beginning of the connection because I think there is sometimes a problem with the IF statement on line 339 (**_if (!config.getScaleDisplay())_**), perhaps at the wrong place ?

_Originally posted by @SeRom7640 in https://github.com/cedrozor/myrtille/issues/72#issuecomment-453841008_

**Comment by cedrozor** [comment]
Hi, I was just about to reply into the #72 , but better have a new issue indeed.

I checked and there can be a race condition (into the initialization stage) that prevent the scale command to be sent correctly to the remote session.

I fixed it and it will be into the next release for those who want autoscale on session start. I will even make it configurable so that it won't be necessary to modify any .js file.

Meanwhile, you can remove the code you added into `network.js` and insert the following code into `websocket.js`, after the line [390](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/js/network/websocket.js#L390):

```
// enable scale display
if (idx == 1)
{
	var width = display.getBrowserWidth() - display.getHorizontalOffset();
	var height = display.getBrowserHeight() - display.getVerticalOffset();
	network.send(network.getCommandEnum().SET_SCALE_DISPLAY.text + width + 'x' + height);
}
```

**Comment by SeRom7640** [comment]
I don't have autoscale at all anymore without pressing the scale button, the value of idx perhaps ?
![image](https://user-images.githubusercontent.com/39957946/51117051-f45e3680-180c-11e9-9728-d5806863eece.png)

**Comment by cedrozor** [comment]
No, I think it's a browser cache issue. Try to clear the cache and refresh (F5)

**Comment by SeRom7640** [comment]
already done, no more autoscaling anywhere (pc, android, linux)

**Comment by cedrozor** [comment]
Nice design :)

Thanks for the link, I checked the issue and indeed the first image idx is 2 (whereas it should be 1). For information, images indexes are auto-incremented into myrtille (starting with 1), and are displayed in sequence.

It's again a race condition. The websocket is probably not opened (client side) when the first image (idx == 1) is available (server side), so it can't be sent and is dropped. The next image (idx == 2) is sent successfully however.  It happened because everything is faster on a LAN and I didn't tested on internet.

So, we can have it differently (just like we did previously in fact). At line 390 of `websocket.js`:

```
// if not already enabled, enable scale display
if (!config.getScaleDisplay())
{
	var width = display.getBrowserWidth() - display.getHorizontalOffset();
	var height = display.getBrowserHeight() - display.getVerticalOffset();
	network.send(network.getCommandEnum().SET_SCALE_DISPLAY.text + width + 'x' + height);
}
```

Please keep in my mind it's only a quick & dirty hack waiting for the next release! :p

**Comment by SeRom7640** [comment]
it seems to be better except from a location behind a watchbox firewall I don't manage.  Is it possible the firewall blocks websocket ? but the scale button works fine.
So to allow easy manual scale activation, what can I do to permanently show the menu bar. I already mask some buttons, so if the menu bar always appears on the top of my browser windows, it will be good for me and more convenient for touch screen for the moment.

**Comment by cedrozor** [comment]
Yes it's possible, even if surprising nowadays. To see if you are using websockets or not, you can toggle the browser devtools and go into the network > websockets (tab). Then refresh the page (F5) and see if you have websockets traffic. Or you can display the myrtille debug button into the toolbar (default.css, line [260](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/css/Default.css#L260)) and click it to have all connection details (including if using websocket or not).

If you don't have websocket traffic, you can enable the autoscale by adding the same code (as my previous post) into `xmlhttp.js`, line [286](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/js/network/xmlhttp.js#L286)

To show the toolbar permanently, you can modify `default.aspx`, function `initDisplay()`, by adding the following after line [334](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/Default.aspx#L334):

```
if (<%=(RemoteSession != null && (RemoteSession.State == RemoteSessionState.Connecting || RemoteSession.State == RemoteSessionState.Connected)).ToString(CultureInfo.InvariantCulture).ToLower()%>)
{
	toggleToolbar();
}
```

It may be possible but not easy to retrieve the RDP session number, that's an interesting idea.

**Comment by SeRom7640** [comment]
Big thanks for your responsiveness. I'll not be present tomorrow, but i'll do that the day after.

**Comment by SeRom7640** [comment]
OK, now AutoScaling seems to work fine everytime and everywhere.
Thanks for your help and availability.
I remain interested if you find the way to retrieve the RDP session number.
I'll just have to to add an autorenew "Let's Encrypt" certificate into IIS and my project will be ready.

See you soon on Github or somewhere else :) !

**Comment by cedrozor** [comment]
Nice! :)

**Comment by SeRom7640** [comment]
Hi Cedrozor,
I come back to you again about autoscaling.  Since last January, I had my "Brocante" when I meeted no problem whith my bookin software through Myrtille.
At this moment my server was a 2012 edition and my RDP session were used une Windows 10 with the Github RDPWrapper.   It seems that RDPWrapper is dropped down by its conceptor So I decided to upgrade my 2102 server to 'Windows 2019 standard with RDP sessions activated by user CALs.
I decided also to upgrade Myrtille to version 2.7.1.
All works fine execpt for the autoscaling.  I tried to modifiy websocket.js as you show me on 14 Jan but it does not work and seems to have no effect.  What can I do to activate autoscaling ?  Remember my URL command line has size parameters defined to &width=900&height=900
900x900 is the place taken by the software running under the rdp session, so autoscaling will allow the visitor to view the rdp session in full screen mode on a tablet or smartphone.

**Comment by cedrozor** [comment]
Hi,

There were many changes since last January (REST APIs, audio support, clipboard sync, etc.) and I think the default resize mode was indeed autoscaling. It's reconnect now but you can change it (config.js):

Replace
`var defaultResize = browserResizeEnum.RECONNECT; `
by
`var defaultResize = browserResizeEnum.SCALE; `

Also, I modified the autoscale feature to preserve the original aspect ratio (900x900 = 1, in you case) into 2.7.x

**Comment by SeRom7640** [comment]
OK, thanks but is there a way to NOT preserve aspect ratio ? I prefer to use all the browser window...

I also want to always display the tool bar but only with a reduce number of button, I suppose I have to do that in default.aspx ?

**Comment by cedrozor** [comment]
Yes, you can hide the buttons you don't want into default.aspx (by commenting the markup) or default.css (display:none).

Regarding the autocale feature without keeping the aspect ratio, this is something I could have configurable; but the reconnect option should already fit all screen, so finally it may be what you need. Just make sure you have the disconnect timeout set to "never" or at least 1mn (the reconnection process needs at least 3 secs, the session musn't be closed in between...) and "enable automatic reconnection" is checked (otherwise myrtille won't be able to reconnect the session).

https://serverfault.com/questions/873399/rds-2016-session-limits

**Comment by SeRom7640** [comment]
OK for hidding buttons, but is it possible to always show the toolbar ?

I have my booking software and a virtual keyboard in my RDP session like this 👍 
![image](https://user-images.githubusercontent.com/39957946/70541248-fc327200-1b66-11ea-8b98-bcaaeee8e62d.png)
When clicking on the RECONNECT button, the scaling does not change immediately, I have to change my browser window dimension to force a rescaling and after rescaling, the virtual kyboard was correctly "extended" to take all the window width but not my bookin software. like this 
![image](https://user-images.githubusercontent.com/39957946/70541672-c346cd00-1b67-11ea-8f91-7ecc64e83318.png)
in the past autoscaling shows like this 
![image](https://user-images.githubusercontent.com/39957946/70541743-e6717c80-1b67-11ea-8668-f85a410314c0.png)

**Comment by cedrozor** [comment]
Same as previously explained in this thread; 

> To show the toolbar permanently, you can modify default.aspx, function initDisplay():
> 
```
if (<%=(RemoteSession != null && (RemoteSession.State == RemoteSessionState.Connecting || RemoteSession.State == RemoteSessionState.Connected)).ToString(CultureInfo.InvariantCulture).ToLower()%>)
{
	toggleToolbar();
}
```

Contrary to the "autoscale" button, the "reconnect" button is just a toggle and it indeed needs a subsequent resize action to trigger. For consistency, I should have both buttons following the same logic (also noted for a future version). You can have it back to `var defaultResize = browserResizeEnum.RECONNECT;` into config.js to avoid this problem.

The real issue here is that your application's window seems to be locked to 900x900 and doesn't fit the whole session's desktop when maximized. That's why the autoscale without preserving the aspect ratio was good for you (both the keyboard and your application were stretched).

I will see to make the autoscale feature configurable with or without aspect ratio into a next version. Meanwhile, can you have your app to support full desktop size on maximize?

**Comment by SeRom7640** [comment]
Thanks for the toolbar.

I can force my app to support full destop size but it's not what I want because in this case my windows app will be maximized but not the content; fields and text will keep their original size.  I want to strech or compress fiels and text for width and height.
I hope you will be ready for that in your next version.  For the moment, no emmergency, booking for the next "Brocante du Marais" will begin on Marsh 9 2020.

**Comment by cedrozor** [comment]
I will try. Merci pour le retour ! :)

**Comment by SeRom7640** [comment]
I have a problem to show the toolbar permanently.  I look at the default.aspx v2.3 (january 19) to see what were the changes I made and do the same in v 2.7.1 but it does not work 
![image](https://user-images.githubusercontent.com/39957946/70712560-573da380-1ce4-11ea-9df5-33b1d8cbc48f.png)
Something else to do ?

**Comment by cedrozor** [comment]
The code has evolved a bit since 2.3.x, you have to do the following:

Into initDisplay, replace:
```
// toolbar state is saved into a cookie to persist across page reload(s)
if (<%=(RemoteSession != null && (RemoteSession.State == RemoteSessionState.Connecting || RemoteSession.State == RemoteSessionState.Connected)).ToString(CultureInfo.InvariantCulture).ToLower()%> &&
	getToggleCookie((parent != null && window.name != '' ? window.name + '_' : '') + 'toolbar'))
{
	toggleToolbar();
}
```
by
```
// always show the toolbar
if (<%=(RemoteSession != null && (RemoteSession.State == RemoteSessionState.Connecting || RemoteSession.State == RemoteSessionState.Connected)).ToString(CultureInfo.InvariantCulture).ToLower()%>)
{
	toggleToolbar();
}
```
then remove the code you added (in green).

**Comment by SeRom7640** [comment]
Yes I saw it some minuts ago, before reading your post.  It's now OK to show always the toolbar.
I just have a little display problem.  When always showing the toolbar, scroll bar appears on the browser and the bottom of my virtual keyboard is not visible without scrolling, the display must be rescaled a little bit smaller to fit under the toolbar.  
![image](https://user-images.githubusercontent.com/39957946/70723708-a3dfa980-1cf9-11ea-9701-9ef6c44e14ea.png)

**Comment by cedrozor** [comment]
done in 2.8.0

**Comment by SeRom7640** [comment]
Hi Cedrozor,
Nice release, excellent to keep or not aspect ratio :)
but it stays a little display problem : when the toolbar is shown, it will be better to resize the display with the original height minus the toolbar height to avoid scrollbar to appear.
Do you understand what I mean ?

**Comment by cedrozor** [comment]
Hi, of course I understand but you are a bit picky :p

The resizing is done server side because, even if canvas (HTML5 clients) could be scaled client side, it was more difficult for divs (HTML4 clients). So, having a resizing just for the toolbar wasn't a priority.

I will have a look at it into the next version.

**Comment by SeRom7640** [comment]
ok, no problem, this toolbar is not very important for the user.  I hide it and remove the "tree dots menu icon", so scaling is perfect :)
you may close this case.  But I'll come back with another question in a new case ;)
