### ISSUE TITLE
Long Polling protocol refresh problem

### ISSUE THREAD

**Issue by SieldP** [cedrozor/myrtille#145]
Hi,

Cause of my network, I can not use the WS protocol. So I use the LongPolling protocol. However, with this protocol, I can not see the images. I am able to move the mouse/keyboard without problems, but I have no returned images. The only images that I can see are the periodical full screen refresh every 60 seconds.

Any solution ?
Thank you

**Comment by cedrozor** [comment]
Hi, you probably have something over the network that prevent http requests to stay open for an extended period of time (long-polling) or filters out incomplete http responses (long-polling pushes data into the http response).

For example, Fiddler (an http proxy often used for debug) prevents the long-polling to work.

The keyboard and mouse inputs, however, still work because they are processed differently (using an xhr for the HTML4 mode).

That would explain why you can see the screen every 60 secs; it's when the long-polling request finishes.

You should check your network config, or if you have a software (antivirus, firewall, etc.) that could also block long-polling requests.

**Comment by SieldP** [comment]
Thank,

After some tests I saw that I'm able to contact the server, the polling's staying open, but the client can't receive data from the server. (Reponse.Flush does not reach the client).
I'm under a corporat network, I think its proxy block the responses as you said...

I'll stay with the XHR protocol (even if it's slow)

Thank you

**Comment by cedrozor** [comment]
XHR only is slower indeed but it works everywhere! :)

Yes I know about SignalR. When I started working on the myrtille PoC, lonnng time ago (12 years), it wasn't even existing; that's why I kept the native javascript code which is lightweight in comparison.

The websocket implementation of SignalR is the same as Myrtille, both use the same nuget Microsoft dll. I'm not sure why it works and not Myrtille, perhaps it has a fallback to handle proxies... sure, if you do implement it in Myrtille, please make a PR! I was also a bit worried that it could impact the performance, but better have something working slower than not working at all.

**Comment by SieldP** [comment]
Wow 12 years ago ? :o

Yes I’m just takling about SignalR using longpolling transport (you can use multple transport protocols). SignalR using websocket protocol still don’t work under my corporate. I’v just finished, it have the same performance as Myrtille’s long polling protocol, but it work under my network ^^ 
The only problem is that you can’t access to user Sessions in the SignalR’s hubs... To prevent this problem II register each session in a public list in Global.cs file ...
Last thing, I implemented signalr in version 1.6.0 of Myrtille. Should I create a PR? Thank

**Comment by cedrozor** [comment]
Yes, I wasn't working on myrtille for that long, of course. The project was almost abandoned when I decided to open source it 3 years ago.

Sure, please go ahead for a PR, and thank you for that. Did you replaced the native code? (both client and server). It's quite a lot of code in fact. I think it may be good, at least for a transition, to just add a new handler for SignalR, then remove the old stuff progressively.

Also please try to add some comments in your code and test it thoroughly (including some load tests). I won't have much time actually to do it myself.

About http sessions not accessible from SignalR, I had a similar problem lately with a REST web api (HttpContext.Current was null), because it's meant to be stateless. There are some workarounds (https://stackoverflow.com/questions/20522477/no-access-to-the-session-information-through-signalr-hub-is-my-design-is-wrong).

That said, it would be interesting to see why the SignalR long-polling work and not the native code. There is nothing complicated with it, just an http request kept open for 1mn and pushing data into the http response...

**Comment by SieldP** [comment]
Thank you,
Yes, I'll make a PR, I just realized that I have somes issues to keep alive the SignalR connection when there's no image updates in the remote session manager : 
For exemple, there is no disconnection when I run something to continually refresh display every seconds (the windows clock for exemple, it refresh the display every seconds)... but when there's no new images, the client is disconnected..
I tried to force the keep alive by alwayse sending data at each polling cycle by this way : 
```
if (image !=null){
//sending image
}
else{ //keeping alive
//sending something else 
}
```
But it does'nt work also.... I'll find the solution then do some tests and of course a PR :)

**Comment by cedrozor** [comment]
Yes, I had this problem with the websocket connection, so I added a "keep-alive" dummy xhr (https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/js/network/websocket.js#L91) to keep the http session going on (and avoid the default 20mn timeout), even if there is no user inputs or display updates.

**Comment by cedrozor** [comment]
Please go ahead with a PR if you had SignalR working with Myrtille. Thanks!

**Comment by gabriele-v** [comment]
Hi @cedrozor and @SieldP has been ever sent the PR? I'm facing the same issue and I'd like to try with Signal.

Thanks
