### ISSUE TITLE
Unable to add iframe to the right of the RDP display

### ISSUE THREAD

**Issue by daviddowning** [cedrozor/myrtille#147]
First of all this is an awesome piece of code... thank you.

I'm trying to add a new iframe section to the right of the RDP control.  For some reason, the scale button is always disabled and I'm not sure if that relates or not.  I've tried decreasing the width calculations by 400 to see if that helps, but the RDP (myrtille) control is always displayed over my iframe.

I'm using VS 2017 so I've migrated the project a bit and it seems to be working... except the scale and the ability to add an iframe to the right.

Any information is greatly appreciated.

**Comment by cedrozor** [comment]
I will update the documentation because myrtille uses VS2017 for some time.

I'm not sure to understand what you want to achieve exactly with an iframe to the right of the display. Do you want to have something like a toolbar replacement?

The scale button have nothing to do with your issue, it's disabled because myrtille now does a reconnect on resize (with the new browser size). This is something I have improved since, giving the choice to the user to choose either scale or reconnect on resize, I will have it commited into the next version.

About myrtille displayed over your iframe, it's because myrtille detects and uses the full browser size. Instead of tryring to change that detection, you should add a div next (or perhaps into) the myrtille display div (https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/Default.aspx#L287) and have your iframe into that new div.

Then, it's just some css tweaking (see #displayDiv into https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/css/Default.css#L510).

**Comment by daviddowning** [comment]
Thank you for your response... I'll investigate adding the display div.
