### ISSUE TITLE
Swiss-German Backslash 

### ISSUE THREAD

**Issue by DaveSchmid** [cedrozor/myrtille#149]
Bonjour Cedric 
I have a very special, difficult problem: in RDP session with Swiss-German keyboard, browser Chrome with German (Switzerland) as first Language, the Server stands in Switzerland with correct Language, Keyboard and Location is correct to German(Switzerland), the RDP-Session is in German Switzerland (I see the Keyboard in the Tray correct as German(Switzerland). Almost all buttons work as expected, except the most important one for Windows: Backslash \.
Backslash is AltGr + (key <>) on the Swiss-German keyboard. Most of the AltGr keys work perfectly except \ and [ ]. In an SSH session, these buttons all work without problem.

**Comment by cedrozor** [comment]
Hi Dave, what is displayed instead of the backslash? some keys may be reversed, I have never tested in this configuration, I must confess.

What you can do is run the windows osk.exe (on-screen keyboard) and check that the keyboard layout does match your physical keyboard. You can also send a \ keystroke from there or by using the myrtille's "keyboard" button into the toolbar.

**Comment by DaveSchmid** [comment]
There is not a wrong key, it just comes no key. But osk.exe and myrtille's "keyboard" and also Alt + 92 works. I also have English/US keyboard installed on the server and activated but that does not change anything.

**Comment by cedrozor** [comment]
I improved the way keystrokes are sent through the RDP session into the upcoming release, not only for standard RDP but also for RDP over VM bus (Hyper-V). I will commit it as soon as possible (this month or the next).
