### ISSUE TITLE
Myrtille on Linux

### ISSUE THREAD

**Issue by serjponomarev** [cedrozor/myrtille#151]
Is it possible to install Myrtille on Linux? Mono, wine, etc ...? Any solutions?

**Comment by cedrozor** [comment]
Never tried with Wine, may be possible; Mono is quite dead actually, with .Net core. I think the easiest solution would be to run a Windows Server VM on the Linux box. I plan to make a Dockerized Myrtille in a close future, that would also be an option along with a VM.

**Comment by serjponomarev** [comment]
@cedrozor what about run myrtille on kestrel?
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2

**Comment by cedrozor** [comment]
Kestrel is for .net core projects and myrtille uses the classic .net framework, so I don't think it will work. I will have a look to port myrtille to .net core and uses xfreerdp under Linux. It's quite some work but nothing much complicated because the logic remains the same. The only thing I lack is time.

**Comment by DashLt** [comment]
An alternative that runs on Linux is Apache Guacamole.

**Comment by serjponomarev** [comment]
> An alternative that runs on Linux is Apache Guacamole.

In Apache Guacamole, you can pass connection parameters in a string without creating a connection configuration file?
