### ISSUE TITLE
Connect to existing/running session

### ISSUE THREAD

**Issue by Marcusg562** [cedrozor/myrtille#152]
Hi all,

we would like to use myrtille as a RDP application for remote support. Is there a solution how to connect to an exisiting user session without closing the session for the user (Windows 7 and 10)? It would also be nice if the user could request assistance via opening a link. Is such a feature planned?

Kind regards
Marcus

**Comment by cedrozor** [comment]
Hi,

Yes, the user can click the "share" button into the myrtille toolbar. It generates a link that can be used by support to access the user's session. The only thing is that, for security reasons, such sharing links currently provide read-only access (spectator view) to shared sessions.

I will provide the option for the user to grant control access to a shared session into the next versions.

About requesting assistance, it isn't planned for the moment; the user will have to generate and send the sharing link, by any means, to the support of its choice.

**Comment by Marcusg562** [comment]
Thanks for this information. Unfortunately this wouldn‘t solve my issue. We have to connect to an existing Windows session and can‘t share a web session.

Thanks

**Comment by cedrozor** [comment]
A web session is bound to a remote session, so it's finally quite similar. Afaik, a Windows session is opened (owned) by a single user and can't have other users to join it afterward.

**Comment by cedrozor** [comment]
What you are looking I think is the old RDP **shadow** (observe/interact) feature, which was removed in Windows Server 2012 but reintroduced since, does it seems, by Microsoft (according to that article: http://woshub.com/rds-shadow-how-to-connect-to-a-user-session-in-windows-server-2012-r2/).

I will have a look if FreeRDP does support that feature and if I can implement it into Myrtille. It won't be easy though, because it would require a supervision access to the server (listing the active connections).

For now, what you can with Myrtille is to connect the remote server with an admin account, open the Server Manager, RDS role, QuickSessionCollection, and shadow the connection(s) you want from there.

**Comment by Marcusg562** [comment]
Thanks for the information :) sounds good for mee as an IT guy but we would like to provide this to our non IT customers. So if it would be possible to implement the Shadow function this would solve all my probs otherwise I've to review which other HTML5 RDP Software can solve this issue

**Comment by cedrozor** [comment]
This is not in my priority list for myrtille open source, but I could do it as a contractor if you wish.
