### ISSUE TITLE
use VPN wih Myrtille

### ISSUE THREAD

**Issue by percoclap** [cedrozor/myrtille#153]
Hello
I connect on a cloud remote VM using Myrtille, but when I try to launch a VPN on this VM, it auto. disconnects.. is it possible to use a VPN when I'm connected at this time on the VM, when of course I dont know the new IP public address generated by the VPN? thanks in advance

**Comment by cedrozor** [comment]
Hi, it seems to be a network issue. Your VPN might indeed change the public IP of the VM, which in turns disconnect you from the VM and from the remote session.

You should check the VPN configuration so that it doesn't change the public IP. I assume that you connect a private network from the VM, through the VPN? the public IP shouldn't change in such a case (VPNs usually create a new network interface to join the private network).

**Comment by cedrozor** [comment]
Were you able to check your VPN config?

**Comment by cedrozor** [comment]
closed to lack of feedback
