### ISSUE TITLE
Cyrillic clipboard from remote to local buggy

### ISSUE THREAD

**Issue by romanad** [cedrozor/myrtille#159]
Hello, dear support team and developer.
I found new issue with clipboard when copying Cyrillic text from remote to local.
It doesn't represent correctly.
Tested with HTML 5 websocket with 2.5.5 latest version.
Please see attached screenshots.

![cyrillic_text_buggy](https://user-images.githubusercontent.com/26842711/58788997-c16ae280-85f5-11e9-8663-7a5aff27d7b1.jpg)
![2 5 5](https://user-images.githubusercontent.com/26842711/58789126-11e24000-85f6-11e9-943e-ebfad39f7269.jpg)

**Comment by cedrozor** [comment]
Hi, thanks for reporting this issue. I normally use UTF8 encoding into Myrtille to support any character set, but there must be  some parts of the code which don't. It may also be related to FreeRDP because Myrtille read the clipboard content from it.

I was thinking to use a base64 encoding to send the clipboard content, then decode it into the browser. I may eventually do this.

**Comment by cedrozor** [comment]
#158 duplicate
