### ISSUE TITLE
Feature Request: Installer: Update Option

### ISSUE THREAD

**Issue by buchser** [cedrozor/myrtille#163]
It would be great if it could be possible to update the Myrtille installation with a newer version, keeping the settings/configuration files.

Running Myrtille/RDS in productive environments, this would significially reduce maintenance time and enable the use of new features much faster.

As a temporary workaround, it would be cool to have a complete list of the configuration/customization files to back up before uninstall the old version.

This might be automated and added as a custom execution script in the MSI installer.

**Comment by cedrozor** [comment]
Yes, I initially wanted to have an auto-update installer but it proven difficult to do with the basic MSI Visual Studio plugin and prone to errors because changes to configuration might not be backward compatible with older versions. So I preferred to play security and ask for a previous uninstall.

But I undertand it can be frustrating. I am thinking to replace the installer engine by something newer, which would handle such configuration or dependencies changes automartically.

Meanwhile, there are 2 config files that you would like to backup prior installing a newer version:

- Web.config
- bin/Myrtille.Services.exe.config

Details here: https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#configuration--performance-tweaks--debug

**Comment by buchser** [comment]
Thanks for the explanation!
