### ISSUE TITLE
Websocket connection errors started

### ISSUE THREAD

**Issue by datgb** [cedrozor/myrtille#167]
The install initially was working great. Everything was working fast and no problems. screen adjusted fast to the browser window changes and I could type like normal. 

Couple days later and now I have websocket connect errors 1006 (yes it is checked off in features). Page doesnt respond fast and when i type its so slow it missing letters. Ive tried different browsers and all the same. firefox, firefox developer, brave browser. Brave browser seems to be a bit faster but still errors show and page doesnt scale.

**Comment by datgb** [comment]
updating. Errors still on brave browser and scaling now and not missing letters when typing. Everything still occuring on firefox

**Comment by cedrozor** [comment]
Do you see the error 1006 (https://stackoverflow.com/questions/19304157/getting-the-reason-why-websockets-closed-with-close-code-1006/19305172#19305172) into your browser dev tools? when you say "it's checked off in features", do you mean the IIS features? if that is, of course you have to re-check it (but how did it got unchecked?)

From your last entry, ERR_CERT_AUTHORITY_INVALID means that your SSL certificate is probably expired; myrtille gets slow because it fallback to xhr and long-pollling.

To check that the issue is the SSL certificate (to update on IIS for myrtille), try to access the page with http://

For the record, myrtille proposes to create a self-signed certificate on install, but it's only valid 1 year (standard duration).

**Comment by cedrozor** [comment]
During recent tests, I found that the latest versions of Chrome are more picky about SSL certificates. It may be the same with Firefox or Brave.

I got a “**Subject Alternative Name Missing**” with the self-signed certificate created by Myrtille during install, _even after clicking advanced -> proceed to the website_ (creating a security exception).

After digging, I found that the certificate needed the DNS name into that entry (https://stackoverflow.com/questions/43665243/invalid-self-signed-ssl-cert-subject-alternative-name-missing/43665244#43665244).

So, If the machine on which Myrtille is installed is part of a domain (with a domain controller, DNS server, etc.), the "Myrtille self-signed certificate" may be reported as invalid; after double clicking it (from the IIS management console), the Certification Authority (CA) is not trusted because not in the trusted root CA store! problem is, the CA _is into that store_ (!)

The fix was to create a new self-signed certificate (from the IIS management console); give it a unique name and ensure the certificate is valid (double click it). You should now read "Delivered by", "Delivered for" = **machine FQDN** (also into "DNS Name=" for the alt subject name entry).

Now, have the default website to use this certificate instead of the default one (bindings > https > the new certificate).

Sorry if it's complicated! this whole SSL thing need a master degree lol. I will try to automate this in the next version.

**Comment by cedrozor** [comment]
But again, can you try to access myrtille with **http://** to check if it's works well without SSL?

**Comment by cedrozor** [comment]
Any news please? 

The best would be to install a trusted certificate (GoDaddy, Comodo, Let's Encrypt, etc.). Also, you did enabled websockets into the IIS features, isn't it?

**Comment by cedrozor** [comment]
I can't help more without feedback :/

**Comment by manto89** [comment]
Hi, i'll write here since I have a similar problem.
My setup: 
Myrtille 2.7.0.0 freshly downloaded and installed from website, Debian gateway with Apache setup with a reverse proxy to a Windows Server 2012.
Apache config:
```
        RewriteEngine on
        RewriteCond %{HTTP:Upgrade} websocket [NC]
        RewriteCond %{HTTP:Connection} upgrade [NC]
        RewriteRule .* "wss://192.168.1.2:8080%{REQUEST_URI}" [P]
        ProxyPass        / http://192.168.1.2:8080/
        ProxyPassReverse / http://192.168.1.2:8080/
```
I can connect without problems but i notice that while typing some characters are missing.
If I open up a web console (both with Firefox and Chrome) i get these messages:
```
websocket.js?v=IAu8c…rf_iXImPv-KhwCs1:41 WebSocket connection to 'wss://remote.mydomain.com/(S(xxxxx))/SocketHandler.ashx?type=binary' failed: Error during WebSocket handshake: Unexpected response code: 500
Websocket.init	@	websocket.js?v=IAu8c…rf_iXImPv-KhwCs1:41
Network.init	@	network.js?v=eeoKku3…ZMsSKFMlaVE-CI1:184
Myrtille.init	@	myrtille.js?v=kPvZMG…OUwSQo2qjnPHEg1:109
startMyrtille	@	myrtille.js?v=kPvZMG…OUwSQo2qjnPHEg1:304
onload	@	(index):54

audiowebsocket.js?v=…IuhW9j9tZEeXv3M1:45 WebSocket connection to 'wss://remote.mydomain.com/(S(xxxxx))/AudioSocketHandler.ashx?type=binary' failed: Error during WebSocket handshake: Unexpected response code: 500
AudioWebsocket.init	@	audiowebsocket.js?v=…IuhW9j9tZEeXv3M1:45
Network.init	@	network.js?v=eeoKku3…ZMsSKFMlaVE-CI1:192
Myrtille.init	@	myrtille.js?v=kPvZMG…OUwSQo2qjnPHEg1:109
startMyrtille	@	myrtille.js?v=kPvZMG…OUwSQo2qjnPHEg1:304
onload	@	(index):54
```
I've tried to test the connection with https://www.websocket.org/echo.html and it seems like i can get a response by pinging my website 
![github](https://user-images.githubusercontent.com/6862296/69355773-a9aa1800-0c82-11ea-8fea-6ccbcb24316f.png)
Although I'm not sure that this is a helpful test.
Any other ideas on how to debug this? I'll be happy to help :)

**Comment by cedrozor** [comment]
Hi, thanks for these details.

The websocket support into myrtille is done through IIS, the same way as SignalR does (using the same official Microsoft nuget libraries). This requires the websocket protocol enabled into IIS (https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#installation, see https://www.iis.net/configreference/system.webserver/websocket). 

The websocket traffic goes through the port tcp 80 (not 8080) when accessing the website with http (ws://) and 443 with https (wss://). So, you should check your network config. Did you tried a direct access (without a reverse proxy)?

Also, despite HTML5 being there for a long time, there are still many network equipments that filters or even blocks the websocket traffic. That's why I kept the HTML4 fallback (xhr and long-polling) into myrtille.

Maybe you could have more luck using base64 instead of binary data (https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/js/config.js#L75).

Someone also recently reminded me about the existence of a less known communication option for browsers, namely [event source](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) (http protocol), working in all but IE (Chromium from now on). I may implement it one day into myrtille.

**Comment by manto89** [comment]
Hi, thanks for the fast reply! It was indeed a problem on the proxy, since I tried to connect to the service without the reverse proxy (as you suggested) and it was working.
For anyone that might encounter this problem, the configuration posted is correct but it is necessary to enable the apache module called mod_proxy_wstunnel.
On Debian it's just a matter of executing the following command:
sudo a2enmod proxy_wstunnel
I hope it helps someone.
Thanks @cedrozor for the amazing app and support, I'll be glad to contribute to this project :)

**Comment by cedrozor** [comment]
You are welcome :) thanks for these details.
