### ISSUE TITLE
White screen when connecting to RDP

### ISSUE THREAD

**Issue by gtmsew** [cedrozor/myrtille#169]
![white screen issue](https://user-images.githubusercontent.com/51693068/61515726-9bfa3280-aa03-11e9-9548-8d9d18e2f5f9.png)
Hello,

sometimes when a user tries to connect, it shows him the "white screen". It looks like the website is loading but it can stay like this forever. Any way I can troubleshoot this?

**Comment by cedrozor** [comment]
Hi, did you tried to unfold the toolbar (the top left, 3 dots button) to see what options are enabled ? try the stats and debug buttons to display some usage and debug info.

if you don't have something useful, you can check the Windows event logs (system and application) and/or the myrtille logs (myrtille install path, log folder).

If that's not enough, you can aso check the troubleshoot section: https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#troubleshoot

Did you enabled the websokets protocol into IIS (https://www.iis.net/configreference/system.webserver/websocket)? if you did, it may be blocked by some network software or equipment; you can try to switch to HTML4 (xhr and long-polling) by clicking the HTMLx button into the toolbar.

**Comment by cedrozor** [comment]
Also, can you try to access the page with "**http://**" (instead of https://) to see if it's an SSL certificate issue?

Please keep me updated.

**Comment by cedrozor** [comment]
Thanks for your input.  When you say "blue screen", is it the windows logon screen which is stuck or just a blank page? did you tried to refresh the page (F5), does the problem persist?

It could be the same issue than the original poster. I noticed that Chrome is more picky lately about SSL certificates and reject self-signed certificates that don't include an "**alt subject name**" . For example, I had to create a new self-signed certificate on my dev environment for Chrome to allow me to create a security exception (self-signed certificate) over **https**.

I will update the self-signed certificate generation into the next release. For the moment, you can do the same as I did by [using the IIS management console to create a self-signed certificate](https://aboutssl.org/how-to-create-a-self-signed-certificate-in-iis/) and bind it (https scheme, port 443) to the IIS website on which myrtille depends.

But it may be something else. Could you, as I asked the OP, try to access the page over **http**?

Finally, could you open the **Chrome dev tools** (Ctrl+Shift+I) and check the console and network tabs for any errors?

**Comment by morths** [comment]
Thank you for your answer! 

First of all i forgot to mention that i had already tried http with no success..
Also, i am not using myrtille's or any other **self-signed** certificate. I have my own ssl certificate from "godaddy.com".

The blue screen i'm talking about is the screen that comes up right after i enter my credentials in the initial myrtile screen and just before my windows server logon page comes up. It's like myrtille (or something else) hangs somewhere between...

Its worth mentioning that, since my last post, i attempted to connect from a different machine with chrome and html5 and.. voila, no problem at all!! The connection was successful! 

Nevertheless i can't understand why it doesn't connect from the first pc i tried, while with previous myrtille version there was no problem.. (same pc / chrome setup - hasn't changed any settings since previous myrtille version)

I will try chrome dev tools later and report back!

**Comment by gtmsew** [comment]
On my end, the issue occurs occasionally, but mostly for people with a not stable internet connection, and just after that (if they will be able to go thrue this) it shows the error "latency > 5000"

**Comment by gtmsew** [comment]
A small update from me. 

The server where the Myrtille is Hosted is in Asia (RDS is also there but as a separated instance), and all the issues reported are from people located in USA, Canada, Mexico and everyone from South America Countries. They have 200-350ms latency to the servers. After a couple of tries, they can connect normally, without the "white screen". All of the people are using Chrome (it is forced by us)

Websockets are enabled, I use https, http is not an option for me to switch.

Ah, and people located in Europe and Asia (so basically with latency < 150ms) do not face this issue.

**Comment by cedrozor** [comment]
> Its worth mentioning that, since my last post, i attempted to connect from a different machine with chrome and html5 and.. voila, no problem at all!! The connection was successful!

This is interesting and could indicate a network issue. Do you have a firewall, antivirus or something on the machine, or your network, that could filter the network traffic? For example, I have Eset Nod32 on a machine and it takes some serious initiatives with the web protection enabled, like checking the SSL certificates, blocking scripts, analysing the traffic, etc...

Is the Chrome version the same between the 2 machines? no different extensions?

> Nevertheless i can't understand why it doesn't connect from my other pc, while with previous myrtille version there was no problem.. (same pc / chrome setup - hasn't changed any settings since previous myrtille version)

Check the console and network tabs with the Chrome devtools (Ctrl+Shift+I). If something is filtered/blocked, you should see it.

> Ah, and people located in Europe and Asia (so basically with latency < 150ms) do not face this issue.

Same here, there might be some network equipments that don't like laggy websockets connections and drop them over a certain latency. Please open your Chrome devtools and tell me what you see.

It also happened in the past that websocket protocol was filtered or blocked by some routers, reverse proxies, load-balancers, etc.. That's why I had an HTML4 backward compatibility into Myrtille; long-polling uses http protocol which is often not filtered/blocked (even if, there again, some network equipments don't like connections opened for too long time... myrtille long-polling is 1mn by default, which should be ok for most of them).

Can you enable HTML4 for a try? (toolbar -> HTML5 ON/OFF). If that works for you, just edit **js/config.js** into the myrtille install folder and have HTML4 enabled by default for all users (https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/js/config.js#L147, replace _networkModeEnum.AUTO_ by _networkModeEnum.LONGPOLLING_).

**Comment by gtmsew** [comment]
@cedrozor WHen I click the ... I cannot switch to HTML4 for some reason, it is not active.

![image](https://user-images.githubusercontent.com/51693068/65459604-8d3f5a00-de50-11e9-9279-1aca46695c1c.png)

**Comment by gtmsew** [comment]
Here are my settings, that I use to support users from around World, any advice about what to change to improve the speed for users with high latency?

`// dialog
    var debugConsole = false;                           // output the debug messages into the browser javascript console (or on screen otherwise)
    var debugLinesMax = 40;                             // max number of displayed debug lines (rollover) when the output is on screen
    var keyboardHelperEnabled = false;                  // display a yellow tooltip to show the user inputs on-the-fly; useful when the latency is high as the user can see a direct result of its action
    var keyboardHelperSize = 75;                        // max number of characters to display into the keyboard helper
    var keyboardHelperTimeout = 3000;                   // duration (ms) before removing the keyboard helper

    // display
    var defaultResize = browserResizeEnum.RECONNECT;    // default action on browser resize (RDP host only)
    var displayMode = displayModeEnum.AUTO;             // display mode
    var imageEncoding = imageEncodingEnum.AUTO;          // image encoding
    var imageQuality = 60;                             // image quality (%) higher = better; not applicable for PNG (lossless); tweaked dynamically to fit the available bandwidth if using JPEG, AUTO or WEBP encoding. for best user experience, fullscreen updates are always done in higher quality (75%), regardless of this setting and bandwidth
    var imageQuantity = 100;                            // image quantity (%) less images = lower cpu and bandwidth usage / faster; more = smoother display (skipping images may result in some display inconsistencies). tweaked dynamically to fit the available bandwidth; possible values: 5, 10, 20, 25, 50, 100 (lower = higher drop rate)
    var imageTweakBandwidthLowerThreshold = 50;         // tweak the image quality & quantity depending on the available bandwidth (%): lower threshold
    var imageTweakBandwidthHigherThreshold = 90;        // tweak the image quality & quantity depending on the available bandwidth (%): higher threshold
    var imageTweakLatencyLowerThreshold = 250;          // tweak the image quantity depending on the average latency (ms): lower threshold
    var imageTweakLatencyHigherThreshold = 750;         // tweak the image quantity depending on the average latency (ms): higher threshold
    var imageTweakLatencyCountPerSec = 20;              // tweak the image quantity depending on the average latency and image count per second
    var imageCountOk = 100;                             // reasonable number of images to display at once; for HTML4 (divs), used to clean the DOM (by requesting a fullscreen update) as too many divs may slow down the browser; not applicable for HTML5 (canvas)
    var imageCountMax = 200;                            // maximal number of images to display at once; for HTML4 (divs), used to clean the DOM (by reloading the page) as too many divs may slow down the browser; not applicable for HTML5 (canvas)
    var imageMode = imageModeEnum.AUTO;                 // image mode
    var imageBlobEnabled = false;                       // display images from local cached urls using blob objects (HTML5 only, binary mode)
    var imageDebugEnabled = false;                      // display a red border around images, for debug purpose
    var periodicalFullscreenInterval = 10000;           // periodical fullscreen update (ms); used to refresh the whole display
    var adaptiveFullscreenTimeout = 1500;               // adaptive fullscreen update (ms); requested after a given period of user inactivity (=no input). 0 to disable

    // audio
    var audioFormat = audioFormatEnum.WAV;              // audio format (HTML5); requires websocket enabled and RDP host; IE doesn't support WAV format (MP3 fallback); others: WAV and MP3 support
    var audioBitrate = 1411;                            // bitrate (kbps); possible values for WAV: 1411 (44100 Hz, 16 bits stereo); possible values for MP3: 128, 160, 256, 320 (CBR); lower = lesser quality, but also less bandwidth usage (128 kbps is good enough for sound notifications)

    // network
    var additionalLatency = 0;                          // simulate a network latency (ms) which adds to the real latency (useful to test various network situations). 0 to disable
    var roundtripDurationMax = 5000;                    // roundtrip duration (ms) above which the connection is considered having issues
    var bandwidthCheckInterval = 300000;                // periodical bandwidth check; used to tweak down the images (quality & quantity) if the available bandwidth gets too low. it relies on a 5MB dummy file download, so this param shouldn't be set on a too short timer (or it will eat the bandwidth it's supposed to test...)
    var networkMode = networkModeEnum.AUTO;             // network mode
    var httpSessionKeepAliveInterval = 30000;           // periodical dummy xhr calls (ms) when using websocket, in order to keep the http session alive
    var xmlHttpTimeout = 3000;                          // xmlhttp requests (xhr) timeout (ms)
    var longPollingDuration = 70000;                    // long-polling requests duration (ms)
    var bufferEnabled = true;                           // buffer for user inputs; adjusted dynamically to fit the latency
    var bufferDelayBase = 0;                            // minimal buffering duration (ms)
    var bufferDelayEmpty = 10;                          // buffering duration (ms) when sending empty buffer
    var bufferSize = 128;                               // max number of buffered items (not size in bytes)

    // user
    var mouseMoveSamplingRate = 100;                    // sampling the mouse moves (%) may help to reduce the server load in applications that trigger a lot of updates (i.e.: imaging applications); possible values: 5, 10, 20, 25, 50, 100 (lower = higher drop rate)`

**Comment by morths** [comment]
Sorry i didn't wrote earlier but i don't have much time lately... 

Yesterday i opened chrome devtools (from the problematic pc) as you suggested but there wasn't any error or something similar (like a warning) in the console and network tabs. Especially in the console tab there wasn't any input at all (nor any new input created during my numerous attempts to connect through myrtile - html5...). Guess i'll have to stick with html4 from that specific pc..

Nevertheless, after succesfully connecting with chrome / html5 the other day, even from another machine, i strongly believe that my issue has to do with my second pc's setup or chrome setup most likely and not with myrtille itself.

Due to lack of time i can't try many things now but when i find time i will surely uninstall chrome, reinstall it from scratch and check if that solves my issue.. Then i will report back.

Thank you for your help!

**Comment by cedrozor** [comment]
What are the values changed into config.js? it will be easier for me to diagnose the issue. 

You can try to lower the latency tweaking thresholds, for example:
```
var imageTweakLatencyLowerThreshold = 200;          // tweak the image quantity depending on the average latency (ms): lower threshold
var imageTweakLatencyHigherThreshold = 500;         // tweak the image quantity depending on the average latency (ms): higher threshold
var imageTweakLatencyCountPerSec = 10;              // tweak the image quantity depending on the average latency and image count per second

```
this will trigger the changes of the display quality and the updates rate earlier.

But websockets are made for low latency networks and don't scale well when the latency gets high. You should try to enable long-polling, with this line:

`var networkMode = networkModeEnum.LONGPOLLING;             // network mode`

I have some ideas to improve the websockets performance into a next version, but http(s) long-polling should help for now.

**Comment by gtmsew** [comment]
@cedrozor 

After I made the changes you recommended, the WebRDP was not usable by users with latency higher than 200ms. It was super slow for users, I had to revert the changes and everything back to normal after that.

**Comment by cedrozor** [comment]
Yes, 200ms was perhaps a bit too low. What does the "tweak" when the latency gets high (so, from 200ms) is to drop some display updates in order to avoid stacking them with an accumulated delay. The result is a much less responsive display and can be a bit confusing for the end user.

What about the  long-polling mode, as I suggested above? with it enabled, you could reset the tweaking thresholds to their default values.

**Comment by cedrozor** [comment]
I fine-tuned the display tweaking into the upcoming version, but I would be interested to know if long-polling improved the experience for your users (after reverting to the default tweak settings) Thanks!

**Comment by gtmsew** [comment]
@cedrozor I apologize for my late reply. After I revert to the default settings I also go back to auto instead of long-polling
When I started long-polling earlier without the additional changes I had much more complains that the system is very slow (stable, no white screen but really slow).

What bother me a bit is that on Myrtille the experience for clients with 300-350ms is much worse than on native RDP client. Is there anything I can do to have it working better for clients with higher ping, so at least it will work the same way as on default RDP client?

**Comment by cedrozor** [comment]
@gtmsew, please tell me if myrtille 2.7.0 improves things

**Comment by gtmsew** [comment]
I just deployed 2.7.0. I will update you as soon I will face any problem.

**Comment by gtmsew** [comment]
Just FYI, the 2.7.0 is F GREAT, working much better for users with higher latency (350-400ms).

Big thank you!

**Comment by gtmsew** [comment]
@cedrozor just a quick update from me.
We recently have other users with the white screen, even for users with low latency (60-80ms) and without any ids/ips/firewall or anything else filtering the traffic.
What help is that change in Chrome:
![image](https://user-images.githubusercontent.com/51693068/74284464-0f5aed00-4d24-11ea-9b19-21db2bdee51d.png)

This issue is happening for a margin number of clients. All others use also Chrome. We have cloudflare in front of the IIS.

**Comment by cedrozor** [comment]
Thanks for your input. What you can do also is force IIS to enforce HTTPS (https://aboutssl.org/iis-redirection-http-to-https/). Then, if you hadn't already, you should replace the default self-signed certificate with a trusted one.

**Comment by gtmsew** [comment]
The weird part is that I have the rewrite rule already there and users always access the Myrtille via https.

**Comment by cedrozor** [comment]
Do you use trusted certificate(s) (not self-signed)?

**Comment by cedrozor** [comment]
Hi, any news?

**Comment by gtmsew** [comment]
> Do you use trusted certificate(s) (not self-signed)?
> 
> So, the issue is only on Chrome? is it possible it could be related to Cloudflare?

Sorry, I did not saw your reply.

I'm using Cloudflare SSL and on origin server lets encrypt SSL cert.

I can't check if it is on any other browser than Chrome.

I doubt it is the "Cloudflare" issue because at the same time there are clients that have no issue at all.

**Comment by cedrozor** [comment]
Do you use an http proxy or an antivirus with internet security? these are nice tools but they can be on a too aggressive setting, altering the communication and breaking it. Long-polling, for exemple, doesn't work with Fiddler and both Fiddler and Nod32 can filter the SSL/TLS protocol (with trusted root certificates). I also had some troubles with Bitdefender in the past.

This could explain why Myrtille works for some users and not for others; and there may also be network filtering (less usual).

**Comment by cedrozor** [comment]
Hi @gtmsew, any news since on this issue?

**Comment by gtmsew** [comment]
> Do your users have an HTTP proxy or an antivirus with internet security? these are nice tools but they can be in a too aggressive setting, altering the communication and breaking it. Long-polling, for example, doesn't work with Fiddler and both Fiddler and Nod32 can filter the SSL/TLS protocol (with trusted root certificates). I also had some trouble with Bitdefender in the past.
> 
> This could explain why Myrtille works for some users and not for others; and there may also be network filtering (?), depending on the internet connection (less usual).

I apologize for the delayed reply. Those users have their firewalls/av disabled, no network filtering. Myrtille is over Cloudflare with SSL/TLS set to "Full" and there is a cert between Myrtille and Cloudflare signed by LetsEncrypt. 
When we will disable in Chrome the "mark non-secure origins" (screenshot in the previous post) everything is working fine. We have a re-write rule on ISS to always point to 443.

Any idea what we can check or do more to avoid this?

**Comment by cedrozor** [comment]
Thanks for your feedback. It's much appreciated and necessary so that I can improve Myrtille.

Do you have users on Firefox or Edge (the new one, Chromium based)? does this problem occurs? if the SSL certificate is valid and everything on the page is accessed with `https://` (`wss://` for websockets) on the same domain (or sub-domain), there shouldn't be any "non-secure origins" (and even if it happened, it would happen for all users).

I'm not able to replicate this problem with Chrome, but I don't use Cloudflare. Do you have a non-Cloudflare setup to test Myrtille against?

Aside from Chrome, what is the Operating System for your users with this problem?

**Comment by gtmsew** [comment]
We are forcing users to use Chrome only. But since Chromium identify itself as Chrome we checked there also - the same issue. 
Yep, everything is accessible via wss/https, no console errors etc.

Only Cloudflare. But this issue is maybe 1 user for 100. It is not like everyone has the same issue. We can have 40 users connected at the same time and one of them will have this problem.
Hm, various OS's but at this point, I do not remember if users with issue were using Win7 or Win10. We will note that from today and I will get back to you.

**Comment by cedrozor** [comment]
Closing for now. Please re-open if needed, I'm still interested by any details you can provide.

**Comment by gtmsew** [comment]
hi @cedrozor 

There is mostly an issue with people from Turkey, Saudi Arabia, United Arab Emirates

Screenshots below are from user from Turkey.

Tested on 2 different domains, with Cloudflare proxy disabled and enabled, with VPN and without VPN. User even tried to use his 4G. At that time I restarted the IIS, Myrtille service, tried with all 4 settings related to 'networkModeEnum'. Nothing, always blank screen even and when I try to "click" something from the top menu it does not work and throw an error in console (2 examples attached)

![image](https://user-images.githubusercontent.com/51693068/89453299-54099300-d75f-11ea-9ec9-28065357c094.png)

![image](https://user-images.githubusercontent.com/51693068/89453307-57048380-d75f-11ea-9b9b-af60f835d2b6.png)

![image](https://user-images.githubusercontent.com/51693068/89453320-5bc93780-d75f-11ea-9e34-a46a00750079.png)

Please advise what I can do more for that user, how to troubleshoot
