### ISSUE TITLE
Password and Login in plan text in URL

### ISSUE THREAD

**Issue by gzz1sql** [cedrozor/myrtille#17]
Hi,

I just realized, that Password and Username are visible in the URL. This hinders a usage in a near productive environment. Is there a possibility to change that behavior to move these to Post and use Session-Variables instead of Paramenters in post.

Cheers
Karsten

**Comment by cedrozor** [comment]
Hi Karsten, thanks for your feedback.

Yes you can set the form method to "post" instead of "get" in default.aspx; I did it initially (with session variables), but it has a boring drawback: if you hit F5 to reload the page, the browser ask you if you want to re-post the form data (standard behaviour). I understand the security argument but, if you use https, the querystring is also encrypted with SSL (so it's ok from a network point of view).

That said, indeed, if someone has access to the browser history, it could find back the credentials within url. What is possible to do is to have the form posted, save the credentials within session (may be used for file transfer), then set the page url with javascript as "window.location.href = window.location.href", which will make the browser to reload the page but without the form data (so subsequent F5 will not bother to repost the form).

I will have a look at it as soon as possible.

**Comment by cedrozor** [comment]
Fixed in release v1.1.1

**Comment by gzz1sql** [comment]
Hey Cedric,

well done. Now we are save :-).
