### ISSUE TITLE
IME Keyboard

### ISSUE THREAD

**Issue by joburg** [cedrozor/myrtille#176]
Does Myrtille support IME keyboards for input?  Specifically, for languages that need double-byte chars when typing a character(s), e.g. Korean, Japanese or Chinese.  The keyboard issues I've seen in the issues list relate to the non-IME keyboard input. I haven't seen anything for IME. short of forking the code and making changes, I would like to see if there is already built-in support in the current released version.

**Comment by cedrozor** [comment]
keyboard inputs are already handled as unicode from javascript and I also made some changes into the upcoming release to handle unicode characters into the clipboard.

The only thing for IME keyboard is that it must be enabled server side. In the case of Chinese, there is an issue related to javascript (not myrtille) which makes it necessary to also run osk.exe _server side_, to have the dropdown toolbar displayed and thus be able to select the right symbol. See https://github.com/cedrozor/myrtille/issues/170

**Comment by joburg** [comment]
Current scenario is this, I have IME input enabled on remote workstation that I am connecting to. It is set for Japanese Hiragana input. Then locally, I set the same (Japanese Hiragana). When I type text into the remote desktop, it is interpreted as english/romanic characters, i.e. if I type taka, this should have come out as たか ... instead it comes out as "taka". Looking at the Microsoft IME behavior (on my local machine), I see that when I bring focus to the canvas (displaying the desktop) IME becomes disabled. And when I display the on-screen keyboard (from the gateway toolbar), I am able to type Japanese chars and then "send" them to the text editor in the remote session. Is there something that needs to be enabled to allow the canvas to be recognized as an IME-compatible element? (I am inferring that based on the behavior I am seeing)...

**Comment by cedrozor** [comment]
I made some additional researches, because I'm not an expert in IME keyboards (and Japanese or Chinese), and I found that the myrtille javascript code can't handle them because it only uses the standard keyboard events ("keydown", "keyup", etc.). IME keyboards need "composition" events, as explained here: https://www.w3.org/TR/ime-api/.

So I think the problem is not related to the canvas element but to these events which are not currently handled by myrtille.

This API is quite recent, it didn't existed back in time when I worked on the myrtille precursors ;)

**Comment by joburg** [comment]
One thing i wanted to ask, is there a way to switch to non-Unicode transmission of keycodes?  I've looked over snippets of code in the FreeRDP client and was thinking that sending ASCII keycodes just for languages that rely on phonetics to identify a char might allow the MS IME component to recognize what is being typed.

**Comment by cedrozor** [comment]
I don't think it's possible, because javascript already returns the keycodes as unicode values. Also, ASCII is not meant to handle multi-bytes per char and I don't think the MS IME is able to intercept a typed character if the browser takes over it.

I think the way to go is the composition events from javascript, and having them bound to the canvas.

**Comment by joburg** [comment]
I finally got it to work with Japanese. Took a lot of trial and error. But with Microsoft IME active on the remote session and Kanji Input is enabled, the phonetic phrases typed from the local keyboard were recognized and MS IME was able to pop-up likely choices for Hiragana characters.

**Comment by joburg** [comment]
i was able to type this in word
![image](https://user-images.githubusercontent.com/11280286/65626062-c4f9ef00-df81-11e9-85d6-0d55801d47ef.png)

**Comment by joburg** [comment]
and that's not using the OSK in the remote session. that's a local US keyboard with the remote session using an active Microsoft IME with Kanji input enabled.

**Comment by cedrozor** [comment]
That's great :) how did you proceed client side? but that's also require IME to be enabled server side, whereas most users would expect it to work from their IME client side (that's where composition events come in).

**Comment by joburg** [comment]
Yes. You are correct. Locally the canvas element is considered a graphic element and automatically disables any kind of IME input. And that's where that compositional API has to be implemented. For our purpose, having a US keyboard with the remote session having IME enabled works (for now). :)

**Comment by cedrozor** [comment]
How did you proceed? that may help for future implementation.

**Comment by cedrozor** [comment]
Any info would be greatly appreciated.

**Comment by joburg** [comment]
Switched everything over to scan codes and then modified the mapping for the xrdp codes to support the keystrokes.

**Comment by cedrozor** [comment]
Interesting, thanks. You mean [this mapping,](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/src/JSKeyCodeToRDPScanCodeMapping.cs) and these [xrdp codes,](https://github.com/neutrinolabs/xrdp/blob/devel/xrdp/rdp-scan-codes.txt), right? I had the mapping for US keyboard layout, did you modified it for Japanese ?

**Comment by joburg** [comment]
Yes. Just had to add and account for all characters on the keyboard. Japanese keyboards are actually laid out in QWERTY. so i just had to account for the extra ones.

**Comment by joburg** [comment]
is the default keyboard layout set for US QWERTY?

**Comment by cedrozor** [comment]
Yes, [here](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/src/JSKeyCodeToRDPScanCodeMapping.cs); but it's normally used only for non character keys (i.e: enter, backspace, tab, etc.) whose codes are common for any keyboard layout, while character keys (i.e: a, b, c, etc.) are sent as unicode (directly from javascript), according to the layout.

I will rework that anyway in a future version, with full IME support as discussed in this thread, because the current implementation has limitations that require server-side IME activation, whereas it should work directly on the client side with the canvas element.

**Comment by cedrozor** [comment]
the next version of Myrtille will include an on-screen virtual keyboard (multi languages/layouts, including Chinese, Hebrew, Russian, etc.) in case of any keyboard issue. This will be a first step before supporting IME events.

**Comment by cedrozor** [comment]
2.9.0 is released, with a multi-languages on-screen keyboard, for those who have issues typing some characters
