### ISSUE TITLE
Cannot start a program on connection while passing parameter

### ISSUE THREAD

**Issue by Hardik0707** [cedrozor/myrtille#178]
Hii, 
I tried to open application through URL on connection but it cannot happen as expect I need to change group policy for start program on connection. Can you tell how to change dynamically that Via Myrtille.

Thank you.

**Comment by cedrozor** [comment]
If you installed the RDS role, you need first to allow the application to run as remote application, as explained [here](https://www.beyondtrust.com/docs/privileged-identity/app-launcher-and-recording/installation/set-up-rds.htm).

Then, the url must be as described into the [documentation](https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#auto-connect--start-remote-application-from-url).

**Comment by Hardik0707** [comment]
Ok will let you know after trying above solution.

**Comment by cedrozor** [comment]
Were you able to try?

**Comment by Hardik0707** [comment]
Nope, Due to administrator rights can't install RDS role but I got error now while Debugging in visual studio showing that "xhr timed out, Please check your Internet connection". The release version is working fine and while building MSI file from debugging getting error in Websocket.js

**Comment by Hardik0707** [comment]
Can I run any other process instead of wfreerdp.exe on windows server and stream back that process on browser ?

**Comment by cedrozor** [comment]
You have to [enable websockets into IIS](https://www.iis.net/configreference/system.webserver/websocket) or myrtille will otherwise fallback to xhr (with lesser performance). If you are debugging, you may have indeed timeout warnings because breakpoints temporarily stop the network communication.

wfreerdp is the RDP client, you can replace it by something else but, in such a case, you will have to handle the display streaming to the browser (which would not be easy and why reinvent the wheel?)

**Comment by cedrozor** [comment]
Wish you good luck replacing wfreerdp, please keep me updated.
