### ISSUE TITLE
Closing tab not disconnect session

### ISSUE THREAD

**Issue by gtmsew** [cedrozor/myrtille#179]
Not sure if this an issue, most likely a question.
Is there any way to mark the session in RDS as a disconnect when the user will close the tab?
Right now it stays as active, I have a solution that disconnects the idle session, however, I would like to disconnect mark them as disconnect just after (or a minute after) user close the tab/window.

**Comment by cedrozor** [comment]
Yes, you can set the following key in web.config (disabled by default):
```
<!-- if the browser window/tab of the remote session owner is closed without disconnecting first, or if the connection is lost, delay (ms) before the remote session is disconnected by the gateway. 0 to disable -->
<add key="ClientIdleTimeout" value="60000"/>
```
But be warned that some people experienced a disconnect if the browser tab/window isn't active, because browsers freeze the execution of javascript code (thread) if the tab/window isn't active, and so the "heartbeat" (based on a `window.setInterval`) sent by the browser on a timely basis and used by the gateway to know that the tab/window is still alive.

I fixed that in the upcoming version (to be released soon), by moving the "heartbeat" into a web worker, which should be executed on a different thread than the UI main thread.

**Comment by cedrozor** [comment]
Myrtille 2.7.0 (new release) implements the said web worker. The client (browser) idle timeout is set at 30 secs (with a 10 secs based pulse). This comes in addition, but doesn't replace, the RDS idle timeout (=no user input) which should be set separately (20mn, for example).

Please tell me if it works as intended.

**Comment by cedrozor** [comment]
related to https://github.com/cedrozor/myrtille/issues/155. please reopen if needed.
