### ISSUE TITLE
xhr timeout (3000 ms). Please check your network connection

### ISSUE THREAD

**Issue by AnujKoundal** [cedrozor/myrtille#190]
Hi,
I have did setup using installer on my local system. When I run SSH protocol to run SSH commands it is giving me following error "xhr timeout (3000 ms). Please check your network connection". I am using windows 10 and .net 4.5. Only thing I am able to locate is "101 Switiching Protocols" in my browsers network tab. I am using latest version of Chrome and Firefox browsers.

![image](https://user-images.githubusercontent.com/11159545/70622845-d084ba00-1c42-11ea-9362-d517d5ddde34.png)

Please help to resolve this issue.

**Comment by cedrozor** [comment]
Can you click the "stats" button into the toolbar and provide a screenshot please?

**Comment by AnujKoundal** [comment]
Thanks for the quick reply, Here is the message after clicking the "stats" button:

![image](https://user-images.githubusercontent.com/11159545/70642397-24a09600-1c65-11ea-87cf-421b4523df96.png)

**Comment by cedrozor** [comment]
Did you enabled the websocket protocol on IIS ? If yes, there may be something (firewall, proxy, etc.) that blocks the websocket traffic.

Xmlhttp requests seem to work because the available bandwidth is well computed.  About the timeout, do you have more info into the browser devtools > network > xhr ? 

Can you try to disable HTML5 (toolbar button)?

**Comment by AnujKoundal** [comment]
Yes I have enabled websocket protocol on IIS.
![image](https://user-images.githubusercontent.com/11159545/70681952-403a8980-1cc3-11ea-9323-13d73e813b48.png)

Here is the info from devtools>network>xhr
![image](https://user-images.githubusercontent.com/11159545/70681974-51839600-1cc3-11ea-8e8e-3df52116a6d7.png)

I have already tried disable HTML5 button but it is not making any difference:
![image](https://user-images.githubusercontent.com/11159545/70681996-67915680-1cc3-11ea-8513-6b997282982e.png)

**Comment by cedrozor** [comment]
Can you check ssh.log ? (into the myrtille install path, log folder). Since you use a custom port for you SSH connection (tcp 20 instead of 22), I assume you did opened the ports, both on the myrtille machine (ssh client) and the ssh server.

Did you tried an RDP connection with myrtille ? does it work ?

**Comment by AnujKoundal** [comment]
Hi Thanks a lot, I have tried with port 22 and it is working fine. RDP is also working fine.
