### ISSUE TITLE
Myrtille init error: Config is not defined

### ISSUE THREAD

**Issue by gtmsew** [cedrozor/myrtille#191]
One of our client having this error every time he wants to log in. At the same time, there are around 20user that are connected to the server and connected and working without any issue, which makes me believe this is some issue on the client's side.
Any tips on what it can be, what we can check to troubleshoot and fix it for that user?

![image](https://user-images.githubusercontent.com/51693068/70692677-20ec2e00-1cbc-11ea-969e-94df337266a5.png)

**Comment by cedrozor** [comment]
Have your user open the browser devtools (ctrl+shift+i) and send you a screenshot of the console and network tabs. This is a javascript error, so there may be a problem loading some js files (http error code?).

You can also have your user to clear the browser cache, in case there is an issue around that (even if, since 2.7.x, myrtille appends an unique hashcode to the js files so that they are reloaded in case of changes).

**Comment by cedrozor** [comment]
Hi, any news?

**Comment by cedrozor** [comment]
Can I close this issue?
