### ISSUE TITLE
Any way to prevent/disable CTRL + [W] shortcut in the browser ?

### ISSUE THREAD

**Issue by deepakkataria0878** [cedrozor/myrtille#195]
Hi Team, 

I have installed Myrtille on my windows 10 machine, then connect by my browser. Can you please provide solution to prevent/disable CTRL + [W] to close the window. I want to just clear the word using ctrl+w shortcut.

Thanks in Adavnce

**Comment by cedrozor** [comment]
Hi, yes **ctrl + w**, like **alt + F4**, is a Windows shortcut to close the active window. Myrtille doesn't propagate the captured events but, unfortunately, some of them are intercepted first by Windows and there is nothing myrtille can do.

However, what myrtille can do is to detect if the tab or window is being closed (https://stackoverflow.com/questions/20853142/trying-to-detect-browser-close-event) and prompt the user whether to confirm or not such an action.

I'll do that into the next version, thanks for your input!

**Comment by cedrozor** [comment]
I tried to detect if the window/tab is being closed (using various methods found at stackoverflow).

Unfortunately the "beforeunload" event isn't reliable (it doesn't fire everytime, see https://dev.to/chromiumdev/sure-you-want-to-leavebrowser-beforeunload-event-4eg5), the dialog message is not customizable (displays a generic and confusing warning message) and, more importantly, the event fires even if the page is simply reloaded. This is a problem for myrtille because the page can be reloaded on several occasions.

This can even be considered as a bad practice to disturb the user with such a confirm dialog.

I tried to intercept ctrl +w, or alt +f4 with myrtille but, as explained before, it's not possible (the browser or OS does capture these events before myrtille can do, using javascript).

So, I'm afraid this is a dead end.  If you close the page by mistake, you can still use your browser history > "pages or tabs closed recently" to resume your session.
