### ISSUE TITLE
Keyboard layout under Myrtille 2.8.0

### ISSUE THREAD

**Issue by SeRom7640** [cedrozor/myrtille#200]
Hi Cedrozor,
My server is a Windows 2019 with 10 user RDP "USER CAL".
Connexion to Myrtille are always done by ONE user but my RDP configuration allows multiple logons for one user, so all people connecting to my "Brocante" booking software use the same user and thus use also only one CAL :).
When connecting to that user under the Windows tsclient, th keyboard is defined as "Belgian (dot)" and the layout of my belgian keyboard is correct.  Belgian Keyboard are AZERTY, French keyboard are also AZERTY but with some differences like : 
- @ : on belgian Keyboard press "Alt Gr" + é
         on french keyboard press "Alt Gr" + à
About 10 keys are différent between both keyboards

My problem is that when connecting to my brocante user under Myrtille, the keyboard layout is AZERTY FRENCH which is not defined under my tsclient normal RDP session.

So my question is : how can I align both sessions (Myrtille RdWEB and the normal Windows TSclient

this user has in fact very restricted rights to avoid piracy, but perhaps will it be possible to allows connected users to change the keyboard layout to match its real keyboard...  I don't know because when opening the session, explorer.exe is not launched, I replaced it in the user registry by my booking software.

**Comment by cedrozor** [comment]
> My problem is that when connecting to my brocante user under Myrtille, the keyboard layout is AZERTY FRENCH which is not defined under my tsclient normal RDP session.

Hi, this is because the connections are made by the myrtille gateway, which probably uses the French keyboard layout by default (while an rdp server uses the layout of the rdp client).

> So my question is : how can I align both sessions (Myrtille RdWEB and the normal Windows TSclient

You can have your users to align the (local and remote) layouts with the floating language toolbar: https://winaero.com/blog/get-the-old-language-indicator-and-language-bar-in-windows-10/

On the remote server:

![image](https://user-images.githubusercontent.com/17749498/74086726-08af4a00-4a86-11ea-8b0e-d93606283a54.png)

The users are able to change the remote keyboard layout:

![image](https://user-images.githubusercontent.com/17749498/74086749-5330c680-4a86-11ea-8f33-75753f20dfe2.png)

and they can do the same for their local keyboard:

![image](https://user-images.githubusercontent.com/17749498/74086772-8ecb9080-4a86-11ea-949b-0df7c2c99989.png)

> this user has in fact very restricted rights to avoid piracy, but perhaps will it be possible to allows connected users to change the keyboard layout to match its real keyboard... I don't know because when opening the session, explorer.exe is not launched, I replaced it in the user registry by my booking software.

If you want to run a custom program on session start (as an alternate shell to explorer.exe), you can also use the "[Auto-connect / Start remote application from URL](https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#auto-connect--start-remote-application-from-url)" feature of myrtille, instead of having it in the registry. But I concur it's also nice this way, because the user is forced into the application whatever the connection params and won't have access to the desktop.

**Comment by SeRom7640** [comment]
Hi Cedrozor,
Under Windows serveur 2019, the way you show above seems to not work because no more such windows are available.
But I found a registry keys wich force the keyboard layout to NOT change from the RDP Client.
With this key I am sure my keybord layout stays unchanged (AZERTY BELGIUM), So French customers may easily use the touche keybord to find the "@" for example.
The registry key can be modified by this way :
**REG ADD «HKLM\SYSTEM\CurrentControlSet\Control\Keyboard Layout» /v IgnoreRemoteKeyboardLayout /t REG_DWORD /d 1**

**Comment by cedrozor** [comment]
Ah Microsoft... there is surely a way to have the floating language bar to be displayed, it's quite handy. But yes, I forgot about this registry key (on the RDP server) to avoid the keyboard layout (for the RDP session) to be changed accordingly to the RDP client (the myrtille gateway). Thanks for that! :)

In fact, both this registry key (there should be a related GPO, to have it cleaner) and the floating language bar are relevant for your usage (and whenever a start program is used). You can also override the default input method, as you can see into the advanced settings screenshots.
