### ISSUE TITLE
Images in Myrtille Websites not displayed

### ISSUE THREAD

**Issue by RalphSester** [cedrozor/myrtille#201]
When I log into Myrtille (2.8 on W2K16) all images (Session-Logos, Myrtille-Logo) are not displayed.
When I trace the iis, I can see, that the png-Files are searched in a virtual URL which seems to be a child of the /myrtille Directory. This directory does not exist in real but the web-app is searching these files there...

What can I do, that this is working correctly ?

Thank you for your help.

Ralph

**Comment by cedrozor** [comment]
It may be a simple right access issue to the static content (js, css, images, etc). You can open your browser devtools (ctrl+shift+i), and check the network tab for the http codes returned for these resources.

Mytille 2.8.0 enables [static content](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/Myrtille.Web.Install.ps1#L18) on IIS. If it's not enabled (?), you can use your server manager  > roles and features to enable it.

If the static content is not physically on disk (?!) then it's another problem; but, in this case, the install process should had failed and you shouldn't even be able to access the myrtille homepage.

**Comment by RalphSester** [comment]
Thank you for your answer.
I have disabled the option for "Session URI". Now its working.
I don't know, why it's not working with the session URI. The IUSR_User has Read-Access in the physical directory....

**Comment by cedrozor** [comment]
Strange indeed; the [http session state](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/Web.Base.config#L93), mode="InProc" cookieless="UseUri" (which allows myrtille to use multiple connections/tabs) is normally handled automatically by IIS and .NET. Obvisously, an url like https://server/myrtille/S(kjkgfkfjjksjjsjjsjjhdhdhd)/ doesn't exists physically; but is mapped by IIS to https://server/myrtille/ and bound to the http session id "kjkgfkfjjksjjsjjsjjhdhdhd"

Do you have the "[IIS-ISAPIFilter](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/Myrtille.Web.Install.ps1#L18)" feature enabled on IIS? you can use your server manager > roles and features to check that.

I investigated a little more and found this: https://forums.asp.net/t/1107617.aspx?Problems+deploying+site+as+cookieless+

> After a call with Microsoft, we were able to come up with a resolution to the problem. The cookieless session ID that was created by .net was not being picked up by the aspnet_filter.dll (the ISAPI filter for IIS). This .dll was in a downed state which meant that the session ID could not be munged/unmunged by IIS. **This resulted in a 404 error** that was evident in the IIS logs as well as a partial page displayed on the production website.
> 
> Up until about Feb of '07, our web team's practice was to replicate the sites on the development server to the production server via a replication script that would, at a high level, copy the metabase over to the prod servers and find/replace any remnant of the original server. This successfully copied the IIS settings and sites to the other servers. **The aspnet_filter.dll uses an account that is located in the IIS_WPG group**. The root cause of the issue was that when we replicate this over, we also moved over accounts that manage .dll's used by IIS. The fix was to download a tool called Meta ACL from Microsoft and run a command to use the appropriate account for the respective server. Once this was done, the ISAPI filters were back online and able to successfully parse the session IDs.

Did you changed the default ACLs of some myrtille folders (static content for example?) that could prevent the IIS ISAPI filters to parse the http session ID when accessing these folders? If you want to set the ACLs manually, you should grant permissions to the myrtille application pool ("IIS AppPool\MyrtilleAppPool") instead of the IIS_IUSRS group. This is what is done by the installer to [allow the myrtille web application to write logs](https://github.com/cedrozor/myrtille/blob/8e5100ba880c9287502f79d42825ddfcca18d197/Myrtille.Web/src/WebInstaller.cs#L184) into the "log" folder.

But except if you really need it and understand the results, you shouldn't need to change the ACLs...

**Comment by RalphSester** [comment]
ok - i have changed back to URI config and gave the pool-identity read-access to the myrtille-directory. but no changes - still same problem. my isapi-filter is installed.

I changed now back to cookie config...this is working.

**Comment by cedrozor** [comment]
It's some configuration issue somewhere :/ if you don't need multiple connections/tabs, it's fine as is.

But that would be interesting to track down that issue. Did you checked the Windows application event logs? it's not something at the myrtille level; it's related to the way for IIS and .NET to pass the http session ID (instead of passing it into a cookie, it's passed into URL).

**Comment by RalphSester** [comment]
i have checked the application and the systemlog. there are no errors in the time while i have changed to session uri. perhaps my environment is nonstandard because my iis-server is an domaincontroller. perhaps there are some differences in security settings.

**Comment by cedrozor** [comment]
Do you have a reverse proxy that could interfere with the ISAPI filter (in charge of munging /unmunging the http session ID)? I found something about that: https://stackoverflow.com/questions/31430753/unable-to-create-asp-net-session-on-a-cookieless-web-application

More info about the ASP.NET session state and isapi filter modules: https://www.drdobbs.com/how-cookieless-sessions-work/184416901

If you didn't already, you could also have a look to the IIS logs (default `C:\inetpub\logs\LogFiles\W3SVC1`).

**Comment by RalphSester** [comment]
I don't use a reverse proxy for testing.

I have tested again.
in the iis log i can see following errors:

```
2020-02-09 17:50:15 192.168.0.100 GET /Myrtille/(S(131fsivcprfkkyi45d4uksn4))/img/RemoteSSH.png - 443 - 37.24.231.29 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/80.0.3987.87+Safari/537.36+Edg/80.0.361.48 https://www.anywhere.de/Myrtille/(S(131fsivcprfkkyi45d4uksn4))/ 404 0 2 3
2020-02-09 17:50:15 192.168.0.100 GET /Myrtille/(S(131fsivcprfkkyi45d4uksn4))/img/RemoteDesktop.png - 443 - 37.24.231.29 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/80.0.3987.87+Safari/537.36+Edg/80.0.361.48 https://www.anywhere.de/Myrtille/(S(131fsivcprfkkyi45d4uksn4))/ 404 0 2 2)
```
In the Systemlog of Windows i see an error:

Event ID: 10016 DCOM

```
Durch die Berechtigungseinstellungen für "Anwendungsspezifisch" wird dem Benutzer "IIS APPPOOL\MyrtilleAppPool" (SID: S-1-5-82-1877816451-2288598883-4273411821-1610741511-207314010) unter der Adresse "LocalHost (unter Verwendung von LRPC)" keine Berechtigung vom Typ "Lokal Aktivierung" für die COM-Serveranwendung mit der CLSID 
{D63B10C5-BB46-4990-A94F-E40B9D520160}
 und der APPID 

```

The listed AppID is the "RunTimeBroker" which i cannot edit the settings in Components-MMC and I don't want to change too....last time I changed something in the DCOM-Config I had to reinstall my machine.....

So i will you the cookie-config again....seems to work fine.
Thank you for your support!

**Comment by RalphSester** [comment]
I don't use a reverse proxy for testing.

I have tested again.
in the iis log i can see following errors:

```
2020-02-09 17:50:15 192.168.0.100 GET /Myrtille/(S(131fsivcprfkkyi45d4uksn4))/img/RemoteSSH.png - 443 - X.X.X.X Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/80.0.3987.87+Safari/537.36+Edg/80.0.361.48 https://www.anywhere.de/Myrtille/(S(131fsivcprfkkyi45d4uksn4))/ 404 0 2 3
2020-02-09 17:50:15 192.168.0.100 GET /Myrtille/(S(131fsivcprfkkyi45d4uksn4))/img/RemoteDesktop.png - 443 - X.X.X.X Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/80.0.3987.87+Safari/537.36+Edg/80.0.361.48 https://www.anywhere.de/Myrtille/(S(131fsivcprfkkyi45d4uksn4))/ 404 0 2 2)
```
In the Systemlog of Windows i see an error:

Event ID: 10016 DCOM

```
Durch die Berechtigungseinstellungen für "Anwendungsspezifisch" wird dem Benutzer "IIS APPPOOL\MyrtilleAppPool" (SID: S-1-5-82-1877816451-2288598883-4273411821-1610741511-207314010) unter der Adresse "LocalHost (unter Verwendung von LRPC)" keine Berechtigung vom Typ "Lokal Aktivierung" für die COM-Serveranwendung mit der CLSID 
{D63B10C5-BB46-4990-A94F-E40B9D520160}
 und der APPID 

```

The listed AppID is the "RunTimeBroker" which i cannot edit the settings in Components-MMC and I don't want to change too....last time I changed something in the DCOM-Config I had to reinstall my machine.....

So i will you the cookie-config again....seems to work fine.
Thank you for your support!

**Comment by cedrozor** [comment]
DCOM... yes better not change anything about that.

So you have something wrong somewhere into the IIS and ASP.NET modules pipeline. Maybe reinstall the related role and features could help. If you do, please tell me if that fixes the issue.

You are welcome :)
