### ISSUE TITLE
Migrate to ASP.NET Core 3.0

### ISSUE THREAD

**Issue by umar-ulabs** [cedrozor/myrtille#202]
Is it possible to migrate Myrtille.Web project to ASP.NET Core 3.0?

**Comment by cedrozor** [comment]
Sure, if someone want to help me on this task, or hire me to do it, because it's not a small one.

For now, I prefer to focus on stability, performance and features; but I understand it would bring Myrtille in the Linux world (and also make use of MVC patterns), so this would be something valuable. 

But it would not only require Myrtille.Web to be migrated; the myrtille FreeRDP fork would also need to use xfreerdp as rdp client under Linux, and continue to use wfreerdp under Windows.

**Comment by se** [comment]
Hi @cedrozor. I'm so happy to see this project. For this task, as a team, we want to help.

Let's start with the web project and converting current projects to netstandard. After that, we can convert wfreerdp to xfreerdp.

Starting from small steps will take us there ;-)

**Comment by cedrozor** [comment]
Hi @se, any help is welcome ! :) thank you
