### ISSUE TITLE
Remote Program not starting in Myrtille-2.8.0 for Windows server 2019

### ISSUE THREAD

**Issue by Panchraj** [cedrozor/myrtille#203]
Hi,
I have installed myrtille 2.8.0 using the setup.exe on windows server 2019. 
I am able to access my remote desktop from web browser that's amazing.
I want to use Myrtille to run a my desktop application on web browser so i entered the path of my desktop application in Program input box during login but it always opened the remote desktop instead of Remote Application.
Kindly suggest, am i missing anything or its an issue in this version ?

I have visited issue#27, issue#104 issue#106 but but nothing worked for me.

Thanking you.

**Comment by cedrozor** [comment]
Hi,

If the target is a Windows Server 2019, it should work but you have to allow the remote application to run, as explained into the [documentation](https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#auto-connect--start-remote-application-from-url).

Myrtille relies on the RDS role and features, so you have to configure your application as detailed here:
https://msfreaks.wordpress.com/2014/01/08/step-by-step-windows-2012-r2-remote-desktop-services-part-4/

If you want something more simple, you can allow to run any application by using a group policy (or local policy if you don't use a domain)

![image](https://user-images.githubusercontent.com/17749498/74090887-1cbc7100-4ab1-11ea-9c46-4e41cee7f731.png)

**Comment by Panchraj** [comment]
Hi,
I enabled the setting Remote start of unlisted programs but still its displaying remote desktop instead of  application. 
It seems that its an issue of FreeRDP(wfreerdp) that is used in Myrtille.
I tried to do the same using wfreerdp from command prompt but it displayed the black screen for few seconds and then disappeared.
I tried the same on Windows server 2016 but same issue there.
Is there any issue in current version of wfreerdp ?

**Comment by cedrozor** [comment]
Hi, did you re-checked the path of your application? if you have params and the path contains space(s), you have to use double quotes (i.e.: `"C:\Program Files (x86)\MyApp\MyApp.exe" /param1 / param2`). Even if you don't have any param, you can enclose your path with double quotes (behind the scene, the Windows command interpreter, cmd.exe, will execute your application; see https://github.com/cedrozor/myrtille/issues/197).

Also, if you use the "&program=" param into url, you have to [url encode](https://www.url-encode-decode.com/) the value.

You see a black screen with wfreerdp because it runs then it closes, probably because of some param(s) it doesn't like. You can [enable the wfreerdp logs](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/app.config#L210) to see what happens exactly,

I re-checked the 2.8.0 with a start program, it worked with both Windows Server 2016 and 2019.

**Comment by cedrozor** [comment]
Did you succeeded to run your application?

**Comment by andy22584** [comment]
Hi, I'm having the same issue. Just playing with it, this is the URL I'm trying to open cmd.exe
https://mydomain.com/myrtille/?__EVENTTARGET=&__EVENTARGUMENT=&server=myserver&domain=mydomain&user=user&password=password&program=C%3A%5CWindows%5CSystem32%5Ccmd.exe&width=width(px)[optional]&height=height(px)[optional]&connect=Connect%21

**Comment by cedrozor** [comment]
Hi, @Panchraj and @andy22584, any news on this issue? I wasnt able to replicate it on Windows Server 2019

**Comment by Panchraj** [comment]
It was resolved after reinstalling the Myrtille.
Thanks for your help.
