### ISSUE TITLE
connecting to a VM in standard mode - some keys are wrongly mapped or do not work.

### ISSUE THREAD

**Issue by TechReefer** [cedrozor/myrtille#204]
Many thanks for your work on this - it's the best solution I've found for accessing windows VMs from a web page and solves a number of problems with others I've tried (Guacamole, Admin Center, RDS html 5 etc). I have tried to fix this problem myself but really don't have the skills...

Myrtille Version: 2.7.1 (stable)
Issue: when connecting to a VM in standard mode (ie not using enhanced session mode) some keys do not match the keyboard or locale (UK in this case for all devices) or produce no output at all.
Example: The # symbol key (aka the number sign or hash).
Symptoms:
Pressing the # key produces no output at all in Firefox but a single quote in Chrome and Edge.
Pressing the \ key produces the # symbol in all 3 browsers.
Pressing shift + 3 produces the £ symbol in all 3 browsers (which is correct for UK). In other words the locale is being detected correctly.

When connecting to the same vm using enhanced mode the keys work as expected.
When connecting to the same vm using wfreerdp in either mode the keys work as expected. To keep everything as comparable as possible I did this by running myrtille.services.exe from a command prompt rather than the service, connected to the same vm from the browser and then tested in the wfreerdp window on the server.
Both the native Hyper-V vmconsole and standard RDP also work as expected.

Here's a link that shows a UK keyboard layout along with the scancodes: http://kbdlayout.info/KBDUK/scancodes . From there you can see that the keyboard scancode for the # symbol is code 2B / 43.

Thinking this might be a scancode problem I edited JsKeyCodeToRdpScanCodeMapping.cs and added these lines, commenting out the codes they replaced:

MapTable.Add(163, new RdpScanCode(43, false));          // uk # symbol
MapTable.Add(220, new RdpScanCode(86, false));          // uk \ symbol

This gave me the correct output for the # and \ symbols in Firefox but had no effect on Chrome and Edge - the # key still produced a single quote.

Using one of the js keyCode generators (eg https://keycode.info/ ) I found that Chrome sees the # key as 222 not 163. Changing that in JsKeyCodeToRdpScanCodeMapping.cs produced the right output in Chrome but not in Firefox.

I wondered if this could be related to what I think is the use of js KeyboardEvent.keyCode rather than KeyboardEvent.code see https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode. However, as this is the first time I've looked at c#, I could very well be misreading the keyboard related code. 

The reason you can't just always use enhanced mode is for those cases where it's not available - a vm that hasn't finished loading the OS yet or for which you want to select the boot device, Linux vms (without LIS), earlier Windows version vms, Windows safe mode etc. 

I looked at the changelog for 2.8 but don't think the changes would effect this issue. Thanks for any help you might be able to give with this issue.

**Comment by cedrozor** [comment]
Hi, thanks for your input. Indeed, having the right output on various browsers, different local, gateway and remote keyboard layouts & languages is quite challenging; especially with the RDP protocol and this additional difficulty of scancode for non character keys, extended or not, vs unicode for character keys.

I reworked recently (2.7.0+) the keyboard capture to differentiate left or right locations for keys like shift and alt (was useful to handle the Alt+Gr key correctly, https://github.com/cedrozor/myrtille/issues/92).

Some myrtille users switched everything (character keys or not) to scancodes (https://github.com/cedrozor/myrtille/issues/176), even if I'm not sure it's the best way to go; unicode is nice for that it's meant to work whatever the language, without needing a mapping table for each keyboard layout (!)

Anyway, I will rework this to support IME keyboards and composition events (https://developer.mozilla.org/en-US/docs/Mozilla/IME_handling_guide) instead of relying on the javascript key codes (no ETA! or this better be a sponsored development :p)

Waiting for that, you can also provide the user the ability to change the keyboard layout for the remote session and have it to match its local layout (https://github.com/cedrozor/myrtille/issues/200)

**Comment by TechReefer** [comment]
Thanks for your reply. I had read both those issues (#92 and #176) before posting but this is not a keyboard layout issue, or at least not in the same way...

Consider that all devices along the chain in this scenario have UK as the default (and only) keyboard layout. This is why, as I mentioned above, pressing shift + 3 produces the £ symbol in all 3 browsers and in both standard and enhanced session mode when connected to a vm. So, all keyboard layouts are the same in this case (local, gateway, host and vm). That also means it's not possible to workaround by adding a UK keyboard layout because it's already installed.

Also, consider that this issue _only_ occurs when connecting to a VM in standard mode. Connecting to the same VM with Myrtille using enhanced mode (or rdp) does not have the issue - the # symbol is produced correctly and there are no keyboard issues in either of those cases.

I did not understand why this should only happen when enhanced mode is not used but I now see in keyboard.js (Myrtille.Web/js/user/keyboard.js) these lines:
	// RDP over VM bus (Hyper-V): send keys as scancodes when enhanced mode is disabled
        if (!keyIsChar || modCtrl || modAlt || config.getVMNotEnhanced())

So I think, in my case, this issue is just about scancodes. Luckliy, it's only 3 or 4 keys that I would need to add/change in JsKeyCodeToRdpScanCodeMapping.cs which is easy enough for me to do.

Unfortunately that still leaves the problem of how to make it work across different browsers. The reason it does not work is because different browsers can return different numbers for the js keyCode number when some keys are pressed. This means that adding scancodes will fix one browser but create a problem in another browser.

I did some testing using https://w3c.github.io/uievents/tools/key-event-viewer.html to see what other js methods of reading keydown might be more consistent. The only one that seems to be consistent across browsers is event.key (as opposed to event.keycode). The returned value is text rather than a number so, as Myrtille uses event.keycode it is expecting a number so this is probably not much use :(

The only other way round I can think of is browser detection in  JsKeyCodeToRdpScanCodeMapping.cs so that I could switch the js keycode accordingly. I know how to do browser detection in js but not in c#. I tried a few examples but couldn't get them to work. Is there anything already in Myrtille that I could call from JsKeyCodeToRdpScanCodeMapping.cs ?

**Comment by cedrozor** [comment]
Nice tool https://w3c.github.io/uievents/tools/key-event-viewer.html :) you figured it, the whole keyboard capture is so complicated :/

Regarding the UI `event.key` (or `code`?) instead of the legacy `keyCode`, why not for sure; but in my experience, the latter worked well whatever the browser; but I didn't used an UK keyboard and an Hyper-V VM in standard mode. You can't use the enhanced mode because the target is a Linux box?

You could have the browser detection into the browser then send it as additional info into the `SendKeyScancode` command; the C# gateway doesn't know neither should care about the browser. See https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/js/display.js#L161 for some methods about browser detection, but you can surely find better (and even some libraries for that).

Another approach would be for `keyboard.js` to rely on `event.key` (or `code`?) instead of `keyCode;` but this will change many things into the gateway workflow and this should be reworked to use IME keyboards anyway (this is yet another API); so, yes, I think you are better with the above.

**Comment by wellloaded** [comment]
Similar issue for SSH, the very important [TAB] used in Linux to autofill commands maps instead into a comma (**,**)

**Comment by cedrozor** [comment]
the next version of Myrtille will include an on-screen virtual keyboard in case of any keyboard issue.
