### ISSUE TITLE
More than one users access to Myrtille with same account

### ISSUE THREAD

**Issue by vasu-senawongse** [cedrozor/myrtille#206]
1. According to using the URL access to myrtille remoteApp. I cannot make more than 1 user use the same account to access remoteApp at a moment. I don't want to create many account on my server to serve everybody. Anyway work around in this case? 

2. Moreover, in my last issue which I already mentioned that I want to use MS Word with remoteApp. I want the way to let user click the button and save that remoteApp MS Word. Because it is remoteApp window, so I don't know how to use access and control the window programmatically. I'm using React Typescript for Front-end and .Net Core C# for Back-end.

Appreciated :)

**Comment by cedrozor** [comment]
> According to using the URL access to myrtille remoteApp. I cannot make more than 1 user use the same account to access remoteApp at a moment. I don't want to create many account on my server to serve everybody. Anyway work around in this case?

You can allow multiple sessions per user, as explained into the documentation: https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#remote-desktop-services. In addition to have 1 account for everyone (and require only 1 CAL), it will also be easier to configure, secure and monitor.

By the way, if you didn't already, you should either [publish your application](https://newhelptech.wordpress.com/2017/07/23/step-by-step-how-to-deploy-remote-desktop-services-in-windows-server-2016/) (MS Word) as a remoteapp (into an RD session collection) or [allow any unlisted program](https://github.com/cedrozor/myrtille/issues/203) on the RD session host(s) (using a local or group policy, depending on your setup), in order to prevent any execution denial on session start.

> Moreover, in my last issue which I already mentioned that I want to use MS Word with remoteApp. I want the way to let user click the button and save that remoteApp MS Word. Because it is remoteApp window, so I don't know how to use access and control the window programmatically. I'm using React Typescript for Front-end and .Net Core C# for Back-end.

You won't be able to control it that way because first, there is no remoteapp window with myrtille.  Technically, myrtille is a gateway and doesn't have an UI. Instead, it runs the application as an alternate shell into the remote session and stream its content into the browser. The result is like remoteapp and even share the same technical stack (the application must be allowed as explained above).

If what you want is to save the user document before close, you have to proceed differently. You can hide the myrtille disconnect button into the toolbar so that the only way for the user to exit the application (and thus close the session) is to click the application's window close button or exit menu. If that occurs, the application should prompt the user whether to save or not any unsaved work before close.

**Comment by vasu-senawongse** [comment]
I already set the restrict single session to disable and set the limit connection to 999999. But I still kicked out from the App when other connection access to the App.

**Comment by cedrozor** [comment]
Which OS is the target server? last time I checked, there was a reconnect issue with Server 2019 (see https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#remote-desktop-services) but I didn't encountered any issue with multiple sessions per user. But that depends on the application used and the fact a same user could share the same data over different sessions.

Regarding the single session restriction, did you disabled it on the myrtille gateway? if yes, that would explain the problem. You need to disable it with a group policy if you have a domain or with a local policy on each RD session host otherwise.

About the RD licensing, you can _technically_ use 1 CAL for a same user, but you may also be in violation of the RD license terms (https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-client-access-license); it may be ok during the RD trial period but not after.

**Comment by vasu-senawongse** [comment]
I moved my server from Azure VM to other cloud VPS. I did everything same as before but getting this error.

The remote connection failed due to missing or invalid credentials

When I tried to get the hashpassword by the URL it keep changing everytime. Is this normal?
Why is this happening?

**Comment by vasu-senawongse** [comment]
Seems like more than 1 user can access same account but not in the same application. The scenario is that I have 15 questions of MS Word. If user A is doing Q.2 and B is doing Q.1, then it's fine. But if A doing Q.2 then B move from Q.1 to Q.2 then A will be disconnected.

**Comment by cedrozor** [comment]
This is possibly related to the application. I think that MS Word puts a file lock on disk for the opened document (like Open Office, for example) and the fact it's related to the same user account must disturb it.

Do you use a local or roaming (domain) user account? (https://community.spiceworks.com/topic/2152482-microsoft-word-is-not-working-for-one-user). It might be some configuration issue; you could try to set a different working folder  for each remote session (https://social.technet.microsoft.com/Forums/en-US/32aa46f9-4c6d-4e02-8d31-e981a596428f/remote-desktop-services-user-profile-and-home-folder?forum=winserverTS)

During various tests, I didn't had that issue with many other applications. The definitive solution would be to use different user accounts...

**Comment by vasu-senawongse** [comment]
I solved it by separate each user folder.

> If what you want is to save the user document before close, you have to proceed differently. You can hide (or disable) the disconnect button into the myrtille toolbar so that the only way for the user to exit the application (and thus close the session) is to click the application's close button or exit menu. If that occurs, the application should prompt the user whether to save or not any unsaved work before close.

Can you guide me through what you mentioned? How can I make a button to execute close function and embeded to myrtille tool bar?

**Comment by vasu-senawongse** [comment]
Can I get the ID of each remote session process or close the program immediately when user left the page? I have some problems because files still opened after users left.

**Comment by cedrozor** [comment]
You can set a small disconnection timeout (i.e: 1 sec) so that a session is closed (signed out) just after being disconnected (https://serverfault.com/questions/873399/rds-2016-session-limits).

If you want to control that more accurately, you can use the RDS API (through the Cassia wrapper) to logoff your sessions, as Myrtille does to drain the disconnected sessions with connection broker(s) in HA mode (https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/RemoteSessionProcess.cs#L67)

**Comment by vasu-senawongse** [comment]
I will try your solution. Can I send KeyStroke through an app opened by Myrtille?

**Comment by cedrozor** [comment]
You can send keystrokes yes, as it's done for the "Keyboard" popup (https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/js/myrtille.js#L509), but it wil be sent to the remote session; your application must be focused to receive it (which should be the case if the application is run at startup).

**Comment by vasu-senawongse** [comment]
Where can I use this sending keystrokes function? Is it available in toolbar or how can I call it?

**Comment by cedrozor** [comment]
It's a javascript function, so you call from the DOM. Have a look to the "Ctrl+Alt+Del" button and the code behind it, then you should be able to implement a "Ctrl+S" button.

**Comment by vasu-senawongse** [comment]
Okay, I'm coming up with the new solution. I want to edit the toolbar, get rid of the collapsed bullet and all of the button. Then, I will add one new button with the Ctrl+S to save and close the connection. Can I do that? Where can I adjust the toolbar and its CSS.

By the way, I want to thank you again for this software and your help from the beginning. I know I might annoyed you sometime. I owe you a lot.

**Comment by cedrozor** [comment]
You can do many things if you know what you are doing ;) but the simplest is always best, so I would advise to use myrtille within an iframe into your website. The only thing is both must be on the same domain to avoid cross domain restriction.
