### ISSUE TITLE
opening a new windows browser on the client side

### ISSUE THREAD

**Issue by SeRom7640** [cedrozor/myrtille#208]
Hi cedrozor.
when putting data to the clipboard, I can paste it on the client side.
But I would like to launch a new window browser on the client side when the data contained in the clipboard is an URL.

Is it possible or will it be possible in the future ?

I need this for my "Brocante booking application" to execute the payment process on the client side (I think this will be more "Ethic" to let the customer making the payment on his side) and I need this on a NEW window (and not a new TAB) to avoid the user close the browser before my program has detected the completion of the payment.
And I prefer to do that automatically to avoid copy-paste manipulation by the user.

Actually, If I put an URL in the clipboard, your "copy box" appears and the copy action must be done manually...  If it is not possible to do that automatically, perhaps will it be possible to add a customizable button close to the "copy" and "close" button, and the click on this button will launch a new browser window on the client side

**Comment by cedrozor** [comment]
> when putting data to the clipboard, I can paste it on the client side.
> But I would like to launch a new window browser on the client side when the data contained in the clipboard is an URL.

Hi, I understand your need but I can't implement such a behavior into myrtille. It's too specific and even intrusive (not "ethic" at all).

> Actually, If I put an URL in the clipboard, your "copy box" appears and the copy action must be done manually... If it is not possible to do that automatically, perhaps will it be possible to add a customizable button close to the "copy" and "close" button, and the click on this button will launch a new browser window on the client side

This popup is because the clipboard API is not available on the browser; myrtille can't copy the remote clipboard content into the local clipboard and needs a manual action from the user.

You need Chrome, https and grant myrtille access to the clipboard in order to have a seamless clipboard sync (https://github.com/cedrozor/myrtille#requirements). If you deny myrtille access to the clipboard, you won't be ever prompted again and you will have to open the Chrome settings for the myrtille page to change your initial choice.

To get back to your requirement, you can change the code on remote clipboard copy event (https://github.com/cedrozor/myrtille/blob/83539e311b840067848e676a2df95b3fb7d4f539/Myrtille.Web/js/myrtille.js#L476) to check for an URL and open a new window if that occurs.

**Comment by SeRom7640** [comment]
OK, thanks, I'll try this but the software is now in production, so I'll do that a bit later.
