### ISSUE TITLE
Mark Server as in Use

### ISSUE THREAD

**Issue by schporto** [cedrozor/myrtille#211]
I have a way on the client to limit RDP session to 1.  Is there anyway we could add a badge or change the icon of the session icons to indicate the session is in use?  Something like this
![myrtille-badge](https://user-images.githubusercontent.com/14842823/76346982-3d5c2e80-62dc-11ea-89fa-b6aaef0f50a2.png)

**Comment by cedrozor** [comment]
There is no way for myrtille, with FreeRDP as RDP client, to know how many concurrent sessions are allowed by the RDP server. Also, AFAIK, there is no special exit code returned by FreeRDP to indicate that a connection was rejected because the maximum number of concurrent sessions was reached.

However, it's possible to use the RDS API (with [Cassia](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/RemoteSessionProcess.cs#L84) as C# wrapper) to retrieve [the number of active sessions on an RDP server](https://docs.microsoft.com/en-us/windows/win32/api/wtsapi32/nf-wtsapi32-wtsenumeratesessionsa), then display it over the connection icon (in a bullet for example).

I can dig this for a future version.

**Comment by cedrozor** [comment]
This could be done as a custom development (please contact me for a quote). Closed for now.
