### ISSUE TITLE
 Printing in rdp-session leads to two print jobs in the "Myrtille PDF"-printer at the gateway

### ISSUE THREAD

**Issue by andrups** [cedrozor/myrtille#213]
We just installed Myrtille 2.8. on a Windows Server 2016 Standard. Using Google Chrome 80 on a Windows 10 client, we successfull start a RDP-session using the Myrtille-gateway (Myrtille.Web-website).

When printing a document (for example from notepad), two print jobs are created (with different names) in the "Myrtille PDF"-printer at the gateway: first a blank document and a second one containing the expected document. In the printer queue of the RDP-client (linked printer) is only one print job created as expected. It seams that the customized version of FreeRDP included in the setup creates two print jobs. Is this a known issue and how can this be fixed? Any help is much appreciated.

Chears,
Andreas

**Comment by cedrozor** [comment]
Hi, thanks for your report. No, it's not normal and maybe a side effect after FreeRDP was resynced to the latest code base. I will investigate.

**Comment by andrups** [comment]
Hi, is there any news about this problem?

**Comment by cedrozor** [comment]
Hi, no; it's not a blocking issue, so I didn't prioritized it. But it was noted

**Comment by cedrozor** [comment]
I wasn't able to replicate this issue

First, are you talking about print jobs or printer names? because there are indeed 2 "Myrtille PDF" printers:

- "Myrtille PDF". This printer is installed on the Myrtille gateway; it's usable locally to create PDFs (without Myrtille) if you need to
- "Myrtille PDF (redirected xxx"). This is the same printer, but redirected through and usable into the RDP session

The print workflow is as following:

Using the Myrtille PDF redirected printer:

![image](https://user-images.githubusercontent.com/17749498/93713378-c2fa4a00-fb5b-11ea-8aa9-47dfb6c13fc1.png)

The print job into the remote session:

![image](https://user-images.githubusercontent.com/17749498/93713383-d2799300-fb5b-11ea-990d-bd1129797424.png)

The print job on the Myrtille gateway:

![image](https://user-images.githubusercontent.com/17749498/93713411-f63cd900-fb5b-11ea-8479-1aa8bc04b3b7.png)

The print job into the browser:

![image](https://user-images.githubusercontent.com/17749498/93713431-23898700-fb5c-11ea-82cf-58575e4b44c8.png)

**Comment by andrups** [comment]
There have been two print jobs (first one a blank page, second one the expected document). As it turned out later, this behaveor occured on our testsystem only. In the meantime we’ve gone in production with our setup an in these conditions the pdf printer works as expected.

 

So if you can’t reproduce this issue, I think you can close thise case – maybe there was „someting special“ in the used Windows-installation.

 

Thank you for checking this issue and all the time you invest in this project!

 

Andrups

 

Von: cedrozor [mailto:notifications@github.com] 
Gesendet: Sonntag, 20. September 2020 16:28
An: cedrozor/myrtille
Cc: andrups; Author
Betreff: Re: [cedrozor/myrtille] Printing in rdp-session leads to two print jobs in the "Myrtille PDF"-printer at the gateway (#213)

 

I wasn't able to replicate this issue

First, are you talking about print jobs or printer names? because there are indeed 2 "Myrtille PDF" printers:

*	"Myrtille PDF". This printer is installed on the Myrtille gateway; it's usable locally to create PDFs (without Myrtille) if you need to
*	"Myrtille PDF (redirected xxx"). This is the same printer, but redirected through and usable into the RDP session

The print workflow is as following:

Using the Myrtille PDF redirected printer:

 <https://user-images.githubusercontent.com/17749498/93713378-c2fa4a00-fb5b-11ea-8aa9-47dfb6c13fc1.png> image

The print job into the remote session:

 <https://user-images.githubusercontent.com/17749498/93713383-d2799300-fb5b-11ea-990d-bd1129797424.png> image

The print job on the Myrtille gateway:

 <https://user-images.githubusercontent.com/17749498/93713411-f63cd900-fb5b-11ea-8479-1aa8bc04b3b7.png> image

The print job into the browser:

 <https://user-images.githubusercontent.com/17749498/93713431-23898700-fb5c-11ea-82cf-58575e4b44c8.png> image
