### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by camjcorley** [cedrozor/myrtille#220]
Hello, I'm not sure why but I can't get sound to work. I've tried MP3 and WAV on both the official release and a release built from source. I'm testing on a Windows 10 and a Windows Server 2016 machine. The Windows 10 test is using a local user; the Windows 2016 is a domain user. In both cases I have a valid SSL certificate and am connecting via HTTPS. I've tested connecting to both from a Windows 10 machine using Firefox and a Windows 10 VM using Firefox and Chrome.

There aren't any errors in the logs or browser console/network calls. I added some console logging to the audiowebsocket.js file and verified that init() and open() are successful while message(), error(), close(), and receive() aren't called during a connection. I've also verified that Myrtille.Services is sending the appropriate settings to FreeRDP in the RemoteSessionProcess.cs StartProcess() method.

I'm not quite sure in what direction to dig next while troubleshooting this, hoping to get some guidance.

**Comment by cedrozor** [comment]
Hi, did you enabled audio into the remote session? also, because this is server to client audio redirection, the rdp client (FreeRDP) must be able to play it; which means, the machine running Myrtille must have an audio card, either physical or virtual (if it's a VM).

It doesn't really make sense in fact, because FreeRDP is not supposed to play the audio stream on the Myrtille gateway (the stream is just forwarded and decoded/played by the browser), but that's how it works in FreeRDP, probably because it relies on the Windows audio API.

For the same reason and because I wasn't able to change the Docker VM settings, I couldn't get the audio redirection or printing with Myrtille running as a container (Windows containers, at least). If anyone has an idea about this, I am listening!

**Comment by camjcorley** [comment]
I did some additional digging and can provide the following additional info:

- All machines I am testing are VMs. Some are in MS Azure and others are on VMWare. I have tested once _from_ my local physical computer just to be safe (no dice).
- The issue occurs both when attempting to connect 'through' the Myrtille gateway to a target machine or directly to the Myrtille gateway server (server: localhost).
- The "Remote Audio" device shows up while connected in any of the configurations I tested (win10 -> win10, server->win10, etc.). 
- I confirmed that sound works when connected via mstsc.exe (Microsoft's built-in RDP client). 
- In one configuration the Myrtille gateway OS did not have the Windows Audio service running. I rectified this and ensured that audio was redirected when connecting directly via mstsc.exe. However, the issue persists.
- I haven't tried running inside of a container but can confirm that printing is working without issue for me.

Thanks!

**Comment by cedrozor** [comment]
Can you try to add the (VMWare or Hyper-V) guest tools to the Myrtille VM?

**Comment by cedrozor** [comment]
A Myrtille user provided me with the solution. That's what I thought, the VM running Myrtille must have a virtual sound card for wfreerdp to be able to process the audio stream. I could not find the equivalent for Hyper-V (I will re-check later), but please find below the settings for VMWare:

Here are the parameters to apply to the .vmx file:
```
sound.present = "true"
sound.allowGuestConnectionControl = "false"
sound.virtualDev = "hdaudio"
sound.fileName = "-1"
sound.autodetect = "true"
sound.pciSlotNumber = "34"
```

**Comment by cedrozor** [comment]
Hi @camjcorley, did this helped ?

**Comment by camjcorley** [comment]
Hey cedrozor, sorry for the delay. Unfortunately I had to shutdown the VMWare host I was using for testing and am only testing in Azure at this point. However, I do have an update.

I connected directly via the wfreerdp.exe that's packaged with the Myrtille release build and had sound without an issue:
`.\wfreerdp.exe /v:10.0.0.5 /sound /u:cjadmin /p:[omitted]`

I'm playing around with the initialization of the process arguments now in the Myrtille.Services.RemoteSessionProcess.cs file now but am not having much luck. I think the next stop would be the Myrtille fork of wfreerdp to see what's going on but unfortunately I don't have much experience with C++.

**Comment by camjcorley** [comment]
Another update. I've spent this whole time thinking to myself that I could have sworn I tested sound when I first came across Myrtille and that I would've noticed if there was an issue. I just did some testing and confirmed that sound worked without issue on version 2.7.1 with default settings (just install, no configuration). After that release I have this issue.

**Comment by camjcorley** [comment]
I was able to resolve the issue with sound by extracting the following files from the 2.7.1 release binaries and copying over an installation of 2.8.1:
* freerdp-client2.dll
* wfreerdp.exe

I left the following files intact:
* freerdp2.dll
* winpr2.dll
* winpr-tools2.dll

I'm uncertain what the implications of this change are but am going to check out your FreeRDP fork to see if I can tell the commit it started after.

**Comment by cedrozor** [comment]
Hi @camjcorley, thanks for your investigation! So it looks like a regression into FreeRDP :/ it's surprising that it requires a sound card when it was not the case in the past. I wasn't sure, but this confirms that I remember having Myrtille in a VM with a sound that worked.

There have been many changes in FreeRDP between Myrtille 2.7.1. and 2.8.0, simply replacing certain DLLs is hazardous. But this is interesting, because it restricts the search between the common rdp client code and the windows client.

I will resync the FreeRDP fork in the next version of Myrtille and see if the problem persists. If you can take a look too, any help is greatly appreciated! :)

**Comment by camjcorley** [comment]
Happy to help! I'm not terribly familiar with C++ (or compiling the code for that matter). I was finally able to get a build on the 2.7.0 and 2.8.0 releases of your fork of FreeRDP and their functionality matched my results so far. Sound on 2.8.0 and no sound on 2.7.0.

My next plan was to start checking out verified commits between 2.7.0 and 2.8.0 to see if I can find where the issue starts. However, when I build one ([Merge pull request f89d1d4](https://github.com/cedrozor/FreeRDP/tree/f89d1d42ae88bc72e597f5da278b3bbf65ccf074) for example) it doesn't work when plugged into my installation of Myrtille. Is there a step I'm missing that occurs between the verified commits and releases? Thanks!

**Comment by cedrozor** [comment]
Did you used cmake to prepare the build projects ? you also need openssl (for example [Win32 OpenSSL v1.1.1g](https://slproweb.com/download/Win32OpenSSL-1_1_1g.msi)). Then you can enable the FreeRDP logs into `Myrtille.Services.exe.config` or even extended logs as explained here : https://github.com/cedrozor/myrtille/issues/156#issuecomment-505554971. 

But the best would be to debug through Visual Studio C++ because there are some arguments which are not passed through command line, such as the target server and user credentials. This is for security reasons, in order to avoid being able to retrieve these informations from the process command line.

I set tags on the FreeRDP fork when I release an new version of Myrtille, so you can focus on commits between 2.7.0 and 2.8.0 (and you can see there were a lot !). I will also have a look as soon as possible.

Thanks again !

**Comment by cedrozor** [comment]
Hi @camjcorley , did you found something relevant about this regression?

**Comment by camjcorley** [comment]
Hey @cedrozor, other than further confirming my previous findings I have been unable to determine which commit caused this issue to first appear. I have also been going through a few code sprints at work recently and have not had as much time as I was hoping to dig into this.

**Comment by clusteruk** [comment]
@cedrozor 
Hi, can I ask if this issue is resolved please, we are running 2.8.1 of Myrtille.
My Myrtille setup running from a Windows 10 Home machine works fine with audio, but on our production 2019 server we get no audio in the browser. However the audio is active and the audio works if us manually using wfreeRDP.exe directly.

**Comment by cedrozor** [comment]
Hi, this problem only happens when Myrtille is installed on a VM which doesn't have a (virtual) sound card. The current workaround is to add one, as explained before in this thread.

I didn't had the time lately to resync FreeRDP with the latest code, maybe this issue was fixed since. I will try to re-prioritize this and resync FreeRDP in the next version of Myrtille.

Which DLLs state 2.8.1 after you upgraded to 2.9.0? this may be the MSI engine which see no change beside the version number, and should not prevent Myrtille to work, but this is not the expected behavior.

**Comment by cedrozor** [comment]
On the other hand, I noticed a regression on the audio. After a limited time (between 40 secs and 1mn), the audio no longer works. This may be due to the fact that the audio websocket only receives data and does not send data (no microphone support with Myrtille) and the browser would therefore take the initiative to close the websocket, which it considers inactive.

If so, it may be a recent update to the websocket protocol. In any case this does not affect the display, whose websocket uses a "keep-alive" with a frequency of 10 seconds. The solution in this case would be to also have such a "keep-alive" on the audio websocket. I would look at this for a future version of Myrtille.

**Comment by ccameron-ntap** [comment]
Hey @cedrozor, thanks for following up on this issue! I haven't had a chance to test out the latest version and will do so next week. I'll also try playing around with some alternate virtual sound card options. By the description, @clusteruk is experiencing the same situation as myself.

**Comment by clusteruk** [comment]
Hi, the virtual sound card addition solved my problem. I was confused because it had sound available through wfreeRdp so I assumed it was available. After checking with the VM hosting team it was clear no Virtual sound card was applied and mine was just redirected sound which the Myrtille system does not use.
Thanks @cedrozor for the quick resolution.
Steve

**Comment by ccameron-ntap** [comment]
@clusteruk that's what threw me off as well. Can you share which virtual sound card solution you went with?

**Comment by clusteruk** [comment]
@ccameron-ntap We have our own hosting house and they just set a default one, nothing special but I would need to email them to ask what VM software and sound card.

**Comment by ccameron-ntap** [comment]
Thanks @clusteruk! In the meantime, @cedrozor do you have any recommendations for this?

**Comment by cedrozor** [comment]
@camjcorley this depends on the virtualization software used to run the Myrtille VM:
- VMWare: as detailed upper in this thread, see http://virtualvillage.cloud/?p=546
- Hyper-V: https://www.quora.com/Why-doesnt-Hyper-V-support-audio
- VirtualBox: https://www.youtube.com/watch?v=tjWKnDVQOuA
- ProxMox: https://forum.proxmox.com/threads/sound-on-windows-guest-vm.34419/

In a future version of Myrtille, I will try to remove the need for a sound card on the Myrtille gateway. This is a bit tricky because the RDP audio output virtual channel is created only if the RDP client (wfreerdp.exe) runs on a machine with a sound card (either virtual, physical or RDP redirected). What Myrtille does actually is send the remote audio output to the audio websocket instead of the sound card.

@clusteruk the same thing goes for remote audio input in the other way

**Comment by camjcorley** [comment]
Thanks @cedrozor !
