### ISSUE TITLE
myrtille init error: Can't find variable: XmlHttp

### ISSUE THREAD

**Issue by serridavide** [cedrozor/myrtille#230]
Hello,
I am using myrtille on a remote touchscreen panel with a browser which i haven't got access to his settings. With an online tool i found out it has Safari for Ubuntu installed on it. I used myrtille on a docker container with an external network to connect my panel to a ubuntu VM installed on my computer. 
all was working fine with this link:
[http://DockerContainerExternalSwitch/Myrtille/?__EVENTTARGET=&__EVENTARGUMENT=&server=myServerIp&user=davide&passwordHash=hereihavethecorrecthash&connect=Connect%21](url)
 
After the installation of a Windows Server machine in my office I decided to move Myrtille onto the server and install it directly with the newest version 2.9.0 . After i adapted the link to have the server address and the relative passwordHash, i tried to connect once again to my ubuntu machine. From my laptop on the latest chrome everything works fine. But if i try to connect from my remote Panel i get 2 message errors one after the other:

> myrtille init error: Can't find variable: XmlHttp

and

> failed to start myrtille: Can't find variable: XmlHttp

if I connect to regular myrtille page and insert manually the information about VM Ip user and password i manage to connect just fine, but I really need to be able to connect from a direct link.

I tried to explore the file and even change the config to avoid XHR setting it to WEBSOCKET but the error still remain. I would gladly accept some help on this matter since i'm not sure if this is a coding bug or some setup error, which seems strange since last version on docker was working great..

![WhatsApp Image 2020-10-06 at 17 42 34](https://user-images.githubusercontent.com/72458567/95224790-635a9a80-07fb-11eb-94f2-305d07cd89e4.jpeg)
![WhatsApp Image 2020-10-06 at 17 42 34 (1)](https://user-images.githubusercontent.com/72458567/95224795-648bc780-07fb-11eb-9adb-e92f0bd155c7.jpeg)
![WhatsApp Image 2020-10-06 at 17 42 34 (2)](https://user-images.githubusercontent.com/72458567/95224799-66558b00-07fb-11eb-9e66-18d7e15a4ab8.jpeg)

**Comment by cedrozor** [comment]
Hi, looks like a javascript issue. Do you have the ability to show the devtools console on your Safari ?

What did changed in 2.9.0 is the use of a cdn for the on-screen keyboard (https://cdn.jsdelivr.net/npm/interactjs/dist/interact.min.js). If your Ubuntu machine doesn't have access to it, the on-screen keyboard won't work; it shouln't impact the rest of Myrtille, but it's possible.

**Comment by serridavide** [comment]
Unfortunately I'm not able to access the devtools console, it is an embedded and locked up system which only makes available the web browser url to access a single app or website. This is also the reason why I use myrtille, so i can have a full on operative system on that panel. Is the docker version exactly the same as the windows version? could it be that the issue came out switching from docker to windows app instead of upgrading from 2.8 to 2.9?

**Comment by serridavide** [comment]
Quick update: 
I just tried installing myrtille 2.8 on my computer without docker, tested it and all is working fine. So apparently the issue is indeed in upgrading to 2.9

**Comment by cedrozor** [comment]
Yes, and this is probably related to the use of a cdn (nodejs), with the new international on-screen keyboard in 2.9.0. Your panel may not have internet access, so it can't access https://cdn.jsdelivr.net/npm/interactjs/dist/interact.min.js, and this prevents loading the others javascript files, as a side effect.

I must say I was a bit lazy on this one because I didn't embedded`interact.js` into Myrtille, as opposed to all the others 3rd party libraries, thus breaking the ability of Myrtille to work in a closed environment (with no internet access). I will do that in the next version. Meanwhile, you can download [interact.js]( https://cdn.jsdelivr.net/npm/interactjs/dist/interact.min.js) and all its dependencies (and that's where nodejs is nasty) and change the related <script> tags into `Default.aspx` and `popups\OnScreenKeyboard.aspx`.

Docker has nothing to do with this issue, this is the same code as the installable version (btw I have to update the latest myrtille image to 2.9.0). A question however: did the external network you defined for the myrtille container had   internet access? in which case, you should use the same network for the installed myrtille version.

**Comment by serridavide** [comment]
Thanks for the explanation, the panel should have internet access, it is possible however that the internal system has some protection over the network thus blocking it, unfortunately i'm not able to verify that... as of now we will continue as usual with version 2.8.0. Whenever a new release is available I will try it and keep you updated on the behaviour of the panel.

**Comment by cedrozor** [comment]
It's a little detail. You can fix it by changing the following line (into the Myrtille install folder ("C:\Program Files (x86)\Myrtille" by default):

    js/network/xmlhttp.js: line 238
    js/network/eventsource.js: line 91
    js/network/websocket.js:line 299

Replace: `catch` by `catch (exc)`

**Comment by cedrozor** [comment]
updated release 2.9.1
