### ISSUE TITLE
myrtille initDisplay error: Display is not defined

### ISSUE THREAD

**Issue by ggnoplay** [cedrozor/myrtille#235]
Hello,

I tried using Myrtille over a work pc and I get the error in the title. The issue is the same one as https://github.com/cedrozor/myrtille/issues/138 . Only difference is I have checked if Static Content is installed or not. It's already installed. So I'm assuming the issue is due to the heavily managed browser permissions and limitations.

Can you add a field to overcome the issue such as entering "Display resolution" field somewhere so I can provide the info that Myrtille is not able to.

**Comment by cedrozor** [comment]
Hi, you should check your browser devtools (Ctrl+Shift+I), console tab, to see what is the problem exactly. It's suprising the browser can't even retrieve its own resolution.

You can either:
- change the width and height input fields to be of "text" type instead of "hidden", so you can provide their values manually (https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/Default.aspx#L85)
- connect Myrtille from URL, passing the values of "&width=" and "&height=" into querystring (https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#auto-connect--start-remote-application-from-url)

**Comment by cedrozor** [comment]
You can also add a drop down list with common screen resolutions (https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide) into the login page and let the user select one. Please re-open if needed.

**Comment by ggnoplay** [comment]
Hello.

I have been using your solution of using Syntax login method. However browser started giving "too many redirection" error.

Then I tried using changing hidden into text in Default.aspx. But now server gives following.

Parser Error Message: The base class includes the field 'width', but its type (System.Web.UI.HtmlControls.HtmlInputHidden) is not compatible with the type of control (System.Web.UI.HtmlControls.HtmlInputText).
