### ISSUE TITLE
Myrtille init error: can't find variable URL

### ISSUE THREAD

**Issue by fabian-at-fit** [cedrozor/myrtille#244]
Hello,

since Myrtille 2.7 I am having issues with launching the Webclient on older Platforms. in Internet Explorer (checked with Version 8) i have Javascript errors (various "expected Identifier" and "the object does not support this action") and the page doesn't load at all. Wenn I try with Zebra Enterprise Browser on my Windows CE based embedded Devices (WebKit Engine), the page loads but throws "Myrtille init error: can't find variable URL" with successively less functionality working the higher the myrtille Version is. e.g. in 2.8 i get video but input isn't working, in 2.9 I don't get anything at all, just more myrtille init error messages. Recent Versions of Firefox work fine (but cannot be deployed were I need the Web Client).

**Comment by cedrozor** [comment]
Hi, thanks for you report. It becomes more an more difficult to ensure a proper support of IE, but I understand the need and it was even a particularity of Myrtille to support the old IE and HTML4 browsers.

I confess having reduced the tests with my IE 6/7/8/9/10 VMs lately (looks like since Myrtille 2.7.1); I thought no one was using IE anymore, but I was wrong!

I'll take a look at it in future versions.

**Comment by cedrozor** [comment]
This is normally fixed into the version 2.9.1
