### ISSUE TITLE
Is it possible to connect Azure Windows Virtual Desktop using myrtille?

### ISSUE THREAD

**Issue by umeshpatil12** [cedrozor/myrtille#248]
I have connected to a Virtual Machine using myrtille. I want to connect Azure Windows Virtual Desktop using myrtille.  Is this possible?

**Comment by cedrozor** [comment]
If the Azure machine is an Hyper-V VM, you can connect it with Myrtille by using the "RDP over VM bus" protocol and specifying the VM GUID. Otherwise, the virtual desktop will need to have remote access (RDP) enabled or have the RDSH (Remote Desktop Session Host) role feature enabled so that Myrtille (FreeRDP more precisely) can connect it.

Alos think to open the related ports accordingly (RDP: tcp 3389, RDP over VM bus: tcp 2179 and SSH, if you need it: tcp 22).

**Comment by cedrozor** [comment]
I hope I replied to your question; please re-open otherwise.
