### ISSUE TITLE
Need Multiple Instance of RDP connection

### ISSUE THREAD

**Issue by vinu693693** [cedrozor/myrtille#25]
Hi, This tool is great and very much helpful for simply deploying a machine over RDP that too through browser. But while using it I found a limitation with this tool is that we can only open one RDP session at a timeon HTTPS; even if we try to open a second session to a difference machine it just shows you the first session. Could you please provide an ability to multiple instance of RDP over HTTPS? on HTTP it works fine. 

thank you very much
Vinayak

**Comment by cedrozor** [comment]
Hi, this is because myrtille uses an http session on the gateway to maintain a correlation with an rdp session. It should be possible to replace the session cookie, client side, by a simple session id which would be send on each request, and have the server to restore the associated context.

This is already how an http session works, with the difference that it's done automatically by the browser. When you open a new tab and browse to myrtille, the browser retrieves the cookie (associated with the url domain) then send it to the http server; the .NET framework is then able to restore the http context.

The result is having the same rdp session displayed in a new tab.

Currently, you can avoid that by using another browser (if you have Chrome and Firefox by example). You can also try to disable the cookies support on your browser, but I'm not sure it will be enough, as the session id will then be passed into the URL instead of being stored in a cookie.

You said it's work fine with HTTP, but I don't think it behaves differently than HTTPS.

I will investigate that.

**Comment by vinu693693** [comment]
My Bad. At one point it seemed like working. Yes, you are correct. Either over HTTP or HTTPS i am not able to load two different machines over different tabs. 
Workaround of using a different browser is working; but expectation is to make use of the same browser but different tab. Thanks for your help.
