### ISSUE TITLE
Allow Clipboard direct sync when myrtille is used in iFrame

### ISSUE THREAD

**Issue by sabyasachi-basu-i** [cedrozor/myrtille#253]
Dear @cedrozor ,

I was trying to sync the clipboard automatically to parent when Myrtille is open in an iFrame in that page. It shows the default clipboard popup unlike auto syncing the clipboard (when opened directly)

Is there anything I can do to add that auto sync behavior. I already added the Site Settings for Clipboard (in Chrome) to Allow for the Parent site.

Thank you in advance.

Regards,
Sabyasachi Basu

**Comment by cedrozor** [comment]
The clipboard auto-sync requires Myrtille to be accessed in `https` and the user must allow clipboard access when prompted. These settings can be changed afterward for the site or defined by default into the browser.

Afaik, an iframe should inherits from the page settings or, if the page doesn't access the clipboard, prompt the user for clipboard access. Both the page and iframe should be accessed in `https` and be on the same domain (cross domain restrictions apply otherwise, unless you defined CORS rules).
