### ISSUE TITLE
The term 'Get-WebBinding' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by nerodark** [cedrozor/myrtille#255]
When installing Myrtille 2.9.1 I am getting this error log

Path          : 
Online        : True
RestartNeeded : True

Enabled IIS, WebSocket protocol, management console and tools

Path          : 
Online        : True
RestartNeeded : True

Enabled .NET extensibility

Path          : 
Online        : True
RestartNeeded : True

Enabled WCF/HTTP activation

Created Myrtille self-signed certificate
The term 'Get-WebBinding' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by cedrozor** [comment]
[Get-WebBindings](https://docs.microsoft.com/en-us/powershell/module/webadminstration/get-webbinding?view=winserver2012-ps) depends on the [WebAdministration](https://docs.microsoft.com/en-us/powershell/module/webadminstration/?view=winserver2012-ps) module. It's surprising this module isn't registered on the machine since all the related components are enabled (if not already) by [this line](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/Myrtille.Web.Install.ps1#L18). That said, ` Import-Module WebAdministration` should have been placed before the `Get-WebBinding` call (just before the self-signed certificate code block).

What is the operating system of the machine on which you are installing Myrtille? I didn't had this issue on a fresh Win10, Server 2016 and Server 2019.

What you can do is to uncheck the "install SSL certificate" checkbox into the installer; it won't enter the faulty code block and you will be able to install Myrtille. You can create a self-signed certificate afterward, or install a trusted one, by using the IIS management console.

**Comment by cedrozor** [comment]
Might be related to https://github.com/cedrozor/myrtille/pull/274 on Server 2012

**Comment by cedrozor** [comment]
Fixed in [Myrtille 2.9.2](https://github.com/cedrozor/myrtille/releases/tag/v2.9.2)
