### ISSUE TITLE
Seems not too suitable for 3d games

### ISSUE THREAD

**Issue by yoyomule** [cedrozor/myrtille#259]
Hello, we have conducted preliminary tests in the local area network and found that when testing 3d game software, the interaction is relatively stuck, the delay is high, and there may even be a situation where the button cannot be closed (directly in the windows RDP client is no problem ), but other ordinary applications are okay. Is myrtille suitable for such application scenarios.

**Comment by cedrozor** [comment]
Hi, no Myrtille is not suitable for 3D games or videos. The RDP protocol itself is not really designed for such use, and Blueberry uses images (PNG, JPG, WEBP) to update the display which is efficient and lightweight for most applications, but not optimal for games or videos.

That said, there is room for improvement for Myrtille as the latter could use an H264 GPU accelerated video stream instead of images, which should translate to better performance.

**Comment by sabyasachi-basu-i** [comment]
@cedrozor , I want to take this task as an Improvement. Can we add to planner, if ok?

**Comment by cedrozor** [comment]
@sabyasachi-basu-i it's much more complicated than changing the UI, but if you want to give it a try, please go ahead :)

**Comment by sabyasachi-basu-i** [comment]
@cedrozor oh I know. I actually already started my research. I need to understand and work on the session you're rendering in your FreeRDP code. I want to take a stab at it.

But, this will also help us with the Audio rendering issues as well, I suppose.

Thank you!!
