### ISSUE TITLE
Need VNC support

### ISSUE THREAD

**Issue by vinu693693** [cedrozor/myrtille#26]
Can i also get a VNC support such that i get to see linux host from browser?

thanks in advance
VinU

**Comment by cedrozor** [comment]
Myrtille is currently supporting RDP only but is architectured it so that it's possible to extend this limitation. 

The RDP support is ensured by a FreeRDP fork (https://github.com/cedrozor/FreeRDP), modified for myrtille needs.  The myrtille C++ code into FreeRDP is clearly tagged and separated, as most of possible, from the FreeRDP code.

So, one just need to get a VNC client and report the myrtille C++ code into it, then improve the Myrtille.Services/RemoteSessionProcess.cs code a bit to make it running the VNC client instead of RDP (by adding a protocol select dropdown into the UI, for example).

The gateway and javascript code won't need any changes (they are manipulating PNG/JPEG/WEBP images, so they don't care of the remote desktop protocol used behind.

I don't have the time to do it. If someone does, it would be a nice way to collaborate to the project.

**Comment by aMASKed** [comment]
Thank you for your quick answer.
I have adapted RemoteSessionProcess.cs, so, the program starts well and connects to the server wanted, but I did'nt have retransmission on the internet browser. So now I have to adapt the Myrtille C++ code in the FreeRDP fork right ?

I will have to rebuild it ? Which part of the code is the Myrtille C++code ?

**Comment by cedrozor** [comment]
Yes, the myrtille code into the FreeRDP fork is surrounded by blocks:

> #pragma region Myrtille
> ...
> #pragma endregion

Basically, you have to report the same logic into the vnc client (tigerVNC, libNVC, etc):
- connect the remote session inputs & updates pipes
- loop the inputs pipe (forward the user events, process the commands, etc)
- encode the display updates (into PNG, JPG, WEBP, etc) and write them into the updates pipe

As the code is C++, most of it is portable. Then cmake for build.

**Comment by aMASKed** [comment]
So I have to get an VNC client with it's source to modify it like your freerdp fork and then get an executable compatible with Myrtille needs ? 
Sorry to insist, but the FreeRDP fork containt more than hundred files, and I don't use an IDE to edit it but a simple Notepad :p Which is the file who containe the myrtille code ? 

Thank you so much

**Comment by cedrozor** [comment]
Ugh, notepad is not the right tool for this... you need a full IDE (Visual Studio, Eclipse, etc.).

Best would be to use VS2015 if you want the same IDE as I used with FreeRDP (and thus be able to use comparable build settings). TigerVNC uses minGW, but libVNC seems to have some MSVC support.

Most of the myrtille code is into:
https://github.com/cedrozor/FreeRDP/blob/master/client/Windows/wf_myrtille.h
https://github.com/cedrozor/FreeRDP/blob/master/client/Windows/wf_myrtille.cpp

Please also note that there may be some licence issues; some licenses don't mix well together (myrtille is licensed under Apache 2.0 whereas libVNC and TigerVNC are under GNU GPL v2.0). In any case, you would need to obtain an agreement from the original authors (an so do I, if the modified vnc client is part of an official myrtille release).

**Comment by aMASKed** [comment]
Ok thank you much,
I'll see that.

**Comment by cedrozor** [comment]
Closing this for now. Please reopen if any progress :)

**Comment by jpickerell** [comment]
I am not a programmer so I can't help here at all, but just wanted to add that if anyone did ever want to take on adding VNC support to Myrle, I'd be interested in supporting that effort!

I use the UltraVNC server in the school districts that I work with, along with using the NTLM/MS Logon v2 authentication option along with the SecureVNCPlugin DSM plugin (for encrypted connections).

Jared
