### ISSUE TITLE
screen resizing issue

### ISSUE THREAD

**Issue by mayuraitavadekar** [cedrozor/myrtille#262]
If I minimize my browser screen and log in to remote session, and after login if I maximize the browser screen, the session remains at same height and width which was before login. If I click to SCALE ON, screen size becomes larger but maintains aspect ratio. i.e. height becomes 100% but not width. @cedrozor how can I change it so that it will take full height and width of current available screen.

**Comment by cedrozor** [comment]
Into config.js, you can tweak many Myrtille settings. The ones you need are:

```
var defaultResize = browserResizeEnum.NONE;   // default action on browser resize (RDP host only)
var keepAspectRatio = true;                   // if scaling the display, preservation of the aspect ratio
```

Instead of `NONE`, you can set the default resize to `SCALE` or `RECONNECT` (for the latter, caution if the target host is a Windows Server 2019... it may not work, see [documentation](https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#remote-desktop-services).

If you scale the display, you can choose not to keep the aspect ratio by having `var keepAspectRatio = false`;
