### ISSUE TITLE
Disconnect After Logout

### ISSUE THREAD

**Issue by MTBEnthusiast** [cedrozor/myrtille#27]
Hi,

I start the RDP session according to "Start program from URL # 21" ( the hiding of the status line has already been discussed and should be implemented in the next release).
A program is automatically started with the user.
If I leave the started program, the logout should be done automatically (Windows function) and the RDP session should be terminated (Myrtille function, possibly the Explorer window should be closed).
Instead, the session is left open and the Explorer window is "white".

Can the automatic disconnect be implemented after a logout?

Kind regards
Rolf

**Comment by cedrozor** [comment]
Hi Rolf,

There are 2 ways to start a remote application using RDP (see http://stackoverflow.com/questions/1226772/can-rdp-clients-launch-remote-applications-and-not-desktops):
- Alternate shell
- RemoteApp

RemoteApp is supported from Windows Server 2008, and use sub-optimal settings for myrtille (such as start the program into a window instead of fullscreen and redraw the whole window when it's moved), so I preferred the alternate shell option.

In both cases, it should logoff the session when the application is closed.

What program are you starting? maybe it has a different exit code that the one expected by the RDP layer (see http://superuser.com/questions/455954/logging-out-of-an-rdp-session-with-some-program-other-than-explorer-exe-as-the-s).

If that is, maybe the RemoteApp option would work (so I should autodetect, or at least provide the ability to change the start mode).

**Comment by MTBEnthusiast** [comment]
Hi Cedric,

I define to the user a startup program (login), which works:
-	Shortcut on the desktop (URL)
-	Opens the browser 
-	myrtille remote desktop is running 
-	automatic login
-	starts the program
-	user stops the program
-	automatic logout
-	automatic disconnect
-	Browser remains open and myrtille home page is displayed

The idea is that when disconnect the page is closed (only “start with remote application from URL”).

c:\windows\system32\cmd.exe does not start with the &program parameter, or I do not know the syntax.

Kind regards
Rolf

**Comment by cedrozor** [comment]
Ah, I had misunderstood. You meant the browser isn't closed after disconnect? this is the expected behavior (returning to the home page). 

In my opinion, closing the browser - if the application was started from an URL - introduces a specific behavior that complexifies the session handling logic and may be confusing to the end user.

Also, if the browser was already running (with some tabs opened) prior to double-clicking the shortcut, the end user won't be happy to see it closed (and it won't happen anyway, as javascript allows to close the current window/tab only).

Speaking about session handling and tabs, I will update the session handling logic in the next release (by the end of the month) so that it will be possible to have multiple different sessions in different tabs (https://github.com/cedrozor/myrtille/issues/25).

But your idea is interesting and it would not be so hard to close the current tab instead of redirecting to the home page given a start program is set; I'm curious to have people opinion about it; could you please post and link this issue to the [myrtille forum](https://groups.google.com/forum/#!forum/myrtille_rdp)?
