### ISSUE TITLE
Uncaught ReferenceError: interact is not defined

### ISSUE THREAD

**Issue by pwadkar** [cedrozor/myrtille#278]
Hello Team,

I have been receiving Uncaught ReferenceError: interact is not defined when I am trying to connect to the Host which I have created.

1. I installed the windows version from https://github.com/cedrozor/myrtille/releases
2. I kept it very simple added Host IP, username, and password 
3. Clicked on Connect then Blank page in Developer inspect I see the attached exception, the response status code I see is (200 Forbidden).

Appreciate if you help me with this issue.

Regards,
Prakash

**Comment by cedrozor** [comment]
Hi, yes I used an external CDN for interact.js (https://cdn.jsdelivr.net/npm/interactjs/dist/interact.min.js) instead of embedding the dependency into Myrtille (which I normally do); you probably have a restriction on your network which prevent you from accessing this url.

This is the same issue as https://github.com/cedrozor/myrtille/issues/230

I will see to embed this library into a next version of Myrtille.

**Comment by pwadkar** [comment]
Will check it today and see if this URL is being blocked or not. Is there a contact to talk more about integrating myrtille docker version with you?

**Comment by cedrozor** [comment]
Fixed into [Myrtille 2.9.2](https://github.com/cedrozor/myrtille/releases/tag/v2.9.2)

Duplicate of #282
