### ISSUE TITLE
Error 503

### ISSUE THREAD

**Issue by FabienNaslin** [cedrozor/myrtille#332]
Hello Cedric,

I tried to install on 2 different servers (win 2019) Myrtille and each time I get a 503 error. Did I forget something?

The application is well launched on IIS, thanks

**Comment by cedrozor** [comment]
Hi Fabien,

HTTP 503 is "service unavailable" (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503), does Myrtille works from the server itself? (https://localhost/Myrtille). If there was an error during install (often due to limited user privileges), you can find out what exactly by having a look to the install logs (`Myrtille install path\logs`)
