### ISSUE TITLE
End support for old browsers

### ISSUE THREAD

**Issue by pablo-martinez** [cedrozor/myrtille#34]
Supporting old browsers like IE6 was perhaps a nice feature to have back in 2010 when HTML 5 features were not implemented consistently by the majority of browser vendors at that time.
But we're now in 2017 and the story has changed: Microsoft [does not support](https://support.microsoft.com/en-us/help/17454/lifecycle-support-policy-faq-internet-explorer) such old browsers (the post is from 1 year ago), and I think Myrtille should not either.

Today, WebSockets is supported by [more than 92%](http://caniuse.com/#feat=websockets) of browsers, including iOS and Android. It does not make sense anymore to fallback to ajax if it means a security threat for end users.

On the other hand, this is an example of comments in .js files (config.js):
```
// about properties, starting from IE9 it's possible to define getters and setters... but these scripts are intended to work from IE6...
// so, going old school...
```
I think it is time for this code to evolve and take advantage of newer ECMAScript syntax, and also by focusing only on WebSockets, we can get rid of .aspx files and it will be easier to add new functionality, such as audio.

Thoughts?

**Comment by MTBEnthusiast** [comment]
This is exactly one function I need. I create SCADA systems with a very, very long life (guarantee period is 10 years!).
It would be as good as # 28 to test the possible functions.

**Comment by cedrozor** [comment]
This is indeed debatable because many people or companies still use old browsers (ok, maybe few are still on IE6). This is because browsers were modified for specific needs or embedded within applications.

It's true that modern browsers do have websockets support but, at the nework level, many proxies, reverse proxies, firewall, or whatever network related are filtering or blocking them. This is often due to the fact these websockets don't use the standard http(s) 80(443) ports because their websocket servers were developped before all the W3C specs and upgrade mechanisms were ready (like myrtille, which use Fleck - btw this is going to change very soon as i'm replacing it with IIS8+ websockets ... tests in progress).

So I think it's interesting to keep a backward compatibility for these people which are still using old browsers and such network cases. I even found that long polling, used along with xhr (for the user inputs), does behave better than websockets under the load (playing some videos for example).

And such ability to work under all scenarios is also a myrtille strength :)

I tought about using jQuery (and some other javascript libs) for an higher abstraction level and avoid the (boring) cross browsers/versions issues; SignalR (for .NET) can even abstract the transport layer and make use of the best one (it also have a fallback mechanism in case one isn't available or doesn't work) but I'd rather stay on vanilla javascript for (also debatable) reasons:
- myrtille was coded prior to most of these libs and I didn't wanted and/or had time to rewrite all (after all, they are just wrappers for the same things and myrtille works well enough).
- I like to know how things work (too many people tend to rely on libs and forget what is behind). I don't mean (neither like) to reinvent the wheel but, at least for an open source project, i think it's interesting.
- I wanted something as optimized as possible (not bloated by things I don't know or don't have the hands on). The best responsiveness and lowest traffic footprint always were on top of my priorities.

That said, I stay open to every suggestion and you have a very good point! ;) I'm curious to have more feedback on this, could you please post it to the [forum](https://groups.google.com/forum/#!forum/myrtille_rdp) Pablo? thanks! :)

**Comment by cedrozor** [comment]
Well, I'm not closed to newest ECMAScript either...

In the latest version (currently in test), I removed Fleck and added IIS8+ websockets support . I also moving to binary websockets to remove the base64 overhead and allow direct draw to canvas.

**Comment by Fancy-Boy** [comment]
There is no old browser support I think.
But There maybe a forward proxy between client and myrtille. And maybe forward proxy does not support websocket. Upgrading browser is easy, but upgrading proxy is not easy.

**Comment by cedrozor** [comment]
Hi, thanks but I'm not sure to understand :p could you develop your proxy idea?
