### ISSUE TITLE
Do you use the RFB protocol ?

### ISSUE THREAD

**Issue by aMASKed** [cedrozor/myrtille#42]
Hello cedrozor,

I would like to add VNC (and why not putty) support to Myrtille. First, I saw that you start freeRDP process with some arguments on the serveur. 
Just to make a test, I had remplaced wfreerdp.exe by the native MS RDP client (works with the same arguments that FreeRDP).
The process start, but any retransmition in web browser. 
So to help me, I would like to know if you using the RFB protocol to do that.
Last thing I saw that you had make a modification to the freeRDP work for Myrtille needs: what was it done ? 

Thank you

**Comment by cedrozor** [comment]
Hi, no but it's very close in the principle : send user inputs (keyboard, mouse) and receive display updates.

The FreeRDP fork handles just that: the user inputs are forwarded through the rdp session and the display updates are encoded into PNG, JPEG or WEBP format then sent to the browser through an http gateway.

Instead of an RDP client, a VNC client could do the same. The gateway would not change (neither the js code) and the freerdp process would only need to be replaced by the vnc one.

**Comment by cedrozor** [comment]
Linked to #26 :)
