### ISSUE TITLE
Using a wrapper instead of FreeRDP fork

### ISSUE THREAD

**Issue by SieldP** [cedrozor/myrtille#44]
Hello cedrozor,
I use Myrtille every day since 3 months and I thought about the process of myrtille last week. What do you think about if we use an process wrapping a .exe application and sending frames to Myrtille.WEB ?
Porcessing like that, we can extend the limitation of Myrtille: RDP only. Then we can upload any application (SSH, VNC etc.) like OpenVNS ALS.
Do you think that is possible ?

Thank ++

**Comment by cedrozor** [comment]
Hi, yes for sure I already thought about it... mostly when I upgraded myrtille from FreeRDP 0.8.2 to the latest version last year... the code was quite different (FreeRDP was almost entirely rewritten), no longer C++ (pure C) and the build params fully handled by cmake... so I spent much time and efforts to find the good entry points to report, adapt and refactor the myrtille code.

The result was nice however as it allowed myrtille to benefit from the latest FreeRDP features and bugfixes; and the fork could now (normally) be resynchronized with the FreeRDP master or stable branch.

As you said, such wrapper could extend the RDP protocol limitation, but it would also (mostly!) avoid having to modify the FreeRDP code.  The wrapper would have to hook the user input devices (keyboard, mouse, etc.) and display rendering (hardware or software) and act as a middleware between the myrtille gateway (Myrtille.Web) and the protocol client (RDP, VNC, SSH, etc.).

That is, tricking FreeRDP so that it would take its inputs from the wrapper and draw its updates into a display context owned by the wrapper.

The gateway would have to send the inputs to the wrapper (instead of FreeRDP currently) and receive the updates from it (named pipes could still be used for that purpose).

But it's not that so simple and I'm afraid it goes beyond my programming skills :/ there could also be some performance consideration (as its adds a layer), but I think it would be worth it.

I would be grateful to have some help if such wrapper is possible and considered.

Thanks :)

**Comment by SieldP** [comment]
Thank for reply, and sorry for this late..

I think that will be verry difficult for me too: I am a french student in 3rd year of engineering school.. And if it goes beyond your programming skills: what do you think about mine ? ^^

But I find that Myrtille is very interesting and deserves to be improved: I really want to do that for an school project.

I'm just afraid on one point: launching a hidden process as your freeRDP fork currently,  I'm not sure that it can return a frams from the window..

I will try and at the end, if I succeed, I'll send you all.

Thank ++

**Comment by cedrozor** [comment]
Did you succeeded with this wrapper idea we were speaking about?

Myrtille 1.5.0 (out and stable) went through an heavy refactoring; many things were improved (mostly simplified as much as possible, following design patterns).

The hidden FreeRDP (fork) is windowless but it works at bitmap level (not frame) so this is not a problem.
