### ISSUE TITLE
all static resource get 404

### ISSUE THREAD

**Issue by ruiruige** [cedrozor/myrtille#51]
- installed IIS
- installed myrtille.exe
- installed vc++ 2015 x64

Then I enter `http://127.0.0.1/myrtille/`, it automaticlly become `https://127.0.0.1/myrtille/(S(jmibphorygjzmgoh3zyua0ai))/Default.aspx`, seems adding a `(S(yqcche5kb2x22w1g4j3qo1jm))` in the url

Then I open the developer tool of Chrome, I found it has an `302` redirect, and then all the static resources' urls are all added with a  `(S(yqcche5kb2x22w1g4j3qo1jm))`

For example:
https://127.0.0.1/myrtille/(S(yqcche5kb2x22w1g4j3qo1jm))/js/myrtille.js
I remove the strange text in the url:
https://127.0.0.1/myrtille/js/myrtille.js, then I can access the js file.

the image is blow:
![image](https://user-images.githubusercontent.com/8370100/27865182-26f1a416-61c4-11e7-802e-b38cb58ae15f.png)

**Comment by ruiruige** [comment]
By the way:
Under the condiction of the fact that all static file are 404, I still tried to enter the IP ,username ,password

It seems it worked because my old remote desktop said "another user has logged in , so quit"
But I have no idea why static files are 404

**Comment by cedrozor** [comment]
The strange text "(S(jmibphorygjzmgoh3zyua0ai))" into the url is the http session id and shouldn't be removed.

It's usually transparent for the end user because it's stored into a transient cookie bound to the website domain then added to the requests http headers. 

But in order to allow myrtille working in cookieless mode and with multiple sessions/tabs, it has to be added to the url.

The 404 with the session id and static resources must be related to an issue with ASP.NET. The installer should normally download and install it, if not already installed on the machine, but there may be some extra configuration steps.

Have a look at follow : [https://stackoverflow.com/questions/6425442/http-error-404-3-not-found-in-iis-7-5/8487214#8487214](url). Also try to register ASP.NET against IIS using the aspnet_regiis.exe -ir command.

**Comment by cedrozor** [comment]
Any progress on this?

**Comment by ruiruige** [comment]
@cedrozor I checked my IIS， and found asp.net was not enabled. After enabled, it is OK. And I really like this because it does not depend on websocket. Thanks a lot
