### ISSUE TITLE
Does myrtille support RemoteFX?

### ISSUE THREAD

**Issue by philrykoff** [cedrozor/myrtille#52]
Well, that's the question :-)

**Comment by cedrozor** [comment]
Hi,

FreeRDP (the rdp client used by myrtille) does support it but I didn't extended it to myrtille because I wanted to keep things as simple as possible (and, usually, when you connect a remote machine, it isn't to play a video, music or a game :p).

It was also because at the time the first PoC of myrtille was developped (10 years ago), HTML5 wasn't ready yet (no websocket, canvas, video streaming, etc.) and we wanted no plugin (ActiveX, Flash, Sliverlight, etc.) nor extension. Also because some hardware (host side rendering through GPU virtualization) are usually not available on VMs and USB redirection has little meaning with a browser.

It would be a nice addition anyway to myrtille if someone is interested to work on it :)
