### ISSUE TITLE
What Port Do I Open

### ISSUE THREAD

**Issue by NotHexon** [cedrozor/myrtille#58]
What port do I open to connect to my myrtille gateway server from outside my lan?

**Comment by cedrozor** [comment]
You need to open the standard HTTP (tcp 80) / HTTPS (tcp 443) ports, or redirect custom ports, on your NAT and forward them the myrtille gateway (same ports).

If IIS (on the myrtille gateway) is bound to another ports, use them instead of 80 / 443.

If you have a reverse proxy, additional configuration may apply.
