### ISSUE TITLE
How to auto connect

### ISSUE THREAD

**Issue by noetius** [cedrozor/myrtille#59]
I can't understand what is the correct URL syntax in order to establish an auto connection, if it is possible.

**Comment by cedrozor** [comment]
Yes, it's possible; syntax documentation can be found here : https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#start-remote-application-from-url

If you want to run a specific application upon auto-connection, you have to set the "**&program=**" param with the executable file path and name.

As the querystring must be url encoded, you have to use a tool like http://www.url-encode-decode.com/ for all params, then copy & paste the result into the url.

For example, to run

> C:\Program Files\MyApp\AppName.exe -with -some -params

the url param is

> &program=C%3A%5CProgram+Files%5CMyApp%5CAppName.exe+-with+-some+-params

If your user password is

> Hello!

the url param is

> &password=Hello%21

You can also hash the password for more security if you wish (https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#password-hash), but it's not mandatory.

Related issues :
https://github.com/cedrozor/myrtille/issues/41
https://github.com/cedrozor/myrtille/issues/53

**Comment by noetius** [comment]
Hello @cedrozor, thanks for your reply and this great project, well I've found out that if you don't set width and height, client avoids auto connect, or auto login in other words, even if every credential is set, and after other checks, I have also noticed that there is no window self-resizing feature because my use case applies to an iframe that should show the client's content within a web page. 

We can state that for the time being, it is always necessary to set width and height within the url to avoid visualization and authentication issues.

But in fact this also applies to browser use, and it is really strange that I must to set width and height even if I want to simply load that url in the browser with auto login, and I must click the connect button in order to open the session. I don't know if it is an expected behaviour or a bug.

**Comment by cedrozor** [comment]
Strange indeed, it's not the expected behavior. If you dont set width and height, it should be auto-detected from the browser window.

I didn't tested myrtille within an iframe, it may require some tweaking:
- make sure the parent window (browser page) is on the same domain to avoid cross domain restriction
- the [javascript code which auto-detects the resolution](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/Default.aspx#L181), when starting a program from url, applies to the current window (the iframe), not the parent (the browser page).

About clicking the connect button, it's not normal; did you added it to the url? (&connect=Connect%21). It's required.

**Comment by cedrozor** [comment]
Thanks to an user feedback, and after doing some additional testing with version 1.5.0, I noticed that the "**&program=**" param must be added to the to the url for the auto-connect feature to work.

This is a regression and is tagged for fix. I will update the documentation which flag this param as optional.

If you don't want a program to be run on session start, leave the param empty ("&program="); otherwise , set its path\name (i.e.: "&program=notepad.exe").

**Comment by cedrozor** [comment]
Any progress on this?

**Comment by cedrozor** [comment]
Fixed into myrtille 1.6.0 (to be released soon)
