### ISSUE TITLE
Anyone get this working on Windows 2012?

### ISSUE THREAD

**Issue by tmakaro** [cedrozor/myrtille#6]
Has anyone got this working on Windows 2012?
I installed this on my Windows 2012 server and tried accessing it from my Windows 10 desktop using chrome. I got the web page for logging in but then get an error 1006 during the connection.  Perhaps I am filling in the screen incorrectly?

**Comment by cedrozor** [comment]
Error 1006 can apply to different things. I assume you are getting it from a windows event log?
I made some research and found these links:
https://technet.microsoft.com/en-us/library/ee891040(v=ws.10).aspx
https://technet.microsoft.com/en-us/library/cc727283.aspx
http://lokna.no/?p=1063
http://clintboessen.blogspot.fr/2011/01/microsoft-windows-grouppolicy-event-id.html

From them, it appears it could be due to a group policy issue, more specifically a problem between the RD Session Host server and the domain controller (do you use a domain controller?).

Could you enable the myrtille logs? (select "debug enabled" from the connection settings). Then, after the connection failed, you may get more details into the myrtille logs folder, wfreerdp_xxxx.log file.

**Comment by tmakaro** [comment]
Here is the error I am getting in the logs:

2016-07-25 13:00:40,244 [11] ERROR System.Diagnostics redirection [(null)] - Failed to wait for connection on images pipe, remote session 2 (System.ObjectDisposedException: Cannot access a closed pipe.
   at System.IO.Pipes.NamedPipeServerStream.CheckConnectOperationsServer()
   at System.IO.Pipes.NamedPipeServerStream.EndWaitForConnection(IAsyncResult asyncResult)
   at Myrtille.Web.RemoteSessionPipes.ImagesPipeConnected(IAsyncResult e))

2016-07-25 13:00:30,899 [17] INFO  System.Diagnostics redirection [(null)] - Started rdp client process, remote session 1
2016-07-25 13:00:31,586 [17] INFO  System.Diagnostics redirection [(null)] - Stopped rdp client process, remote session 1
2016-07-25 13:00:40,025 [6] INFO  System.Diagnostics redirection [(null)] - Started rdp client process, remote session 2
2016-07-25 13:00:40,244 [18] INFO  System.Diagnostics redirection [(null)] - Stopped rdp client process, remote session 2

**Comment by cedrozor** [comment]
These are the logs into Myrtille.Services.log. It shows that the rdp client (freerdp) starts and stops almost immediately. Can you please have a look to the FreeRDP.wfreerdp.xxxx.log? (the rdp client logs)

Did you tried to connect the rdp server using the Microsoft windows client (mstsc.exe)? is it working?

Regarding the domain controller and GPOs, did you checked that the problem is not as described [here](http://lokna.no/?p=1063) ?

**Comment by tmakaro** [comment]
There is no  FreeRDP.wfreerdp.xxxx.log that I can find. I searched all of drive c:  :(
FYI, mstsc does work fine to the server.

**Comment by cedrozor** [comment]
Most likely, the rdp client (freerdp) doesn't event start (which is another issue). Could you please try to run FreeRDP.wfreerdp.exe manually, located into the myrtille bin folder? it may be missing DLLs, you will have a popup window in this case indicating the missing assembly.

Did you installed the Microsoft Visual C++ 2015 redistributables? it's a prerequisite, as listed into the documentation, https://github.com/cedrozor/myrtille/wiki/requirements.

If you installed them, perhaps it didn't worked. On Windows Server 2012 specifically, there is a reported issue (http://stackoverflow.com/questions/31536606/while-installing-vc-redist-x64-exe-getting-error-failed-to-configure-per-machi). So, please try to fully update your OS (using windows updates) before installing the redistributables again.

**Comment by tmakaro** [comment]
Thanks, I'll give it a try later on today.

**Comment by cedrozor** [comment]
You can find more details about this issue related to the Microsoft Windows Universal C Runtime on Windows Server 2012 (basically equivalent to Windows 8.1) at http://stackoverflow.com/questions/31536606/while-installing-vc-redist-x64-exe-getting-error-failed-to-configure-per-machi/38222104#38222104.

In brief, if you don't want or can't update your OS, you need at least to install the **KB2999226** (https://support.microsoft.com/en-us/kb/2999226). you can install it manually, if you wish. Check the prerequisites (https://support.microsoft.com/en-us/kb/2999226#bookmark-prerequisites).

**Comment by tmakaro** [comment]
I got it working. It required the Microsoft Visual C++ 2015 redistributables which I didn't have installed.

It is falling back to long polling though. Any way to find out why it is not using web sockets? I have web sockets installed on iis.

Hey, if I can get this working on my IPAD with websockets then I would like to contribute. I am a c# web developer. I mainly write MVC5 apps with bootstrap and jquery. Perhaps I can help you out?
