### ISSUE TITLE
I have lots of RDPs, can it make a group list ? and save user/password auto ?

### ISSUE THREAD

**Issue by NickWoo33** [cedrozor/myrtille#61]
I don't want to type the ip in the index every time?

Can it make a list/ group with user/password in the index ?

just like some rdp client tool in the windows, such as mRemoteNG, a group with a list of RDPs. with user/passwword.

**Comment by cedrozor** [comment]
Myrtille doesn't have user group management but, in order to avoid typing you connection settings (server, user/password, etc.) every time, you can save them into an url bookmark using the [auto-connect syntax](https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#start-remote-application-from-url).

For example, https://localhost/Myrtille/?__EVENTTARGET=&__EVENTARGUMENT=&server=1.1.1.1&user=john&password=doe&program=&connect=Connect%21

Please note that all params listed in the above example url are required (not only server, user and password).

If you don't want the passwords to be saved in plain text, you can [hash them](https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#password-hash).

In the end, each url is like an .rdp file (as saved by mstsc or remoteapp).

You can save (bookmark) these URLs into folders, which make up for groups.

**Comment by NickWoo33** [comment]
I see, thanks :)
