### ISSUE TITLE
Save a cursor as a .cur file

### ISSUE THREAD

**Issue by thijsk** [cedrozor/myrtille#64]
I saw the todo to send the cursor to the brower as a .cur file instead of an ico.
See this code https://github.com/MathewSachin/NIco/blob/master/Models/Cur.cs to save a cursor to a .cur file. It's basicly an Icon file with a different header and the hotspots are in the Plane / BitsPerPixel fields.

**Comment by cedrozor** [comment]
Thanks! I guess you're refering to https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/GetCursor.aspx.cs#L73 (and the  CreateCursor method); I'll try this asap (if I can have the mouse cursor working for IE, it would be nice :))

**Comment by cedrozor** [comment]
Implemented into myrtille 1.6.0 (to be released soon).

I went into a slightly different way, adapting the code I found here: https://gist.github.com/darkfall/1656050 to create a .cur instead of .ico, following the outline described here: https://en.wikipedia.org/wiki/ICO_%28file_format%29#Outline

Mouse cursors are now working fine into IE (all versions) :)

Thanks again!

**Comment by thijsk** [comment]
Great work!
