### ISSUE TITLE
using websockets through port 80 and 443. I can add that for you if you like?

### ISSUE THREAD

**Issue by tmakaro** [cedrozor/myrtille#7]
So I noticed that you have a separate web socket server that you fire up using port 8181 and port 8431. (I wasn't able to get wss working but I did get ws working). The firewall has to be opened for this to work.

IIS 7.5 with .net 4.5 allows for web sockets directly through IIS using the default ports. I have done just this in one of my own projects.

I have just started taking a look at RemoteSessionSocketServer to see how it works but if you can give me some pointers that would be great :)

**Comment by cedrozor** [comment]
Yes, myrtille do use a custom websocket server (Fleck, open source written in C#) because in 2011, when I added HTML5 support to the product which preceeded myrtille, we were working with Windows Server 2008, IIS 7.0 and .NET 4.0. It was even working on Windows Server 2003, but when I upgraded from VS2010 to VS2015 lately, the MS VC++ 2015 redistributables refused to work under this OS...

Even if Fleck works very well, it's a good idea to use the native IIS 7.5+ features (and don't have to open ports on the firewall), so yes I would be glad to receive some help on that matter.

RemoteSessionSocketServer.cs is the actual myrtille websocket server implementation; it's used to received the client (browser) inputs (keyboard, mouse and touchscreen events) and pass them to the RemoteSessionManager.cs class (which, in turn, pass them to the rdp client (freerdp) through named pipes). The display updates are received by RemoteSessionManager.cs from the rdp client (also through named pipes) then sent to the client using the same, duplex, websocket (as the one used for inputs reception).

I didn't worked with IIS websockets but it would be basically the same logic (without the RemoteSessionSocketServer.cs class).

To get the wss working actually, if the port 8431 is opened, you have to check if you have an SSL certificate defined for the web application and a .pfx file (exported from the certificate) under the myrtille "ssl" folder. This is normally automatically done by the installer in the latest version (1.0.6, with a self signed certificate). You also have to access the myrtille homepage with "https://" instead of "http://".

**Comment by tmakaro** [comment]
I've started creating a myrtille.mvc project that supports web api. First I am going to replicate your default.aspx page using mvc and fleck and then I will replace the fleck server. 

I'm currently away for a wedding and will be back on Tuesday to start coding. :)
Troy

**Comment by cedrozor** [comment]
Thanks for your help :)
