### ISSUE TITLE
View and Access a Specific Session

### ISSUE THREAD

**Issue by welsonplay** [cedrozor/myrtille#71]
Is there any way to access a specific RDS session by passing the Session Id as a parameter?

Is there any way to request control of an active session?

**Comment by cedrozor** [comment]
The remote session is bound to an http session. In cookieless mode (default), you can get the http session id into the url (i.e: "(S(**j3okxa2sd3f0orerx4mb2rox**))", in bold); otherwise it's stored into the domain cookie. The cookie mode is configurable into the myrtille web.config, cookieless is preferred because it allows for multiple sessions/tabs.

Myrtille have a mechanism to prevent session fixation attack by generating a new session id upon login. Also, in order to prevent session stealing, it's advisable to use https://

You can indeed share an active session by sending its url to people you want to share with. This will allows collaborative work within this session, all browsers being synchronized.

Myrtille was not really intended for collaborative work, so there is currently a limitation to that. In HTML5 mode, there is only one websocket (duplex) by remote session, so only 1 browser will be able to control the remote session. If this is a wanted feature, I could allow multiple websockets by remote session and multicast any display update traffic on them. **In HTML4, using long polling, this limitation doesn't applies** (because there are as many long polling requests as http sessions), so you can have an mspaint drawing contest if you want to :)

Joke aside, it could prove useful to demo a software, or for an e-learning course. Myrtille lacks collaborative controls such as a presenter role (so that only one person could control the remote session), and being able to transfer it, but it should be enough for basic needs.

**Comment by welsonplay** [comment]
How can I enable multiple WebSockets per remote session?

**Comment by cedrozor** [comment]
It's not supported for now.

If someone is interested to improve the current code, it's there : https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/src/RemoteSessionManager.cs#L151, basically make it like **public RemoteSessionSocketHandler[] WebSockets { get; set; }**

**Comment by cedrozor** [comment]
I will implement that into the next version

**Comment by welsonplay** [comment]
Is there any forecast for the next version?

**Comment by cedrozor** [comment]
This month probably
