### ISSUE TITLE
AutoScale when launching myrtille client

### ISSUE THREAD

**Issue by Kiwy404** [cedrozor/myrtille#72]
Hi @cedrozor ,

I launch Myrtille client with this kind of url : 
`https://server/myrtille/?__EVENTTARGET=&__EVENTARGUMENT=&server=SERVER&domain=DOMAIN&user=User&password=PWD&program=&connect=Connect%21&width=1024&height=768`

Is it possible to autoscale Myrtille client without click on "Scale" button ?
I tried to edit Default.aspx and add a call to toggleScaleDisplay() or replace parameter scaleDisplay of startMyrtille(...) function at onload="..." but that dont work.
What i want is even if the display is deformed i want the 1024x768 resolution to fit entire client browser display without force users to click always on "scale" button.

Note :  I use Myrtille 1.5.0, is it also possible to set 8bits/16bits depth color to reduce bandwidth consumption ? 

Thanks for any suggestions

**Comment by cedrozor** [comment]
Hi, you can add the following:
```
// if not already enabled, enable scale display
if (!config.getScaleDisplay())
{
    var width = display.getBrowserWidth() - display.getHorizontalOffset();
    var height = display.getBrowserHeight() - display.getVerticalOffset();
    commands.push(commandEnum.SET_SCALE_DISPLAY.text + width + 'x' + height);
}
```
into the initClient() function ([here](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/js/network.js#L325))

Because the autoscale will always be enabled, you may also want to hide the scale button by adding the following into default.css:

```
#scale
{
    visibility: hidden;
    display: none;
}
```

Myrtille already uses 16bits depth color ([here](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/RemoteSessionProcess.cs#L98)). You can replace it by 8bits (256 colors) if you wish.

If you use graphical applications and want to save bandwidth, I suggest you to set the image encoding to AUTO instead of PNG ([here](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/js/config.js#L95)). It will encode each display update in both PNG and JPEG formats and send only the smaller sized (caution however, it will take more CPU server side).

There is also actually a display update size limitation on the updates pipe ([here](https://github.com/cedrozor/FreeRDP/blob/master/client/Windows/wf_myrtille.cpp#L69)). I will extend it on the next release (2048KB instead of 1024KB). It may explain why some pople have issues with some applications.

**Comment by TheWalkingCat** [comment]
Thanks for the quick answer, its exactly what i wanted !

Just another question, is Myrtille support natively restriction on server IP ? (example : expose myrtille gateway on internet via HTTPS and avoid everybody on the internet to use it as public gateway by restricting allowed connections to a list of servers ==> avoid VPN).

**Comment by cedrozor** [comment]
No. You can add such [IP restrictions on IIS](https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-8/iis-80-dynamic-ip-address-restrictions), or use a reverse proxy (better), such as [ARR](https://blogs.msdn.microsoft.com/chiranth/2014/08/03/application-request-routing-part-2reverse-proxy-and-troubleshooting-arr-urlrewrite-issues/) or [nginx](https://www.nginx.com/resources/admin-guide/restricting-access-tcp/)

**Comment by c-lillini** [comment]
Hi,
I am implementing a simple white list of servers that can be accessed. A PR could be interesting.

**Comment by cedrozor** [comment]
Hi Christian,
It's not really the responsibility of myrtille to do that (IIS has an access control and so do have proxies and reverse proxies); but why not indeed if it can help :)

**Comment by SeRom7640** [comment]
Hi Cedrozor,
I come back to you about autoscaling at begining of the session because I meet some strange behaviours I can't explain.  As said in #141, Websocket are now correctly installed but it happens that sessions do not start autoscaling when starting.  My quesion is : have I correctly put the autoscaling code in the network.js ?
![image](https://user-images.githubusercontent.com/39957946/51087273-7e48c980-1751-11e9-83c3-1a0174e2db57.png)
In fact my URL command line has size parameters defined to **&width=900&height=900**
900x900 is the place taken by the software running under the rdp session, so autoscaling will allow the visitor to view the rdp session in full screen mode on a tablet or smartphone.
But quite often, the session start with no scaling enabled whatever the device or the browser used.  I have to clic once on the scale button in the menu bar to activate scaling.
Easy to do on a PC, Mc or Ubuntu machine with mouse, but not on touch device.
Is it possible to defined the user size (**&width=900&height=900**) at the early beginning of the connection because I think there is sometimes a problem with the IF statement on line 339 (**_if (!config.getScaleDisplay())_**), perhaps at the wrong place ?
