### ISSUE TITLE
WebSocket connection

### ISSUE THREAD

**Issue by SieldP** [cedrozor/myrtille#78]
Hello,

Do you think that it possible to implement an other server than IIS (Nginx for example). I know that is complicated using asp but a lot of people use Win7 to run Myrtille. The problem is the WebSocket protocole isn't available with IIS under Win7. 
Any idea to set the WS protocol in Win7 or improve the Myrtille performance using long-polling network mode ?

Thank you

**Comment by cedrozor** [comment]
Hi, myrtille pre version 1.5.0 had a Fleck websocket server, which worked well under win7 (was even working nicely under windows server 2003). 

It's not so easy to just replace the websocket server by something else because it acts as a proxy for the myrtille webapp, forwarding the user inputs and setting the websocket on which to push the display updates.

About the long-polling mode, it's already optimized as much as possible; performance is very close to websocket (some people even prefer it for imaging applications as they found the throughput to be more consistent!).

**Comment by SieldP** [comment]
Thank you for your answer.
The problem with pre version 1.5.0 is that we have to open specific ports (by default 8181 and 8431) to use its ws. And it's not always possible when we use a 4G modem.

**Comment by cedrozor** [comment]
That's exact, It's a pity that's websocket protocol is only supported from IIS 8 :/
