### ISSUE TITLE
Improve scaling function

### ISSUE THREAD

**Issue by mak1311** [cedrozor/myrtille#79]
Hello,
Merry Xmas :p

I noticed that the scaling was done on the server side, this is not optimized when the bandwidth is low.
I suggest you to implement it in JS. 

This function allow the scaling : 
```
var canvas = document.getElementById("MyCanvas"); // must to set "Mycanvas" ID to the cavans when you instacy it
var ctx = canvas.getContext('2d');

function resize() {
	// Our canvas must cover full height of screen
	// regardless of the resolution
	var height = display.getBrowserHeight() - display.getVerticalOffset();
	
	// So we need to calculate the proper scaled width
	// that should work well with every resolution
	
	var width = display.getBrowserWidth() - display.getHorizontalOffset();
	
	canvas.style.width = width+'px';
	canvas.style.height = height+'px';
}

window.addEventListener('load', resize, false);
window.addEventListener('resize', resize, false);
```

And then, to adjust the mouse position input, you have to replace setMousePosition (in mouse.js file) functiion by this :

```
function setMousePosition(e)
    {
        var scrollLeft = (document.documentElement.scrollLeft ? document.documentElement.scrollLeft : document.body.scrollLeft);
        var scrollTop = (document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop);

        //dialog.showDebug('browser width: ' + display.getBrowserWidth() + ', height: ' + display.getBrowserHeight());
        //dialog.showDebug('scroll left: ' + scrollLeft + ', top: ' + scrollTop);
        //dialog.showDebug('horizontal offset: ' + display.getHorizontalOffset() + ', vertical: ' + display.getVerticalOffset());

        var oldHeigh =document.getElementById("height").value //debug:755
        var verticalOff =  display.getVerticalOffset(); //debug:33
        var ToolBarHei = display.getToolbarHeight(); //debug:28
		var BrowserHei = display.getBrowserHeight(); //debug:816
		//TEST HEIGHT: actual:783px new:1021px

		var actualY =(e.pageY ? e.pageY : e.clientY + scrollTop) - display.getVerticalOffset();
		var diff = (actualY/(BrowserHei-verticalOff))*(oldHeigh-BrowserHei+verticalOff+ToolBarHei);
		
		var diffWidth = (e.pageX/display.getBrowserWidth())*(display.getBrowserWidth() -document.getElementById("width").value);
		mouseX = (e.pageX ? e.pageX : e.clientX + scrollLeft) - display.getHorizontalOffset() - diffWidth;
		mouseY = (e.pageY ? e.pageY : e.clientY + scrollTop) - display.getVerticalOffset() +diff ;


        //dialog.showDebug('mouse X: ' + mouseX + ', Y: ' + mouseY);

		
		//Condition maximal + difference
        if (mouseX < 0 || mouseY < 0 || mouseX > display.getBrowserWidth() + scrollLeft - display.getHorizontalOffset() || mouseY > display.getBrowserHeight() + scrollTop - display.getVerticalOffset())
        {
            //dialog.showDebug('mouse out of bounds, ignoring');
            return false;
        }

        //dialog.showDebug('*************************');

        return true;
    }
```

By this way, it should be very helpful, scaling is instantaneous.

**Comment by cedrozor** [comment]
Hi,

Merry Xmas too!

Interesting. When I initially studied the scaling question, I checked it server side because FreeRDP already have an option for it, called [smart-sizing](https://github.com/FreeRDP/FreeRDP/blob/master/client/common/cmdline.c#L184) to fit the remote desktop to window size. They even added a param (recently) to adjust it [dynamically](https://github.com/FreeRDP/FreeRDP/blob/master/client/common/cmdline.c#L91).

In a similar way, I made the necessary calculations to scale both the [display updates](https://github.com/cedrozor/FreeRDP/blob/master/client/Windows/wf_myrtille.cpp#L392) and [mouse inputs](https://github.com/cedrozor/FreeRDP/blob/master/client/Windows/wf_myrtille.cpp#L1176), according to the current [browser resolution](https://github.com/cedrozor/FreeRDP/blob/master/client/Windows/wf_myrtille.cpp#L1030) and requesting a fullscreen update on [resize](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/js/user.js#L93).

I understand the benefits to do it client side. Your solution fit the canvas to the browser size, does it also scale its content (the remote session display)? what about the new display updates (are they also automatically scaled)? If the server isn't aware of the new resolution, you'll have to adjust the [addImage](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/js/display.js#L330) function.

Also, this would only work for HTML5; how could it be done for [HTML4](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/js/display/divs.js#L23) (no canvas)? I know this is a bit overkill, but the server side solution has the merit working for both ;)

Last but not least, I could use a pull request :)

Thanks!
