### ISSUE TITLE
Load balancing

### ISSUE THREAD

**Issue by welsonplay** [cedrozor/myrtille#81]
Does martylle support load balancing?

**Comment by thijsk** [comment]
It does as long as you can set sticky sessions on your loadbalancer. Because the freerdp process will be running on a single machine (through the myrtille backend) you'll need to keep sending the same session to the same webserver every time, otherwise it won't work.

**Comment by cedrozor** [comment]
Myrtille doesn't do any load-balancing by itself; a RD connection broker can do that, in a load-balanced RD Session Host server farm (as I stated in one of your previous questions: https://github.com/cedrozor/myrtille/issues/75)

**Comment by welsonplay** [comment]
In issue of Load Balance involving more than one Session Host was clear.

I wanted to know if it is possible to install Myrtille on two servers and put these two servers in Load Balance. It is possible? Does Myrtille support such scenarios?

**Comment by cedrozor** [comment]
Sure, you can load-balance the myrtille web servers and freerdp processes by installing myrtille on different servers. Then, if you connect the same connection broker, it should ensure load-balancing on the RDS farm and session pinning.

**Comment by welsonplay** [comment]
Many thanks @cedrozor  for responding super fast.

Obrigado @thijsk pelo esclarecimento.

**Comment by welsonplay** [comment]
I will have two servers with Myrtille installed for high availability, but I have seen that for me to use the encrypted password in the url, I have to encrypt the password on the same Myrtille server.

In my scenario I have two servers with Myrtille ese I encrypt User 1 password on Myrtille Server 1 and Load Balance send User 1 to Server 2. How can Server 2 decrypt the password?

Is there any alternative to this scenario?

**Comment by welsonplay** [comment]
I will have two servers with Myrtille installed for high availability, but I have seen that for me to use the encrypted password in the url, I have to encrypt the password on the same Myrtille server.

In my scenario I have two servers with Myrtille ese I encrypt User 1 password on Myrtille Server 1 and Load Balance send User 1 to Server 2. How can Server 2 decrypt the password?

Is there any alternative to this scenario?

**Comment by cedrozor** [comment]
Hey, good catch... I will think about it and get back to you

**Comment by welsonplay** [comment]
OK thank you!

What can be done is to use an encryption key that can be used by both servers to decrypt the password. I really wanted to help Myrtille work in High Availability and with Load Balance. So if you need help I'm at your disposal.

**Comment by c-lillini** [comment]
Hi,
I have the same problem and I'm thinking an asymmetric encryption.
@cedrozor, what's do you think about?

**Comment by cedrozor** [comment]
I wanted to use the same encryption as used by MS (see https://gallery.technet.microsoft.com/scriptcenter/Password-Text-String-34711a5e and older method https://www.remkoweijnen.nl/blog/2007/10/18/how-rdp-passwords-are-encrypted/) so that the same hash used by myrtille could also be used by mstsc into an .rdp file (and reciprocally).

The only change I made was to define the encryption scope to local machine instead of current user, because the user account running the powershell script (to generate the hash) is different from the user account running myrtille (either the webapp or service).

A solution would be to generate the hash under the same account as the user to connect and impersonate it with myrtille (the same way it's done for file transfer, with regards to domain authentication). That way, the decryption scope could be set to current user and would work whatever the myrtille server. Problem is, as the user password is encrypted, it's a catch22...

If you use an asymetric encryption (RSA, AES or whatever), you would need to generate/exchange public keys, which adds some complexity to something already not so simple...

**Comment by welsonplay** [comment]
you wanted to use the same Microsoft encryption, which could be used in the rdp file. I find this ideal solution. What problem did you inflict for not using MS encryption? Please could I have tips on how I could implement this encryption?

**Comment by cedrozor** [comment]
I explained why above... also have a look to the 2 links, for implementation

**Comment by welsonplay** [comment]
Need some change in the Myrtille code?

**Comment by cedrozor** [comment]
Yes, and because it's something quite specific, I won't implement it for now; but you can proceed as follow:
- assuming your myrtille servers are joined to a domain, create a "myrtille" domain user
- logon the myrtille domain user and modify the powershell script [Password51.ps1](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/Password51.ps1), with "CurrentUser" instead of "LocalMachine". Execute the script to hash your users passwords
- modify the [DecryptPassword](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Common/Helpers/RDPCryptoHelper.cs#L74) method to impersonate the myrtille domain user (you can use [this nuget package](https://github.com/mj1856/SimpleImpersonation)),  then replace DataProtectionScope.LocalMachine by DataProtectionScope.CurrentUser

The password decryption should now work whatever the myrtille server.
