### ISSUE TITLE
IPAD keyboard use possible?

### ISSUE THREAD

**Issue by tmakaro** [cedrozor/myrtille#9]
So I noticed that the IPAD's keyboard doesn't work. I suspect that is why you have the keyboard button and a popup textbox. Any thoughts on how to get the IPAD's keyboard working? If you give me some ideas I can try and get it working for you. I would really like the feature.

**Comment by cedrozor** [comment]
Yes, that was the idea of the keyboard popup. When it opens, it brings up the device keyboard and also allow to copy&paste some text and send it to the rdp session.
I thought about making a virtual, on-screen, keyboard but rejected it because it would be a pale copy of the device virtual keyboard (and would also have to be adapted for each resolution).
