### ISSUE TITLE
Any way to force screen resize?

### ISSUE THREAD

**Issue by srwsolutions** [cedrozor/myrtille#91]
Hi Cedric:
 
First of all, the right click toggle works like a charm.  Thanks!
 
One other thing I was wondering was if there is any way to setup a button to force the screen to resize to the browser's current windows size ( I mean to actually resize the rdp session rather than scale it)?   On the iPad you have to be careful when logging in to your rdp session to minimize the keyboard after typing in the signon information and before clicking  "connect".  If you don't the virtual keyboard is on the screen at the moment Myrtille checks the available room in the browser window and the resulting session ends up about half the size it should be because of the virtual keyboard still being visible.  Also, on windows or Linux, if you resize your browser window it would be nice to be able to cause Myrtille to resize the rdp session without having to terminate it and re-establish it if you want the session to fit in the newly sized window.
 
This certainly isn't a showstopper of any kind, but if it wasn't that difficult to do, it would be a nice feature.  
 
Scott W.

**Comment by cedrozor** [comment]
Hi Scott,

Indeed I had noticed that when I made the feature but, sadly, there is no way the resize the desktop into freerdp after the rdp connection has been established; only play with the scaling.

Cedric

**Comment by alexandrelozano** [comment]
Hi, on Guacamole you can set Reconnect for a resize method. What do you think about it?
You can reopen this issue with this approach?
Thank you,

**Comment by cedrozor** [comment]
Hi, yes it could be done but it implies to disconnect first then reconnect with the new size. 

There may be some issues; for example, if using a connection broker with session pinning, the same session will be reconnected; otherwise (in a load-balanced environment) it could be another session and the user will lose his work in progress.

Another scenario (less likely but anyway), if the user account is known to other people, another connection of the same user could steal the disconnected session during the small time lapse needed for reconnection.

**Comment by cedrozor** [comment]
You may want to check the [enterprise mode](https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#enterprise-mode), if your servers are on a domain.

Reconnecting a host is just 1 click away, there are extra configuration and security options, even publish one time access urls.

**Comment by cedrozor** [comment]
I hope I answered your question; please reopen otherwise
