### ISSUE TITLE
Any chance of SSO/OAuth support?

### ISSUE THREAD

**Issue by absolutejam** [cedrozor/myrtille#96]
I'm trialling this at the moment wih an Azure setup and it would be ideal if we could get it working with some kind of SSO solution. A lot of people are supporting OAuth these days, and in my selfish case, this could be amazing as Azure AD has a provider & also has SSO support.

I know this could be a **huge** ask, so I just wanted to throw it out there to see the feasability.

Really amazing work on this project by the way!

**Comment by cedrozor** [comment]
Hi,

Myrtille doesn't do the RD authentication by itself (not its responsibility); it delegates that to the RDS layer.

You can manage SSO through a connection broker; check these links depending on your Azure setup:
http://woshub.com/sso-single-sign-on-authentication-on-rds/
https://geekdudes.wordpress.com/2017/01/21/remote-desktop-services-lab-on-windows-server-2016/

Then, on the myrtille login screen, connect using your broker address instead of host.

Thanks for your support :)

**Comment by absolutejam** [comment]
Alright, cool. I'll have a look 👍 
Just to clarify, does Myrtille have to be on the same server(s) as the connection broker?

Cheers.

**Comment by cedrozor** [comment]
No, myrtille can be installed on a separate server. However, in order to be able to resolve hostnames (connection brokers redirections are using FQDNs), the myrtille server must either join the RDS farm domain or have its primary or secondary DNS configured to target the domain controller IP.
